### ISSUE TITLE
Problem in Penalized

### ISSUE THREAD

**Issue by reuning** [statnet/ergm#1]
I ran into a small strange problem while using MPLE.type "penalized."

The error I ran into was: "Error in if (loglik > loglik.old) break : \n  missing value where TRUE/FALSE needed\n"

I traced the problem back to ergm.pen.glm at line 120. From what I can figure out a rounding error was making it so pi==1. I solved this by adding the following lines. I am guessing this is really rare and don't think this is probably the best way to fix it, but it works well enough:

`pi <- ifelse(pi!=1, pi, max(pi[pi<1]) + (1-max(pi[pi<1]))/10)`
`pi <- ifelse(pi!=0, pi, min(pi[pi>0]) - (min(pi[pi>0])/10))`

**Comment by krivit** [comment]
Thanks for the analysis. Can I trouble you to provide an example to reproduce?

**Comment by reuning** [comment]
Yup. Here is a dropbox link with one of the networks I ran this on and got the issue: https://www.dropbox.com/s/rds9tpdabe5lwa9/Test_Net.RData?dl=0 

I tried to reduce it to the smallest possible formula where I'd still have the error and so below is the command that I found that led to this. This is on the most recent version ergm.

`ergm(net~edges+gwesp(decay=0, fixed=T),
     verbose=T, control=control.ergm(,MPLE.type = "penalized"))
`

**Comment by krivit** [comment]
Thanks. The problem is, indeed, that we get `pi` too close to 0 or 1, `log(0) = -Inf`, and then `0*-Inf = NaN`. In the context of logistic regression likelihood, the calculation should be under the specification `0*log(0) = 0` (which is also the limit).

**Comment by reuning** [comment]
Thanks!
