### ISSUE TITLE
edgecov changestats legacy comments

### ISSUE THREAD

**Issue by marioangst** [statnet/ergm#103]
A very small thing but the changestats implementation for edgecov contains some legacy comments that are not necessarily confidence-inspiring. Consider deleting?

![image](https://user-images.githubusercontent.com/19803038/61793485-89c32e80-ae1f-11e9-8b78-1bae1bdc29ba.png)

**Comment by martinamorris** [comment]
@chad-klumb would you please check this term to verify that it is doing the right thing, and if so, delete this comment?

**Comment by chad-klumb** [comment]
Thanks; I will look into this.

**Comment by krivit** [comment]
@chad-klumb , was this ever resolved?

**Comment by chad-klumb** [comment]
I did look at this awhile ago, and everything appeared fine.  I'll double check this weekend and update the code/issue.
