### ISSUE TITLE
set_attrs warning

### ISSUE THREAD

**Issue by smjenness** [statnet/ergm#110]
This occurs with any model fit with the current CRAN version of ergm:

```r
Warning message:
`set_attrs()` is deprecated as of rlang 0.3.0
This warning is displayed once per session. 
```

**Comment by martinamorris** [comment]
https://rlang.r-lib.org/reference/lifecycle.html

**Comment by martinamorris** [comment]
@krivit -- do i understand right that we need to update our code to remove set_attrs()?  if so, should we set this up as an issue.  and if so, which package(s)

**Comment by krivit** [comment]
Thanks for the report. It appears to already be fixed in `master`.
