### ISSUE TITLE
gwesp/dgwesp documentation

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#114]
- [ ] the documentation for gwesp suggests that when it is used on a directed network, the counts include all two-paths -- that would include both OTP and ITP.  That's not correct, it only counts OTP. https://github.com/statnet/ergm/blob/24db50b75caecd253be3e8cba4bf7fe29f44a6b6/man/ergm-terms.Rd#L1206-L1208

- [ ] there's also a hanging partial sentence that has to be deleted in the penultimate paragraph: https://github.com/statnet/ergm/blob/24db50b75caecd253be3e8cba4bf7fe29f44a6b6/man/ergm-terms.Rd#L1209 

- [ ] the configuration types for the directed *sp terms is missing the RTP option in the compiled man page output.  i can see it's listed in the "sptypes"  definition, so there may be a typo in that (long) line: 
https://github.com/statnet/ergm/blob/24db50b75caecd253be3e8cba4bf7fe29f44a6b6/man/ergm-terms.Rd#L185.

**Comment by chad-klumb** [comment]
`RTP` appears in the github ergm-terms man page (html) for me; it is not on CRAN as the commit that added it was made after the last push to CRAN

![ddspdoc](https://user-images.githubusercontent.com/10733914/63470328-35f93480-c421-11e9-8b9d-747d234d5964.png)

It looks like the hanging sentence should have been cut off, as it is subsumed in the \GWCutoff macro; I'll delete that.

I agree that the explanation of what is counted could be clearer, and should use terminology consistent with the other term docs.  I'll work on an update for that.

**Comment by chad-klumb** [comment]
@martinamorris Let me know if the PR doesn't address all of your concerns.

Here's what the docs look like now (click to enlarge):

![upddoc](https://user-images.githubusercontent.com/10733914/63472465-1533dd80-c427-11e9-9834-953e06f99ea9.png)

**Comment by chad-klumb** [comment]
updated

**Comment by martinamorris** [comment]
Two items still outstanding (see top note).

**Comment by chad-klumb** [comment]
AFAICT all three points in the op have been addressed in `master`.  They won't be reflected on CRAN until the next push.
