### ISSUE TITLE
are we printing the right (log) acceptance probability in SAN?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#119]
Currently, in `SAN.c` and `wtSAN.c`, we have the following chunk of code:

```
    /* Calculate the change in the (s-t) %*% W %*% (s-t) due to the proposal. */
    double ip=0;
    for (unsigned int i=0; i<m->n_stats; i++){
     deltainvsig[i]=0.0;
     for (unsigned int j=0; j<m->n_stats; j++){
      deltainvsig[i]+=(m->workspace[j])*invcov[i+(m->n_stats)*j];
     }
     ip+=deltainvsig[i]*((m->workspace[i])+2.0*networkstatistics[i]);
    }
    if(fVerbose>=5){
      Rprintf("log acceptance probability: %f\n", ip);
    }
    
    /* if we accept the proposed network */
    if (tau[0]==0? ip <= 0 : ip/tau[0] <= -log(unif_rand()) ) { 
      if(fVerbose>=5){
	Rprintf("Accepted.\n");
      }
    ...
```

It appears to me that the printed "log acceptance probability" is not correct for a few reasons:

- it gets the sign wrong
- it doesn't cap the log acceptance probability at zero
- it doesn't divide by the temperature when the temperature is positive
- it doesn't treat the temperature zero case separately

(In 72d6d83b9ec8d946de51f1aaa1070041ae8096c8 of #118 I simply subtracted off the offset contribution from `ip` in this diagnostic output, as that seemed to be most in the vein of the original, but that is still, of course, not the log acceptance probability.)

Is it worth modifying the code to address the above points, or is there a reason it was done this way in the first place?

**Comment by krivit** [comment]
No, you're correct. The acceptance probability that's printed comes from an earlier version of it and hasn't been updated,
