### ISSUE TITLE
Update built-in ergm terms to make use of ergm_get_vattr(), ergm_attr_levels(), and ergm_Init_*() API.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#12]
Currently, the `Init*Ergm*()` routines use their own message writing, and `Init*ErgmTerm*()` functions use `get.node.attr()`. Recently, new helper functions have been implemented:

* `ergm_get_vattr()` can extract and check nodal (vertex) attributes and their transformations in a robust and flexible manner.
* `ergm_attr_levels()` can similarly filter levels of a categorical attribute. 
* `ergm_Init_(warn|abort|inform)()` functions can print sensible error and other messages, incorporating information which `ergm` initializer is responsible.

In addition, two constants are exported:

* `ERGM_VATTR_SPEC`
* `ERGM_LEVELS_SPEC`

which can be used in the `vartypes=` argument of `check.ErgmTerm()` to specify permitted argument types for `ergm_get_vattr()` and `ergm_attr_levels()` respectively.

Porting existing terms to use these would make the interface for terms that use them more consistent and flexible.

**Comment by krivit** [comment]
See also `? ergm_get_vattr`.

**Comment by krivit** [comment]
@chad-klumb , @martinamorris , on further thought, I wonder if for terms like `sender()`, `receiver()`, and `sociality()`, we might want to use a different argument name from `levels`, since it's not intuitive levels of *what*. Perhaps `nodes`?

**Comment by krivit** [comment]
Another question: did we go overboard with converting terms? For example, `nodemix()` is *almost always* called with a `base` argument, which means the opposite of `levels`. That's going to break more code than anticipated. (IIRC, that's also why I implemented the `mm` term.)
@chad-klumb , @martinamorris , @sgoodreau , any thoughts?

**Comment by martinamorris** [comment]
> Another question: did we go overboard with converting terms? For example, nodemix() is almost always called with a base argument, which means the opposite of levels. That's going to
> break more code than anticipated. (IIRC, that's also why I implemented the mm term.)
> @chad-klumb , @martinamorris , @sgoodreau , any thoughts?

it will break things, we knew that, so there's the simple fix of telling 
ergm to use the old syntax, or the new fix of learning how to use levels.

the only thing i can imagine that would be better is an *implicit* 
recognition by ergm of the term "base" or "keep" that would automatically 
trigger it to use the old syntax.

**Comment by chad-klumb** [comment]
I think "converting" some terms and not converting others would be worse.

Making levels available throughout is a good thing, IMO.

If we really wanted to, we could selectively add base back to some terms where it would be useful.  Mixing terms come to mind due to their more complicated levels structure.

Being able to base by value could be useful as well (something you couldn't do with old base and still can't do with new levels).  But I wouldn't want to add it back to every term.

**Comment by krivit** [comment]
OK. I'm the more technically ambitious one, but I wanted to double-check with team members who are closer to end-users. If you're OK with it, I'm OK with it.

**Comment by martinamorris** [comment]
And I've used old fashioned email to raise some broader questions about this API change.  LMK if you'd prefer to have that discussed here on GitHub instead.

**Comment by krivit** [comment]
I think that we are finished with this. @chad-klumb , are there any terms left to convert?

**Comment by chad-klumb** [comment]
statnet/ergm#70 comes to mind

**Comment by martinamorris** [comment]
Did you leave in the option to invoke the 3.9 behavior?  That's still in the documentation for ergm-terms

Term versioning

When a term's behavior has changed from prior version, it is often possible to invoke the old behavior by setting and/or passing a version term option, giving the verison (constructed by as.package_version) desired.

https://github.com/statnet/ergm/blob/7fc9393d1bf659ee68175c46d7d35d0cb07b48f9/man/ergm-terms.Rd#L228

**Comment by krivit** [comment]
@martinamorris , yes, term versioning is still in place.

**Comment by chad-klumb** [comment]
all terms now use the new nodal attribute UI, and all InitErgm* message writing is through ergm_Init_*

couple notes:

get.node.attr is still called in 6 places in "version 3.9.4" code blocks

starmix terms don't have levels arguments (as noted in #107)
