### ISSUE TITLE
SAN documentation doesn't explain how acceptance probabilities are calculated

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#120]
In particular, it does not explain what effect offsets (finite or infinite) have on acceptance probabilities.

While the full acceptance probability calculation might be more information than most users want, I think we more or less have to explain it in order for the role of offsets to be understood.

**Comment by krivit** [comment]
Any takers?

**Comment by martinamorris** [comment]
@chad-klumb it seems like you have a good sense of what's needed.  do you have time to write something up?

**Comment by chad-klumb** [comment]
I can do this before the 3.11 release.
