### ISSUE TITLE
Poll: Name for "exclude most frequent level" levels= setting.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#121]
By default, `ergm` terms such as `nodefactor()` use the alphabetically first level as the baseline. E.g.,
```
library(ergm)
data(faux.mesa.high)
summary(fmh~nodefactor("Race"))
```
yields
```
nodefactor.Race.Black  nodefactor.Race.Hisp nodefactor.Race.NatAm 
                  243                    59                    35 
nodefactor.Race.Other nodefactor.Race.White 
                    5                  1552 
```
using "Asian" as the baseline.

This can be changed by the `levels=` argument, and one of the permitted inputs for it is a function that is evaluated on the attribute and its levels. Thus, let
```
# Encode attribute values into levels, tabulate their frequencies, find the level with the highest frequency, and return its negation:
f <- function(l, a){-which.max(tabulate(match(a, l)))}
```
Then,
```
summary(fmh~nodefactor("Race", levels=f))
```
yields
```
nodefactor.Race.Asian nodefactor.Race.Black  nodefactor.Race.Hisp 
                   54                   243                    59 
nodefactor.Race.NatAm nodefactor.Race.Other 
                   35                     5 
```
so Whites are now the baseline.

We can have `ergm` export a function that does this for the user. What shall we call it? Some ideas:

1. `NOTLARGEST`
1. `NOTBIGGEST`
1. `EXCLUDELARGEST`
1. `EXCLUDEBIGGEST`
1. `NOT_LARGEST`
1. `NOT_BIGGEST`
1. `EXCLUDE_LARGEST`
1. `EXCLUDE_BIGGEST`

Suggestions welcome.

Unfortunately, syntax of R doesn't let you pass `-f` as an argument without nonstandard evaluation alchemy, so something like `levels=-LARGEST` can't be made to work.

**Comment by krivit** [comment]
@martinamorris @sgoodreau

**Comment by sgoodreau** [comment]
Nice feature. I vote for EXCLUDE_LARGEST.

**Comment by krivit** [comment]
Thanks, @sgoodreau . Any other votes? @martinamorris ? @smjenness ?

**Comment by martinamorris** [comment]
I'm not fond of any of these, mostly b/c they're either cumbersome or odd.  But agree with Steve's suggestion, and would love it if it were possible to also include an alias/abbreviation "EL"

**Comment by krivit** [comment]
OK, I think I've figured out how to support a syntax along the lines of `-LARGEST` after all. (You have to overload the `-` operator.) I'll go ahead and implement it.

**Comment by martinamorris** [comment]
wonderful -- thx for your persistence!  -LARGEST makes so much sense from the end user perspective.  does it compromise anything else?  like, for example, tab completion?  i'd still be in favor of the overloaded operator, but i'm just curious.  and is ALL CAPS required?

**Comment by krivit** [comment]
I think tab completion will work for `LARGEST` (and now `SMALLEST`), but it never worked for `ergm` term names and arguments. However, the "arguments" will be misleading, since the end user isn't supposed to call it with `l` and `a` arguments.

All caps are my implementation decision, following the convention that "constants" like `TRUE` and `NULL` are in all caps. Would you prefer them in some other case?

Also, I just added a feature that lets you pass an argument to `LARGEST`, e.g., `LARGEST(2)`, it will select two most frequent categories, and similar. (`LARGEST` alone still works.) Also, I've now implemented `SMALLEST` analogously.

**Comment by martinamorris** [comment]
I'm fine with all caps given consistency considerations.  Nice additions too -- i can't think of a good use case for SMALLEST, but SMALLEST(#) would provide an easy way to put a bunch of small groups together.

**Comment by krivit** [comment]
In that case, would it be useful to have full-fledged algebra for level specification? In the scenario you describe, we might want something like
```nodefactor("a", levels=-LARGEST-SMALLEST(3))```
to use the largest group as the baseline and then omit the smallest three specify an indicator for them in another `nodefactor`.

It also sounds like we want to specify `LARGEST` and `SMALLEST` at the level of attribute extraction as well. I.e., we want to pass as `attr=` an argument that would result in a logical nodal attribute that is `TRUE` if the node belongs to the smallest 3 categories and `FALSE` otherwise, along the lines of
```nodefactor(IS_SMALLEST(3,"a"))```.

**Comment by martinamorris** [comment]
> n that case, would it be useful to have full-fledged algebra for level specification? In the scenario you describe, we might want something like
>`nodefactor("a", levels=-LARGEST-SMALLEST(3))`
>to use the largest group as the baseline and then omit the smallest three specify an indicator for them in another nodefactor.

Hmm, I think this might lead to some confusion, as it requires the user to remember to add the nodefactor for the smallest groups.  In terms of my workflow, I would typically explicitly recode `a` to combine the 3 smaller groups into one, then fit with `-LARGEST`.  If we could use some version of the syntax you're describing to accomplish that recode (it's wonderfully simple), that would make the most sense to me.  But I can see that what you're proposing accomplishes the same thing.

**Comment by krivit** [comment]
It sounds like what you want is some function like `attr=COMBINE_SMALLEST("a", 3, into="other")` (where pipe syntax a la `attr="a" %>% COMBINE_SMALLEST(3, into="other")` will still work) that will take the attribute vector, and return attribute `"a"` with the smallest three categories all renamed to `"other"`. This should be doable.

Any preferences as to the name? `MERGE_SMALLEST` is a little shorter.

**Comment by martinamorris** [comment]
yes, that would be great.

maybe COLLAPSE_SMALLEST.  if tab completion will work, length is not as impt.

**Comment by krivit** [comment]
That should do it. I'll close this issue for now, but let me know if any other shortcuts might be handy.
