### ISSUE TITLE
MSE from ERGM models

### ISSUE THREAD

**Issue by svish91** [statnet/ergm#127]
Hi 
I am trying to extract the Mean Square Error of the fitted models. 
I thought your anova function has the same functionality which returns F statistics and residual sum of square. 
However, I did not find a way to extract that.

Could you please suggest your opinion/suggestion in this regard? 

Thanks a lot.

**Comment by krivit** [comment]
MSE is not generally advisable for models with binary outcomes. `ergm()` provides deviances, AICs, and BICs, and `anova.ergm` provides analysis of deviance chi-squared tests.
