### ISSUE TITLE
Add simulation mean to gof boxplots

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#128]
This is particularly useful for the gof~model plots, where the goal is to verify that the E(stat) = obs.  But it would probably be useful for all plots.

A big blue dot would be my suggestion :)

**Comment by krivit** [comment]
I like the idea in principle. As noted in #170, current `plot.gof()` implementation is a mess and should be refactored, to pave the way for improvements such as this one. @martinamorris , how important is for this to end up in 3.11?

**Comment by martinamorris** [comment]
if it takes more than 30 min, not a priority.

**Comment by martinamorris** [comment]
Ok, I think we need to tinker with this a bit:

![image](https://user-images.githubusercontent.com/8194530/94718150-2deb1400-0306-11eb-8c0b-440e448215f1.png)

In retrospect, for the gof ~ model plots, am I correct that the simulated netstats are essentially "sampling distributions", and are expected to be roughly normal?  The boxplots are all quite symmetric, suggesting the answer is yes.  In which case, the median and mean are not going to differ much.

In any case, a less intrusive marker, perhaps distinguished by color rather than size (say * or +) might be a better choice.

**Comment by drh20drh20** [comment]
Not all sampling statistics will be roughly normal, though you're correct that many will.  Thus, the fact that the mean and median do not differ much is potentially informative.    
Fully agree regarding the less obtrusive marker!

**Comment by krivit** [comment]
Now using a blue rhombus as of 8b00975987aac64f4009279a88aaf51305e40bdb .
