### ISSUE TITLE
Error in documentation for new "levels" argument?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#132]
The current documentation in the `nodematch`  section reads:

> By default, matches on all levels k are counted. The optional levels argument controls which levels of the attribute should be included and which should be excluded. (See Specifying Vertex Attributes and Levels for details.) For example, if the “fruit” attribute has levels “orange”, “apple”, “banana”, and “pear”, then to include just two levels, one for “apple” and one for “pear”, use any of nodematch("fruit", levels=-(2:3)), nodematch("fruit", levels=c(1,4)), and nodematch("fruit", levels=c("apple", "pear")). This works for both diff=TRUE and diff=FALSE.

The error is: apple=2, pear=4, so the `base` equivalent should be levels=-c(1,3) and the `keep` equivalent is levels=c(2,4).  Right?

**Comment by chad-klumb** [comment]
Level indices are based on `sort(unique(attr))`, which would be `c("apple", "banana", "orange", "pear")` in this case.

**Comment by martinamorris** [comment]
Thanks.   Yet another source of confusion.  I'll take a stab at editing the help to clarify this for users.
