### ISSUE TITLE
Replace cycle() terms with better implementations.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#135]
The `cycle` term is implemented very inefficiently, and @CarterButts has contributed a [better version](https://github.com/statnet/ergm/files/4025660/ergm.semicycles_0.4-1.tar.gz), which should be folded into `ergm`.

**Comment by krivit** [comment]
@chad-klumb , can we call this one fixed?

**Comment by chad-klumb** [comment]
Should be fine to close.  A couple of notes:

- the documentation in `ergm.semicycles` said that cycle length could be between `2` and `N - 2`; I'm assuming `N` is the network size, so the upper bound should really be `N`; testing did not indicate any problems for cycles of length `N - 1` or `N`, so the final version of the documentation (now in `ergm`) gives the upper bound as `N`

- in `ergm.semicycles`, there was an undocumented `use.new` argument to the cycle term, and two versions of the C algorithm for cycle counting; based on light benchmarking the "new" version was the faster one, and looking at the code, it appeared the non-"new" version was basically the old algorithm tweaked to support semicycles, so in the version added to `ergm` I removed the non-"new" algorithm and use `use.new` argument and made the "new" algorithm the only option
