### ISSUE TITLE
Save full ergm call to fit object?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#136]
It would be nice to be able to recover the full ergm call from the fit object.  For example, if my call is:

> `fit <- ergm(faux.mesa.high ~ edges + nodefactor("Race") + gwesp(0,fixed=T),
>                      control=control.ergm(MCMC.interval=1e4))`

there is currently no simple way to recover the `control` setting that was changed.  The entire `control` list is saved as an element of the fit object, but good luck finding the one item you changed.

I don't know whether some of the other potential elements of a call (like `parallel`, and `psock`) are preserved in the fit object at all.

Request:  add an element to the list, maybe named "call", that would preserve the full call verbatim.

**Comment by sgoodreau** [comment]
Agreed, this would be handy!

**Comment by krivit** [comment]
OK, I've added it to `master`. Right now, `print.summary.ergm()` prints a formula, but not the rest of the call, by default. Do we want to change that?

Note that, say,
```
form <- faux.mesa.high ~ edges + nodefactor("Race") + gwesp(0,fixed=T)
ctrl <- control.ergm(MCMC.interval=1e4)
fit <- ergm(form, control=ctrl)
```
would produce identical output to the above, except that the call it will print will be
```
ergm(form, control=ctrl)
```
whereas the formula it would print would be
```
faux.mesa.high ~ edges + nodefactor("Race") + gwesp(0,fixed=T)
```

**Comment by martinamorris** [comment]
> OK, I've added it to `master`. Right now, `print.summary.ergm()` prints a formula, but not the rest of the call, by default. Do we want to change that?

no -- a summary should be a summary.

> Note that, say,
> 
> ```
> form <- faux.mesa.high ~ edges + nodefactor("Race") + gwesp(0,fixed=T)
> ctrl <- control.ergm(MCMC.interval=1e4)
> fit <- ergm(form, control=ctrl)
> ```
> 
> would produce identical output to the above, except that the call it will print would be
> 
> ```
> ergm(form, control=ctrl)
> ```
> 
> whereas the formula it would print would be
> 
> ```
> faux.mesa.high ~ edges + nodefactor("Race") + gwesp(0,fixed=T)
> ```
I'm not sure I like this behavior.  It would also require you to (again) look through the whole control object to try to find what you changed, right?

**Comment by krivit** [comment]
> no -- a summary should be a summary.

As with `lm()`, our summary is more verbose than a printing. In particular, `summary.lm()` prints the whole call.

> I'm not sure I like this behavior. It would also require you to (again) look through the whole control object to try to find what you changed, right?

It would. That's because the call only stores the variable names, not their contents. That said, we can probably implement a utility that can compare two control lists and point out the differences.

**Comment by martinamorris** [comment]
>       no -- a summary should be a summary.
> 
> As with lm(), our summary is more verbose than a printing. In particular, summary.lm() prints the whole call.

ok, sorry -- then i'm misunderstanding what you were asking.  i was 
thinking that summary(ergm object) should stay as it is.  but it would be 
nice to have access to the call with all of it's control modifications 
easily available somewhere in the fit object.

>       I'm not sure I like this behavior. It would also require you to (again) look through the whole control object
>       to try to find what you changed, right?
> 
> It would. That's because the call only stores the variable names, not their contents. That said, we can probably
> implement a utility that can compare two control lists and point out the differences.

ideal, for me, would be summary(object, verbose=T) returning, in addition, 
the non-formula elements of the call.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYSEMRRRYDUK5N6HGCDRC4GBDA5CNFSM4KNLKI32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL2
> QW5A.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by krivit** [comment]
I am increasingly inclined to change `print.summary.ergm()` to print the call rather than the formula by default, both for consistency with `summary.lm()` and with `print.ergm()`, and because in most cases, users *do* specify formulas and constraints as a part of one call. For that matter, if it's that important for someone to keep track of which formula they had used and yet they are storing formulas in variables, they can always use a descriptive variable name.

**Comment by sgoodreau** [comment]
> I am increasingly inclined to change `print.summary.ergm()` to print the call rather than the formula by default, both for consistency with `summary.lm()` and with `print.ergm()`, and because in most cases, users _do_ specify formulas and constraints as a part of one call. For that matter, if it's that important for someone to keep track of which formula they had used and yet they are storing formulas in variables, they can always use a descriptive variable name.

Yes, I think that is a good, simple approach. Provides important info easily in most cases, even if it isn't absolutely perfect.  But then again nothing is.
