### ISSUE TITLE
 Error in compact.rle(d) : could not find function "compact.rle" 

### ISSUE THREAD

**Issue by dth2** [statnet/ergm#139]
I just updated my ergm, tergm, network packages and now I am getting an ergm related error:

![image](https://user-images.githubusercontent.com/10469169/74491573-e439e000-4e80-11ea-886f-71d91ab79f02.png)

**Comment by martinamorris** [comment]
sessionInfo plz.  the most useful output is obtained from the sessioninfo package:

sessioninfo::package_info()

**Comment by martinamorris** [comment]
but if you just updated to `ergm-private` to test the `dev` branch you'll also need to update `statnet.common`

**Comment by krivit** [comment]
Should've probably soft-deprecated it in the first place.
