### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by leifeld** [statnet/ergm#14]
Hi there,

Recently, the `ergm` package version on CRAN (3.8.0) shows deprecation warnings of the form

> Warning: 'term.list.formula' is deprecated.
> Warning: 'ergm.update.formula' is deprecated.
> Warning: 'append.rhs.formula' is deprecated.

See here: https://cran.r-project.org/web/checks/check_results_ergm.html

My `xergm` package depends on `ergm` and thus shows some of those warnings as well. The CRAN maintainers asked me to remove these warnings from my package. When I pointed them to the dependency issue, they asked if I could contact you about it. Thanks for your support.

**Comment by krivit** [comment]
The version of `ergm` that fixes it, 3.9, has been in CRAN queue for about a week. I'll follow-up with them.

**Comment by krivit** [comment]
@leifeld Back in June, it got stuck in the CRAN queue, and we had to withdraw it. Does the new version (3.9.4) still show the warnings?

**Comment by leifeld** [comment]
I have removed any `statnet` and `statnet.common` dependencies from my packages in the meantime because the CRAN folks were bugging me about the warnings. I replaced them by dependencies on `ergm`, `network`, and `sna`, which worked fine.

**Comment by krivit** [comment]
OK. Apologies for taking so long to sort this out.

**Comment by leifeld** [comment]
No worries!
