### ISSUE TITLE
Implement a constraint to constrain "blocks" of dyads

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#140]
The idea is to replace `offset(nodematch(...))`, `offset(nodemix(...))`, and other hacks to prevent certain dyads from being toggled with a proposal-level constraint that will hopefully make things more efficient.

In principle, the implementation is a matter of generating an RLEBDM that is `TRUE` if the dyad may be toggled and `FALSE` if it's not. This should be fairly efficient if the nodal attributes are contiguous. E.g., if we only want to allow heterophilous ties, and the attribute vector is `aaabbb`, then we have an RLEBDM
```
...***
...***
...***
***...
***...
***...
```
with 11 runs (not 12, because column 3's `TRUE`s continue into column 4), but on the other hand, if it's `ababab`, then we have an RLEBDM,
```
.*.*.*
*.*.*.
.*.*.*
*.*.*.
.*.*.*
*.*.*.
```
with 31 (not 36 for the same reasons as above).

In terms of the user interface, some variants:
* There is nothing to stop us from implementing `InitErgmConstraint.nodematch` so that `constraints=~nodematch("a")` would either "lock" or "unlock", depending on the semantics we choose, those dyads for which `a[i]==a[j]`.
* We can implement an "operator", e.g., `Dyads(~nodematch("a"))`. Machinery like `ergmMPLE()` can be used to get at which dyads match the criterion. This will not be very efficient, however, since it would require querying every dyad. Using 4.0 APIs, we could also do this at proposal level.

@martinamorris @sgoodreau @chad-klumb @smjenness , please tag in whomever else might be interested.

**Comment by smjenness** [comment]
I'm curious how this would differ from my current approach to modeling constraints, which is to put them in the primary ERGM formula and set their target stats to 0. For example, nw ~ edges + nodematch("a"), target.stats = c(50, 0). I think Martina have other use cases where it does make a difference.

**Comment by sgoodreau** [comment]
It is a lot more efficient and thus faster.  Behind the scenes, offsets are continually proposing toggles which get evaluated, determined to have a logodds of -Inf, and then get rejected.  A true constraint prevents them from being proposed in the first place. In some models forbidden ties can represent the vast majority of dyads (for example with a small degree constraint) or a good chunk of them (e.g. nodematch with a small number of groups).  Some of the existing constraints operate as real constraints, while others are written to seem like constraints but just use a rejection-based algorithm behind the scenes.  True proposal constraints could thus lead to major upgrades in simulation speed.

**Comment by martinamorris** [comment]
Isn't there a formal term used to distinguish these two approaches: rejecting (based on the model weight) vs. not-proposing (based on a sample space constraint).  I feel like I've heard it, but forgotten it.

**Comment by martinamorris** [comment]
So, this approach does seem to offer the possibility of speed improvements in specific (important to us) cases -- I think the prime example is TNT for sparse networks; it doesn't constrain the sample space, but it does keep a (current) list of edges around to permit stratified sampling.  The same idea can be used for constraints to prevent sampling in this part of the sample space.

IIUC, the question is the tradeoff involved in the overhead of keeping track of the sample space as it changes over time, done via the `RLE` (run length encoding).  Each constraint/stratification will require it's own `RLE` implementation.  At some point, or for some implementations, or in some contexts the overhead may outweigh the efficiency gained. 

I'm not sure we know right now what that tradeoff looks like.  But I think it's worth exploring and benchmarking with some simple examples (if that's possible).

**Comment by smjenness** [comment]
Interesting. It will be important to do speed benchmarking against both Martina's use cases and mine; there have been some performance issues with formal model constraints in the past that have made me reluctant to use them.

**Comment by martinamorris** [comment]
> Interesting. It will be important to do speed benchmarking against both Martina's use cases and mine; there have been
> some performance issues with formal model constraints in the past that have made me reluctant to use them.

yes -- we're aware, and i think the idea is to fix that.

**Comment by sgoodreau** [comment]
> Interesting. It will be important to do speed benchmarking against both Martina's use cases and mine; there have been some performance issues with formal model constraints in the past that have made me reluctant to use them.

and I think that's largely (or at least in part) because some haven't actually been written as true constraints, but as pseudo-constraints that use rejection-based algorithms underneath.  so as martina suggested, there may be a big room for improvement here.

**Comment by krivit** [comment]
> IIUC, the question is the tradeoff involved in the overhead of keeping track of the sample space as it changes over time, done via the RLE (run length encoding). Each constraint/stratification will require it's own RLE implementation. At some point, or for some implementations, or in some contexts the overhead may outweigh the efficiency gained.

This depends on the implementation. The current mechanism generates an RLEBDM for each dyad-independent constraint, and I am very reluctant to change that, because a lot of things depend on this. (It may be possible to use memoisation or similar techniques to have them only be produced and stored on demand. Contrary to our conversation last week, i now think that it *would* help in that specific use case.)

That said, the quickest way to implement this is almost certainly via RLEBDMs.

# RLEBDM-based implementation

Now, if we implement specific constraints as special cases (e.g., `InitErgmConstraint.nodemix()`), then we should be able to construct the RLEBDMs pretty rapidly, at least if the vertex attributes are contiguous, since it's a matter of performing an RLE on the vertex attribute and then matching each element of the resulting RLE against each other and concatenating. In the case of the `aaabbb` example, the steps would be
1. Take an RLE of `aaabbb` to get (in pseudocode) `a*3 b*3`.
2.  Match the RLE against its first element (or, more precisely, anti-match) to get `F*3 T*3`, now the first element is repeated 3 times, so we get `F*3 T*3 F*3 T*3 F*3 T*3`.
3. Continue with subsequent elements and concatenate: `F*3 T*3 F*3 T*3 F*3 T*3 T*3 F*3 T*3 F*3 T*3 F*3`.
4. Compress the RLE: `F*3 T*3 F*3 T*3 F*3 T*6 F*3 T*3 F*3 T*3 F*3`.

If we want a more generic implementation, we can actually evaluate the change statistic for each dyad and compress. This is an `O(n^2)` procedure.

One option might be to have it go through a whitelist of `ergm` terms and if the term has an optimised implementation, use that, and if not, go through all the dyads.

# Specialised implementation

We could, in theory, have a specialised implementation that skips the RLEBDM and, like `bd` and `edges`, has a specialised proposal. This will be more troublesome if we want to combine multiple constraints. That said, we might want to have a specialised "block" proposal the way we currently have a block diagonal one.

# Submodel

In `dev`, we could, in theory, have the proposal call the corresponding `ergm` change statistic on the `C` side and filter out the dyads based on the response. Since this is for dyad-independent constraints, proposal symmetry is not violated. It does not rely on constructing an RLEBDM, but it is likely to be less efficient than the above approaches, because it's still a "rejection-based" algorithm, just that the rejection takes place a bit sooner.

**Comment by krivit** [comment]
In the meantime, what are y'all's thoughts about the two possible syntaxes for constrained blocks? (We can implement first and optimise later.) I.e., which would you rather use?
1. `constraints=~nodematch("a")` to fix dyads that match on `a` (and, perhaps, either `constraints=~!nodematch("a")` or `constraints=~nodematch("a", allow=TRUE)` to fix all dyads *but* those that match)
2. `Fixed(~nodematch("a"))` (and `Allowed(~nodematch("a"))`) respectively

**Comment by martinamorris** [comment]
i'm ok with both.  if (2), would like to be able to specify `constraints = ~Fixed(~!nodematch("a")` and it would be nice if there was a way to eliminate the second `~` there.

**Comment by krivit** [comment]
Based on the Skype call, I now think that `Fixed` is not ideal, and `Dyads` is better, since it's possible to "fix" the `nodematch` statistic by using a multiplicitous proposal that proposes to add a "matching" edge and simultanously remove one.

**Comment by krivit** [comment]
The current implementation is very general, in that it should take *any* configuraiton of dyad-independent term, but it's not very efficient, since it actually calls `ergmMPLE()` to go through every dyad and evaluate its change statistics to determine which dyads should be constrained.

Also, the current semantics are as follows. `Dyads(fix=,vary=)` takes one or two formulas, which are interpreted as follows:
1. Dyads matching *any* term/statistic in the `fix=` formula are fixed (and the rest are allowed to vary).
2. Dyads matching *any* term/statistic in the `vary=` formula are allowed to vary (and the rest are fixed).
3. If a dyad is fixed by one but not the other formula, it is allowed to vary.

A more intelligent parser might take just one formula instead, and rather than `+`-separated terms, have them be separated by logical operators (`&`, `|`, as well as `!`). Then, it would extract the terms, evaluate their corresponding RLEBDMs, and then combine them in accordance with the logical operations. E.g., `Dyads(~nodematch("a")&!nodematch("b"))` is saying that a dyad is fixed if it matches on `a` but does *not* match on `b`.

I think I have a pretty good idea for how to implement this. (R should take care of all the actual parsing.)

**Comment by krivit** [comment]
Implemented in `dev`.
