### ISSUE TITLE
Help fitting a network with high centrality

### ISSUE THREAD

**Issue by mberaha** [statnet/ergm#147]
Hi!
I'm trying to fit a network (undirected), with 100 nodes such that some nodes are not connected to any other node and the other (the majority) nodes are connected only to node _i_ .

I have tried dozens of combinations of features among `ergm.terms`, but once I try to simulate given the MLE estimate of the coefficients, I get completely different networks.

Can someone point me to some features that could lead to a nicer simulation result?

**Comment by martinamorris** [comment]
Hi Mario,

I'm not sure what you mean by "only connected to node i".  Are you 
trying to get a network with specific i-j ties only?

best,
mm

On Thu, 12 Mar 2020, Mario Beraha wrote:

> 
> Hi!
> I'm trying to fit a network (undirected), with 100 nodes such that each node is connected only to node i .
> 
> I have tried dozens of combinations of features among ergm.terms, but once I try to simulate given the MLE
> estimate of the coefficients, I get completely different networks.
> 
> Can someone point me to some features that could lead to a nicer simulation result?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYVNUJXBNQLT3KZAYBDRHDX35A5CNFSM4LGNYUV2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IUR5AV
> Q.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by mberaha** [comment]
Hi @martinamorris! Thanks for the super quick reply.

So the problem I am facing now is that I have several networks, among them there are some with the following behaviour
```
G[i^*, j] = 1 # for most values of j
```
and
```
G[i, j] = 0 # elsewhere (mostly)
```

For example
```
G = matrix(rbinom(100*100, 1, 0.05), nrow=100, ncol=100)
G[10, ] = rbinom(100, 1, 0.9]
```
my problem is to formalize an ERGM that can capture well this behaviour, and being a total beginner I'm not really sure which `ergm.terms` I should include

**Comment by martinamorris** [comment]
I'm still having a bit of trouble understanding your goal


On Thu, 12 Mar 2020, Mario Beraha wrote:

> 
> Hi @martinamorris! Thanks for the super quick reply.
> 
> So the problem I am facing now is that I have several networks, among them there are some with the following
> behaviour
> 
> G[i^*, j] = 1 # for most values of j

So you want some nodes to be connected to (almost) every other node

> and
> 
> G[i, j] = 0 # elsewhere (mostly)

but most nodes to be isolates?

This is inconsistent -- if the nodes above are connected to almost every 
other node, and you have an undirected network, then almost every node 
will have at least one tie.

> For example
> 
> G = matrix(rbinom(100*100, 1, 0.05), nrow=100, ncol=100)
> G[10, ] = rbinom(100, 1, 0.9]
> 
> my problem is to formalize an ERGM that can capture well this behaviour, and being a total beginner I'm not
> really sure which ergm.terms I should include
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYUM3UKPPK7LAO25VRTRHDZ3RA5CNFSM4LGNYUV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORP
> WSZGOEOUFJCA.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by mberaha** [comment]
Hi again, sorry for the inconsistency, I will try to be clearer.

The following is a valid example of the network I'm trying to model:
```
G = matrix(rbinom(100*100, 1, 0.005), nrow=100, ncol=100)
G[10, ] = rbinom(100, 1, 0.9)

G = G+t(G)
y = network(G)
```

So that there is one particular node `i^*`, which in this case is node 10, that is connected to almost every other node.
A part from this, the graph is practically empty elsewhere, meaning that for values of (i, j), with i different from `i^*`, I typically observe G[i, j] = 0.

I hope this i clearer, thanks a lot!

**Comment by martinamorris** [comment]
Thx for the clarification.  And do you want a specific node to be the 
hub?  Or any node, as long as the structure is hub-and-spoke?

On Thu, 12 Mar 2020, Mario Beraha wrote:

> 
> Hi again, sorry for the inconsistency, I will try to be clearer.
> 
> The following is a valid example of the network I'm trying to model:
> 
> G = matrix(rbinom(100*100, 1, 0.005), nrow=100, ncol=100)
> G[10, ] = rbinom(100, 1, 0.9)
> 
> G = G+t(G)
> y = network(G)
> 
> So that there is one particular node i^*, which in this case is node 10, that is connected to almost every other
> node.
> A part from this, the graph is practically empty elsewhere, meaning that for values of (i, j), with i different
> from i^*, I typically observe G[i, j] = 0.
> 
> I hope this i clearer, thanks a lot!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYUYZJ3XDFWJPFDNTUDRHD4KBA5CNFSM4LGNYUV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORP
> WSZGOEOUIBQQ.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by mberaha** [comment]
Yes any node would work to be the hub, as long as the graphs have this kind of topology!

**Comment by martinamorris** [comment]
G = matrix(rbinom(100*100, 1, 0.005), nrow=100, ncol=100)
G[10, ] = rbinom(100, 1, 0.9)
G = G+t(G)
y = network(G, directed=F)
degreedist(y)
fit <- ergm(y ~ degree(0:5) + degree(91))
sims <- simulate(fit, nsim=10, stats = T) # just the stats here
sims

delete the stats=T to get the networks.

On Thu, 12 Mar 2020, Mario Beraha wrote:

> 
> Yes any node would work to be the hub, as long as the graphs have this kind of topology!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYQG5AVS5JXBLE6NZVTRHD6TBA5CNFSM4LGNYUV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORP
> WSZGOEOUKTXY.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by mberaha** [comment]
Hi, thank you for your help!

I have ran your code, however I get extremely different results when I simulate from a `formula` object from what I obtain simulating from the `fit` object.
Is there something I am missing?

For example
```
G = matrix(rbinom(100*100, 1, 0.005), nrow=100, ncol=100)
G[10, ] = rbinom(100, 1, 0.9)
G = G+t(G)
y = network(G, directed=F)
fit <- ergm(y ~ degree(0:5) + degree(91))
```

These are kind of good, not exactly like the network y, but not so different.
```
sims <- simulate(fit, nsim=9)
dev.new()
par(mfrow=c(3, 3))
for (i in 1:9) {
  plot(sims[[i]])
}
```
while these are completely different!
```
sims <- simulate(network(100, directed=F) ~ degree(0:5) + degree(91),
                 param=fit$coef, nsim=9)
dev.new()
par(mfrow=c(3, 3))
for (i in 1:9) {
  plot(sims[[i]])
}
```
