### ISSUE TITLE
Need help with "fine tuning" edge terms

### ISSUE THREAD

**Issue by lc5415** [statnet/ergm#148]
Hello,

I've been playing with `statnet`, `ergm` and `Epimodel` for over a week now! I find most of the coding environment quite friendly and intuitive except for some of the `ergm-terms` to be fed into the formation formula. I have read the [specification of ergm terms paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2481518/), [the epimodel methods paper](https://www.jstatsoft.org/article/view/v084i08) as well as the statnet tutorial and the epimodel tutorials.

I will illustrate my struggle with an example, hopefully that is the best in which I can ask for help:

I am making a model of COVID in a refugee camp. For now, my network is very basic: I have 1000 nodes with an age attribute and a residence attribute. The age attribute corresponds to the age group of each individual and for now, it is assumed it does not affect the network structure. The residence attribute can take one of two values: _isobox_ or _tent_. I want nodes with the attribute value equal to _isobox_ to have in average 12 connections and for those in _tents_, 5 connections. 
My best guess for doing this at the moment is using `nodematch('residence', diff = TRUE)`. I also want to model some degree of mixing for which I am using `nodemix('residence', base = c(1,3))`. If my understanding is good and I should indeed use those functions then I am failing to set the statistics the right way, as my diagnostics do not fit the target values and even if they were I am not sure the statistics I am seeking would actually be encoded in the network.

<details> 
<summary> Find my implementation below </summary>

```
library(EpiModel)
n = 1000
nw = network.initialize(n = n, directed = FALSE)

nw = set.vertex.attribute(nw, "residence", c(rep("isobox", 470), rep("tent", 530)))
nw = set.vertex.attribute(nw, "age", rnorm(mean = 35, sd = 25, 100)) # this does not actually matter for now as it does not affect the network structure

formation <- ~edges+
  concurrent+
  nodematch("residence", diff = TRUE)+
  nodemix("residence", base = c(1,3))

mean_degree = 2
concurrent_percentage = 0.5 # % of nodes (people) with a degree of 2 or larger

edges = 1200
concurrent_nodes = 600
residence.iso = 20*20
residence.tent = 15*20
residence.mixing = 6*20
target.stats = c(edges,
                 concurrent_nodes,
                 residence.iso,
                 residence.tent,
                 residence.mixing)

d.rate = 0.0001
coef.diss = dissolution_coefs(dissolution = ~offset(edges),
                              duration = 5,
                              d.rate = d.rate) # this correspond to external deaths
est1 <- netest(nw,
               formation,
               target.stats,
               coef.diss,
               edapprox = T,
               verbose = F)

cores = parallel::detectCores()-1

dx = netdx(est1,
           nsims = 3,
           nsteps = 90, # simulating 6 months
           ncores = cores)
plot(dx)
dx
```
</details>

<details>
<summary> And the results I get for it: </summary>

```
EpiModel Network Diagnostics
=======================
Diagnostic Method: Dynamic
Simulations: 3
Time Steps per Sim: 90

Formation Diagnostics
----------------------- 
                           Target Sim Mean Pct Diff Sim SD
edges                        1200 1501.704   25.142 77.887
concurrent                    600  768.726   28.121 28.805
nodematch.residence.isobox    400  669.407   67.352 43.859
nodematch.residence.tent      300  545.948   81.983 28.651
mix.residence.isobox.tent     120  286.348  138.623 20.417

Dissolution Diagnostics
----------------------- 
               Target Sim Mean Pct Diff Sim SD
Edge Duration     5.0    4.730   -5.409  4.208
Pct Edges Diss    0.2    0.201    0.505  0.011
```
</details>

I still think I am not getting the implementation quite right so please let me know if there is something that I am failing to understand conceptually and also how one would go about implementing the specification I have described earlier.

**Comment by sgoodreau** [comment]
If you just want there to be a difference in mean degree between the two groups, but no selective mixing above and beyond that, then the term you want is `nodefactor("residence")`. 

Then you need to set up your target statistics correctly. It seems that you have 470 isobox nodes and 530 tent nodes, and you say you want them to have mean degrees of 12 and 5, respectively.  That implies that your network has an expected number of edges of (470*12 + 530*5)/2 = 4145.  But you have a target stat of 1200 for edges.  So you need to make sure your logic is consistent there.

Then the target stat for `nodefactor("residence")` should be the total degree for the nodes in each included category (by default, all but the first).  Here that means 530*5 = 2650.

The model knows that the expected total degree for the omitted category must then be the unique value that gets you to a weighted average of 4145, or 8190 in total degree.

With those set, you should get that part of the model to work correctly.

**Comment by krivit** [comment]
Sounds like this has been sorted. If not, please reopen and/or comment.

**Comment by lc5415** [comment]
Thank you for your answer, reading has been quite reassuring in grasping several concepts. I will now extend my question, I hope that is ok.

First I was wondering about the division by 2 in the calculation for the expected number of edges, is that because each edge is connecting two nodes or because the 2 possible attributes are available (_tent_ and _isobox_)? From your response @sgoodreau, I understand the total degree is a different thing to the expected number of edges, though intuitively I would have calculated 8190 as the expected number of edges in the network. My question here is, what is the number that the term `edges` expect?

Moving on, into my more specific issue. I have changed my approach since my first post. Then I was modelling my network in terms of whether people resided in isobox or tents, though there was no constraint on whether the edges were between tents, between isoboxes or between tents and isoboxes. Now I am attributing each node to a specific tent/isobox (tent1, tent2, isobox1... - attribute which I call _housing_) and modulating the number of edges that happen within the same _housing_ (i.e. isoboxes have a capacity of 10, tents have a capacity of 4 and I desire 80% of the edges (do this using `nodematch()`)  of each person to be within their housing). This can be seen as subnetwork within the greater network. I can satisfactorily model such a network for a small number of nodes, though the network degenerates as I expanded in size. 

<details> 
<summary> This is the code I've used to  model this network: </summary>

```
library(EpiModel)

SimulateNetwork = function(n = 200, diss.time = 30){
  #' Commented values correspond to the values for n = 200
  n = n # n = 200
  nw = network.initialize(n = n, directed = FALSE)
  
  prop.isobox = 0.43
  prop.tent = 1 - prop.isobox #0.57
  
  stopifnot(round(n*prop.isobox+n*prop.tent)==n)
  
  tent.capacity = 4
  iso.capacity = 10
  num_of_tents = round(n*prop.tent/tent.capacity) #14
  num_of_iso = round(n*prop.isobox/iso.capacity) #4
  
  num_in_tents = num_of_tents*tent.capacity #56
  num_in_iso = num_of_iso*iso.capacity #40
  
  housing = c(rep(paste0("tent", 1:num_of_tents),tent.capacity),
              rep(paste0("isobox", 1:num_of_iso), iso.capacity))
  #' [1] "tent1"  "tent2"  "tent3"  "tent4"  "tent5" 
  #'  "tent6"  "tent7"  "tent8"  "tent9"  "tent10"
  
  residence = c(rep("tent", num_in_tents),
                rep("isobox", num_in_iso))
  
  if (length(housing)<n){
    remaining = n-length(housing)
    print(paste(remaining, "nodes were left unassigned. Assigning them to new tent."))
    housing[length(housing)+(1:remaining)] = paste0("tent", num_of_tents+1)
    residence[length(residence)+(1:remaining)] = paste0("tent")
    num_of_tents = num_of_tents+1
    num_in_tents = num_in_tents+remaining
  }
  
  residence = residence[1:n]
  housing = housing[1:n]
  
  nw = set.vertex.attribute(nw, "housing", housing)
  nw = set.vertex.attribute(nw, "residence", residence)
  
  
  #######################################
  ##               Setting up formation statistics               #
  ######################################
  
  formation <- ~edges+
    nodematch("housing", diff = FALSE) # amount of interaction with same class nodes
  
  mean_degree.iso = iso.capacity # 10
  mean_degree.tent = tent.capacity # 4
  
  mean_degree = (sum(residence == "isobox")*mean_degree.iso+
                   sum(residence == "tent")*mean_degree.tent)/
    length(residence) # 6.5 (weighted average of the per-class degree)
  
  edges = n*mean_degree/2 # 312 (number of expected edge)
  
  housing.match = edges*0.8  # 525 (number of expected edges with people in the same housing)
  
  target.stats = c(edges,
                   housing.match)
  names(target.stats) = c("edges", "nodematch.housing")# doing this because of a silly error check
  
  ######################################
  ##              Setting up dissolution statistics              #
  ######################################
  
  d.rate = 0.0001
  coef.diss = dissolution_coefs(dissolution = ~offset(edges),
                                duration = diss.time, 
                                d.rate = d.rate) # this correspond to external deaths
  # coef.diss
  
  ########################################
  ##                  Network estimation (MCMC)                  #
  ########################################
  
  est1 <- netest(nw,
                 formation,
                 target.stats,
                 coef.diss,
                 edapprox = T,
                 verbose = F,
                 set.control.ergm = control.ergm(MCMLE.maxit = 100))
  
  # summary(est1)
  
  ##################################
  ##                         Diagnostics                         #
  ##################################
  
  cores = parallel::detectCores()-1
  
  dx = netdx(est1,
             nsims = 9,
             nsteps = 120, 
             ncores = cores,
             nwstats.formula = ~edges+
               nodematch("housing", diff = FALSE))
  # dx
  
  perc.error.edge = dx$stats.table.formation[1,3]
  perc.error.nodematch = dx$stats.table.formation[2,3]
  
  return(list(perc.error.edge, perc.error.nodematch))
  
}

```
</details>

Using this code, I've run several networks and obtained the following plot, this shows the pct difference between the number of estimated edges and the target for different values of the number of nodes n and the average edge duration. As you can as the edge duration decreases and the number of nodes increases the program struggles to fit the target statistics. 
![image](https://user-images.githubusercontent.com/47890755/81917110-ab6aed80-95cc-11ea-8873-020dd6debe84.png)

__Is there any known workaround to fit large networks with short edge duration?__, besides using `stergm`.


<details>
<summary> I can also verify that for small networks (n=200), the desired behaviour is roughly reached by looking at this plot: </summary>

![image](https://user-images.githubusercontent.com/47890755/81920962-d4da4800-95d1-11ea-8d26-701ea643adae.png)

Each row and column represents and individuals and they are ordered by housing. Most connections happen near the diagonal, i.e. in the same housing. And some connections happen externally.

</details>

**Comment by lc5415** [comment]
Hello @krivit , would it be possible to re-open this issue to get an answer on my latest question?

**Comment by sgoodreau** [comment]
Hi Luis - the 2 is because there are 2 nodes per edge, so # of edges always equals total degree across nodes, divided by 2.  Edges expects the total number of edges in the network. across all types.

Unfortunately, I am not available to go through your code and logic in detail at this point, but hopefully the response I just sent you via the epimodel listserv is sufficient to get you back on track.  Others may be able to, but as you can imagine we are all drowning in modeling work right now as well.

In general, the epimodel listserv is the best place for assistance with learning how to use the software, while github is best for requesting new features or bug fixes in the software.

HTH,
Steve

**Comment by lc5415** [comment]
Hello @sgoodreau, thanks for your reply and sorry for the inconvenience. I will now close this issue and wait for the answers in the epimodel listserv. 

Best of luck with the work at the moment

PD: I have not received your response via the epimodel listserv, maybe it was sent to a wrong address?

**Comment by sgoodreau** [comment]
@lc5415 I sent it to the listserv, and just confirmed it went. Will copy you directly now.  Perhaps you have the listserv settings to only get weekly digests or something similar?
