### ISSUE TITLE
Clean-up man page of summary.ergm()

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#154]
I was asked about "MCMC %" column in the output of `summary.ergm()` and thought of updating the man page. Small questions before I submit a PR:

1. Can I put `summary.ergm()` and `print.summary.ergm()` in the same source file? They are documented in the same page and it will facilitate the logical structure of the roxygenized Rd file.
2. Is there still a rationale for the extended meta-information in the commented sections at the top of the source files? Especially the second "frame" which seems to basically duplicate what's in the Roxygen comments. Can I delete it?

@krivit ?

**Comment by krivit** [comment]
The only argument I see against moving them into the same file is that it confuses change tracking and attribution in Git. I think that, in general, removing the stuff on top of the page is a good idea, assuming there isn't anything there that's not documented elsewhere.

**Comment by mbojan** [comment]
I'll leave it in separate files then. I should be able to workout the the proper structure/order with Roxygen alone. I'll make sure nothing gets lost from the top comments.

**Comment by krivit** [comment]
Thanks!

**Comment by mbojan** [comment]
While I'm at it, shall we have https://github.com/statnet/ergm/blob/093843a22c2fd42824e33d52f2b6eaf183f08d73/R/summary.ergm.R#L108 to use `.Deprecated()` or just simply remove the `digits` argument altogether?

**Comment by krivit** [comment]
Mabe use `statnet.common::.Deprecate_once()`.

**Comment by mbojan** [comment]
> Mabe use `statnet.common::.Deprecate_once()`.

Second thought: at this moment `digits` argument is documented, but should have been removed. Perhaps I simply remove it from the documentation? Do you still want to `deprecate_once()`. We need to remember to remove it in  the next-next release.

**Comment by mbojan** [comment]
I see more "inconsistencies" such as the one with `digits`. For example `correlations` is an argument to `summary.ergm()` but in fact is it is not used: it is returned (`ans$correlations`) but then not digested by `print.summary.ergm()` which has its own `correlations` argument with an independent default (`FALSE` in both cases).

Which seems more natural?

```r
# 1
fit <- ergm( ~ , ...)
summary(fit, correlations=TRUE)
```
or
```r
# 2
fit <- ergm( ~ , ...)
s <- summary(fit)
print(s, correlations=TRUE)
```

To me definitely 1. A minimally non-invasive solution could be for `print.summary.ergm()` arguments to default to corresponding elements of the object returned by `summary.ergm()`, e.g.:

```r
print.summary.ergm(x, correlations=x$correlations, ...)
```
and so on?

What do you think @krivit ?

**Comment by mbojan** [comment]
Another issue:

Is there still a need for `$coefs` and `$coefficients`? They differ only in the presence of `MCMC %` column. The documentation BTW incorrectly says that one has z-tests while the other does not. Shall we have just `$coefficients` (like `lm` and `glm`) and have `coef.ergm()` extract it (not `$coefs`)?

**Comment by krivit** [comment]
I think I kept both for backwards compatibility reasons. It may make sense to delete `$coefs` at some point.

**Comment by mbojan** [comment]
> I think I kept both for backwards compatibility reasons. It may make sense to delete `$coefs` at some point.

I'll make a separate issue for that.
Meanwhile closing.
