### ISSUE TITLE
Aborting on NA nodal attribute values in get.node.attr.R too restrictive

### ISSUE THREAD

**Issue by drh20drh20** [statnet/ergm#157]
For bipartite networks, even when nodal attributes are completely observed, some nodal attributes may be NA since not all attributes apply to both types of nodes.

**Comment by krivit** [comment]
Well, it looks like you can, but you can only do it by creating a dummy private repository, transferring to it, then making it public, then transferring from it to the final destination.

**Comment by drh20drh20** [comment]
OK, though isn't creating the "issue-mover" overkill? I'd have been happy to close this and then re-open a new issue in the public repo.  

In any event, my sense is that this issue should now be closed in ergm-private but please correct me if I'm wrong and forgive my naivete WRT this workflow.

**Comment by martinamorris** [comment]
> Well, it looks like you can, but you can only do it by creating a dummy private repository, transferring to it, then
> making it public, then transferring from it to the final destination.

lol, just open up a new issue on the public repo...

**Comment by martinamorris** [comment]
> OK, though isn't creating the "issue-mover" overkill? I'd have been happy to close this and then re-open a new issue in
> the public repo.
> 
> In any event, my sense is that this issue should now be closed in ergm-private but please correct me if I'm wrong and
> forgive my naivete WRT this workflow.

^ what he said

**Comment by mbojan** [comment]
> 
> 
> Well, it looks like you can, but you can only do it by creating a dummy private repository, transferring to it, then making it public, then transferring from it to the final destination.

Pavel, that's crazy.

**Comment by krivit** [comment]
@drh20drh20 , the issue has been relocated from `statnet/ergm-private` to `statnet/ergm`. You do not need to do anything.

I don't understand the drama. If you look at the logs, it took literally 3 minutes (and that includes creating the repository, which only needs to be done once) and preserved the comment discussion history.

**Comment by mbojan** [comment]
> I don't understand the drama. If you look at the logs, it took literally 3 minutes (and that includes creating the repository, which only needs to be done once) ...

No drama at all. Recalling the efficiency of your coding in the car on the way to Dave's house last year that 3 minutes could have been 1 or 2 new ERGM terms! ;)

> ... and preserved the comment discussion history.

That is an argument.

**Comment by krivit** [comment]
Back to the actual bug, someone needs to go through the bipartite terms that use nodal attributes and see which of them have this problem.

**Comment by drh20drh20** [comment]
That's one possibility.  Yet this happened because recent changes to get.note.attr broke terms that had been working fine, and it might be worth thinking about whether it's the terms that should change rather than get.node.attr.  
I think I'd probably lean toward changing the terms as well, simply because there's currently no way (I think) for get.node.attr to know that a nodal covariate is only relevant to the b1 or b2 nodes unless the terms themselves are changed.  Am I right about this?

**Comment by krivit** [comment]
To be precise, `get.node.attr()` is deprecated (though it looks like a deprecation warning was never added). `ergm_get_vattr()` is the function to use, and it's much more powerful.

The `ergm_get_vattr()` *can* be told to only check for NAs in `b1` or `b2`, but it's up to term implementation to tell it what it needs and what it doesn't need.

**Comment by krivit** [comment]
It would be good to fix it in the upcoming release. Any volunteers?

**Comment by drh20drh20** [comment]
One of my grad students is currently working on this.

**Comment by chad-klumb** [comment]
Beyond the `b*nodematch` stuff already being discussed, `b*degrange` and `gwb*degree` should also be looked at.

**Comment by drh20drh20** [comment]
I'm closing this issue and opening a related one in ergm-private, namely, to check all bipartite terms that use nodal attributes to make them consistent with one another AND add relevant tests.
