### ISSUE TITLE
Rename ergm$coef to ergm$coefficients for consistency with glm() and others?

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#158]
See also https://github.com/statnet/ergm/issues/154#issuecomment-661851689

`ergm` objects has `$coefs` and `$coefficients` elements, which is a redundancy kept for backward compatibility. Perhaps we could now only have `$coefficients` which is a convention of `lm()`, `glm()` and friends. `coef.ergm()` should then extract `x$coefficients`. 

Running `git grep "\$coef\b" R/*.R | wc -l` in package root shows 58 places, but some of them are false positives.

**Comment by krivit** [comment]
I'm OK with that. If we use `$coefficients`, we can get rid of `coef.ergm()` altogether, since `stats::coef.default()` will do.

**Comment by krivit** [comment]
Correction to this ticket: it's not `ergm` objects that have `coefs` and `coefficients`, it's `summary.ergm` objects. Whether we should rename `ergm$coef` to `ergm$coefficients` is a completely different one.
