### ISSUE TITLE
Add info on gof defaults to man page

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#16]
Would be useful to know how many networks are simulated by default -- you can see that now by clicking on the link to the control.gof.ergm function, but it's a basic enough bit of info that it would be worth including in the main documentation.

**Comment by chad-klumb** [comment]
@martinamorris I have added the sample size to the details section of the gof man page, which now reads:

![ss](https://user-images.githubusercontent.com/10733914/61836807-c2bacd80-ae36-11e9-9496-b38e8589196f.png)

(the last sentence being new).  Do we want any other additions here or is this good?

**Comment by martinamorris** [comment]
perfect Chad, thx so much!

**Comment by krivit** [comment]
@martinamorris, do @chad-klumb's changes resolve the issue?

**Comment by martinamorris** [comment]
looks good to me.
