### ISSUE TITLE
Add examples and/or unit tests for the san() family of methods.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#17]
Currently, `san()` help does not have any examples, and there are no tests in `tests/` testing its functionality directly. (It is tested indirectly, when `ergm()` is called with `target.stats=`.)

It would be good to
- [x] Add an example for using `san()`.
- [x] Add some tests (in the `testthat` framework, preferably) for its functionality.

**Comment by krivit** [comment]
@chad-klumb , can you issue the pull request for what you did as a part of your "audition"?

**Comment by chad-klumb** [comment]
yep; will do tomorrow

**Comment by krivit** [comment]
Fixed in 6848ba8d7cfffbdbb15ad1fbf59163773abf0db8 .
