### ISSUE TITLE
ergm.pl() code - documentation inconsistencies

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#173]
- [x] `xmat.full` element of the result is not documented
- [x] `foffset` element of the result is not documented
- [ ] `theta.offset` seems to be a logical vector indicating if a column of `xmat.full` is an offset or not. Man says it is a numeric vector. Perhaps depends on the model?

**Comment by mbojan** [comment]
It think `foffset` is basically the sum of all offset terms  (much like `stats::model.offset()`).

**Comment by mbojan** [comment]
Example when `theta.offset` is logical instead of numeric (as the man says):

``` r
trace(
  "ergmMPLE",
  tracer = quote({
    cat("Value of pl$theta.offset:\n")
    print(pl$theta.offset)
    }),
  at = 14
)

## Tracing function "ergmMPLE" in package "ergm"
## [1] "ergmMPLE"

ergmMPLE(
  faux.mesa.high ~ edges + offset(nodematch("Sex", diff=FALSE)) + offset(nodefactor("Sex")),
  theta.offset = c(F,T,T),
  output = "matrix"
)

## Tracing ergmMPLE(faux.mesa.high ~ edges + offset(nodematch("Sex", diff = FALSE)) +  .... step 14 
## Value of pl$theta.offset:
## [1] FALSE  TRUE  TRUE

## $response
## [1] 1 0 1 0 1 0
## 
## $predictor
##      edges offset(nodematch.Sex) offset(nodefactor.Sex.M)
## [1,]     1                     0                        1
## [2,]     1                     1                        2
## [3,]     1                     1                        2
## [4,]     1                     0                        1
## [5,]     1                     1                        0
## [6,]     1                     1                        0
## 
## $weights
## [1]    71  5515    50 10423    82  4769
```

**Comment by mbojan** [comment]
It think `foffset` is basically the combined effect of all the offsets, i.e. vector of sums of products of offset terms and their coefficients. C.f.: https://github.com/statnet/ergm/blob/df6d0022b024fcb5533984350be7049235416a1d/R/ergm.pl.R#L131

**Comment by krivit** [comment]
`theta.offset` is misdocumented. It's actually a vector specifying the coefficients of the offset statistics. Notably it has to have elements for the non-offset statistics as well, but those may be set to `NA`.

**Comment by krivit** [comment]
OK, maybe not. The parameter `theta.offset` was misdocumented, but the return element `theta.offset` serves two completely unrelated purposes, depending on whether the model has offsets. If the model has offsets, it is returned unchanged. If it doesn't, then it contains a "fallback" initial parameter vector, comprising the logit of the density of the network (slightly adjusted if the network is empty) with the rest padded by zeros---effectively assuming that the first statistic is `edges`.

I am going to make an executive decision and remove this fallback code.
