### ISSUE TITLE
predict.ergm() on a model with offset with -Inf coefs 

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#179]
~~Implement `predict.ergm.ego()` which will compute predicted probabilities for the pseudo-population network.~~

**Comment by mbojan** [comment]
> I've updated the PR on `ergm` to take all informative dyads automatically; once you upgrade to that version you should not need to set the `control` argument anymore.

@chad-klumb has it been merged by Pavel? I don't think I see it in the history.

**Comment by mbojan** [comment]
> i don't think `predict` takes this into account when calculating the p(tie). it does the right thing in terms of preventing same-sex ties. but doesn't calculate the probability of a tie for the _possible_ ties correctly.

@martinamorris I'm trying to understand what should be the expected behavior in case models with offsets. How about a small-scale example so that probs can be worked-out by hand:


``` r
# 4 nodes; 12 dyads
net <- network.initialize(4, directed=FALSE)
net %v% "a" <- c(1,1,2,2)

# Within 1: log(20/12); P=20/32=5/8
# Within 2: log(20/12) + 2*log(1/2) = log(20/12 * 1/4) = log(5/12); P=5/17
# Between: log(20/12) + log(1/2) = log(5/6); P=5/11

d1 <- predict(
  net ~ edges + nodefactor("a"),
  theta = c(log(20/12), log(1/2))
)
d1 # as computed above
```

    ##   tail head         p
    ## 1    2    3 0.4545455
    ## 2    1    4 0.4545455
    ## 3    3    4 0.2941176
    ## 4    1    2 0.6250000
    ## 5    1    3 0.4545455
    ## 6    2    4 0.4545455

``` r
d2 <- predict(
  net ~ edges + nodefactor("a") + nodematch("a"),
  theta = c(log(20/12), log(1/2), -Inf)
) 
d2 # nodematch offset does not affect between group dyads
```

    ##   tail head         p
    ## 1    1    2 0.0000000
    ## 2    1    3 0.4545455
    ## 3    1    4 0.4545455
    ## 4    2    3 0.4545455
    ## 5    2    4 0.4545455
    ## 6    3    4 0.0000000

``` r
# identical to previous
d3 <- predict(
  net ~ edges + nodefactor("a") + offset(nodematch("a")),
  theta = c(log(20/12), log(1/2), -Inf)
)

# All together now:
dplyr::full_join(d1, d2, by=c("head", "tail")) %>%
  dplyr::full_join(d3, by=c("head", "tail"))
```

    ##   tail head       p.x       p.y         p
    ## 1    2    3 0.4545455 0.4545455 0.4545455
    ## 2    1    4 0.4545455 0.4545455 0.4545455
    ## 3    3    4 0.2941176 0.0000000 0.0000000
    ## 4    1    2 0.6250000 0.0000000 0.0000000
    ## 5    1    3 0.4545455 0.4545455 0.4545455
    ## 6    2    4 0.4545455 0.4545455 0.4545455

So the -Inf nodematch offset zeroes the within-group tie probabilities but does not affect anything else because nodematch is 0 for those dyads and 0 * -Inf = 0. Or am I misunderstanding something?

**Comment by chad-klumb** [comment]
> > I've updated the PR on `ergm` to take all informative dyads automatically; once you upgrade to that version you should not need to set the `control` argument anymore.
> 
> @chad-klumb has it been merged by Pavel? I don't think I see it in the history.

I believe it was merged, yes.

**Comment by mbojan** [comment]
> `predict` may need to set maximum number of dyads or dyad types appropriately to ensure all dyads are represented in the result; this may explain your 2. if the return value from `predict` has fewer rows than your network's dyadcount; this would generally be an issue for larger networks (but has nothing to do with offsets)
> 
> dyads with infinite offset effects are omitted from the MPLE:
> 
> https://github.com/statnet/ergm/blob/8b00975987aac64f4009279a88aaf51305e40bdb/R/ergm.pl.R#L143-L148

`predict()` uses `xmat.full` so the result always has all the dyads

**Comment by chad-klumb** [comment]
If `MPLE.max.dyad.types` is exceeded then the sampling stops, and you won't get all the (free) dyads; it doesn't matter which part of the return value is used.

I assume (and correct me if I'm wrong) that the intent was to predict tie probabilities for all free dyads.

Since `indices` is a term in the formula passed to the MPLE, every free dyad has its own unique type, so the number of unique dyad types required is the same as the number of free dyads, which can be larger than the default `MPLE.max.dyad.types` of `1e6`.

**Comment by mbojan** [comment]
> If `MPLE.max.dyad.types` is exceeded then the sampling stops, and you won't get all the (free) dyads; it doesn't matter which part of the return value is used.

Ah, right. You are correct.

> I assume (and correct me if I'm wrong) that the intent was to predict tie probabilities for all free dyads.

Yes, the intention is to have all by default.
>
> Since `indices` is a term in the formula passed to the MPLE, every free dyad has its own unique type, so the number of unique dyad types required is the same as the number of free dyads, which can be larger than the default `MPLE.max.dyad.types` of `1e6`.

Yep.

**Comment by chad-klumb** [comment]
Also (and maybe this was a point of confusion), the two parts of my response to Martina that you quoted above were responding to *different* points she had raised; the thing about dyads with infinite offset effects being omitted from the MPLE was addressing her 1. below, while the thing about setting maximum number of dyad types was addressing her 2. below.

> thx @chad-klumb. a couple of questions:
> 
> 1. offsets are often used in glms, and these are typically dyad-independent models that rely on the estimation algorithm we use for MPLE.   i thought that estimate was, in fact, the MLE in the glm setting.   so why doesn't the MPLE work properly?  shouldn't it still try to match the edge and nodefactor counts by redistributing the forbidden ties to allowed dyads?
> 2. i'm getting a similar result -- (sum(predicted edges) != sum(observed edges) -- in my predictions from my MCMLE ergm fits in the WHAMP context.  do i understand correctly from your comment above that the MCMLE fits should produce the right predicted degree?  if so, then i still have another problem to dx.

**Comment by mbojan** [comment]
Yes, apparently... Sorry!

**Comment by chad-klumb** [comment]
No worries; I just wanted to be sure I wasn't confusing anyone (including myself!).

**Comment by mbojan** [comment]
So to summarise where we stand:

1. (Ad 1. above) Seems like actually an issue with `ergm.pl()` or `ergmMPLE()` as `predict.formula()` basically digests their output
2. (Ad 2 above) We could have `predict.formula()` too look at dyadcount of the supplied network and possibly adjust the `MPLE.max.dyad.types` control option. Or perhaps more preferably: just check one against the other and give a warning/suggestion to the user to set it manually.

**Comment by chad-klumb** [comment]
There are still some points to consider regarding `predict`.  I'm putting them here since this is the running `predict` issue atm.  We don't have to do all of this for `3.11`, though.

1.  Currently `predict` does not accept or propagate (from the fits) the `constraints`; this may lead to incorrect predictions for dyads that are fixed by the `constraints` formula but not (also) by infinite offsets in the model formula.

    Beyond this there is the issue of dyad-dependent constraints; I believe we do not currently have a dyad-dependent "conditionally free dyads" API, so even if `constraints` was handled by `predict`, if someone had e.g. `~bd(maxout=1)` but no corresponding offset in the generative model, they may wind up with incorrect predictions for "conditionally structural zeroes".

2.  As currently implemented I don't think there's a way for the user to override the (new) default of getting all the free dyads; we may wish to modify the implementation so the user can pass a different number of dyads to sample, if desired (with all free dyads remaining the default).

3.  In `master`, limitations of the `.C` API mean that we can't have `(# free dyads) x (# changestats)` exceed 32 bit limits.  We may wish to check for this before the `.C` call and give the user an informative error if it's going to occur (since the `long vector` error from `R` isn't optimally clear).

    In `dev` (which uses `.Call` instead of `.C`), we can exceed this limit, but we will run into problems with 32 bit variables in the `MPLE` C code.  If the number of free dyads itself exceeds 32 bit limits, we will also need to increase `MPLE.samplesize`, which defaults to `.Machine$integer.max` (32 bit max), and change how it's handled by the C code (since it can't be a 32 bit integer type anymore).  This is part of a more general problem of some things not working beyond 32 bit limits, even if we may quite reasonably want to exceed those (but fixing that is a `4.0` or beyond issue, not a `3.11` issue).

4.  The `MPLE` hash table machinery bogs down considerably as the number of unique sampled dyad types approaches the maximum number of unique dyad types.  Currently, the maximum number of unique dyads types is capped at the number of free dyads in `ergm.pl` (note that `d` is the number of free dyads):

    https://github.com/statnet/ergm/blob/749563012d464899d017c4142b9c90541ff69992/R/ergm.pl.R#L44-L45

    So, in typical `predict` usage, we will *always* completely fill the hash table (just as we finish sampling the free dyads), since `indices` gives each dyad its own unique type.  When the number of free dyads is large, things become extremely slow as the final small fraction of free dyads is sampled.  Increasing the maximum number of unique dyad types (i.e. the number of rows in the hash table) beyond what is actually needed can avoid this significant slowdown; in a simple test case with 15k nodes and just `edges` as the generative model, current `master` had not finished the `predict` call in 2 hours, while a test version changing only `min(...,d)` to `min(...,2*d)` in the quoted code above finished `predict` in ~ 1 minute.  Doubling the number of rows may be more than is needed, but it demonstrates the point.

**Comment by krivit** [comment]
From my (admittedly) fast read of this thread, the original issue in `ergm` `master` has been resolved, so this is no longer a 3.11 release blocker. Is that right?

**Comment by chad-klumb** [comment]
I believe the original issue has been resolved.

I would consider the linked PRs for inclusion in 3.11; they are small and basically independent of each other, so should be easy to review quickly, and I think they significantly improve performance/user friendliness.

With or without those PRs, I would say this is no longer blocking.

**Comment by mbojan** [comment]
I think so too.

@chad-klumb perhaps it is worthwhile to put:

> There are still some points to consider regarding `predict`. I'm putting them here since this is the running `predict` issue atm. We don't have to do all of this for `3.11`, though.
> (...)

in separate issues for further reference down the road?

**Comment by chad-klumb** [comment]
Okay, I think this issue has run its course so I'm closing it now.

I will post remaining todos elsewhere (possibly in `dev`) at a later date.
