### ISSUE TITLE
warning using levels in sociality term

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#188]
```
[1] ergm_3.11.0-5687   network_1.17.0-413
```

reprex:

```
library(ergm)
data("faux.mesa.high")
degs <- summary(faux.mesa.high ~ sociality(levels = T))

Warning message:
In term ‘sociality’ in package ‘ergm’: Argument ‘levels’ has been deprecated and may be removed in a future version. 
```
 
We're not deprecating the `levels` argument, are we?

**Comment by krivit** [comment]
We are. For `sender`, `receiver`, and `sociality`, the argument name is `nodes`, and `levels` and `base` are both deprecated in favour of it. However, it looks like whereas, we have an informative message for `base`, we don't have one for `levels`. I'll fix it shortly. Also, it looks like at some point, we deprecated `sociality(attr=)` argument.

**Comment by krivit** [comment]
The `levels` argument of `sociality` is actually attached to its `attr` argument, and they are being deprecated. Which nodes' statistics are to be included was formerly determined by the `base` argument but is now determined by the `nodes` argument.

**Comment by krivit** [comment]
So, this is Working as Intended (TM). On that note, we really do need that Roxygen extension for terms to keep track of all this.

**Comment by martinamorris** [comment]
Thx.   Is there a way to get all of the node values?  That's why I was trying `levels=T`

**Comment by krivit** [comment]
`nodes=TRUE`

**Comment by martinamorris** [comment]
What is the Roxygen extension?  Is that the "roclet" thing you mentioned a while back?

**Comment by krivit** [comment]
Yes: https://github.com/statnet/ergm/issues/28.
