### ISSUE TITLE
Move the `Init*` locator code in R/locator.R to statnet.common, document, and export.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#189]
At the moment, it comprises two functions:

- `locate.InitFunction()`, which searches the accessible namespaces for (exported and not) functions with a specific name and returns them in the form `ENV:::FUN` or prints an error message if one cannot be found.
- `locator_cache()`, which caches the past queries (because `getAnywhere()` used by `locate.InitFunction()` is very slow).

It turns out that they are also of use in `ergm.ego` (statnet/ergm.ego#52), but they are not exported. That they are not statistical in nature an may be of use elsewhere means that it makes sense to move them to `statnet.common`.

**Comment by mbojan** [comment]
Am I right that the problem of looking-up the terms across the packages is similar to S3 generics looking for methods? I'm thinking of ways that this could be leveraged, not necessarily directly.

**Comment by krivit** [comment]
Interesting idea. So, say, make `InitErgmTerm()` a generic, and temporarily set the class of `nw` to `c("edges","network")`, so that calling `InitErgmTerm(nw, arglist, ...)` dispatches to `InitErgmTerm.edges()`?
