### ISSUE TITLE
ergm_MCMC_slave function parameter name changes

### ISSUE THREAD

**Issue by smjenness** [statnet/ergm#19]
In the transition from `ergm.mcmcslave` to `ergm_MCMC_slave` in 3.9.4, you changed the names of two parameters:

1. `MHproposal` became `proposal`
2. `eta0` became `eta`

If that was intentional, I would suggest documenting those changes in your deprecation help page that covers `ergm.mcmcslave`. 

Additionally, in the deprecation function here:
https://github.com/statnet/ergm/blob/3.9.4/R/ergm.getMCMCsample.R#L238-L241

1. You switch from `MHproposal` that was in 3.8.0 (
https://github.com/statnet/ergm/blob/3.8.0/R/ergm.getMCMCsample.R#L241) to `proposal` without warning
2. There is a mismatch between `eta0` there and `eta` in the primary function definition here: 
https://github.com/statnet/ergm/blob/3.9.4/R/ergm.getMCMCsample.R#L265

**Comment by krivit** [comment]
Thanks for the report. Yes, the deprecated versions were meant to keep old argument names. It looks like I accidentally changed them.

**Comment by krivit** [comment]
@smjenness , do you think the deprecation notice and the documentation in `ergm_MCMC_sample` is not sufficient?

**Comment by smjenness** [comment]
If you are changing the parameter names back to their old versions (that is `MHproposal` and `eta0`) then I don't think any changes to the deprecation page would be needed.

**Comment by krivit** [comment]
The plan was to keep things backwards compatible via legacy functions, but simplify the parameter names and output formats for the new functions and make them more logical.

My thought was that someone would either get help for `ergm.getMCMCsample` or get the deprecation warning, then look up `ergm_MCMC_sample`, and update parameters accordingly. I can add a note to `ergm_MCMC_sample` help.

**Comment by krivit** [comment]
@smjenness Sorry about misreading your note earlier. Somehow, I saw the bit about `eta0` but missed the bit about `MHproposal`. It's too late for 3.9.4, unfortunately, but I'll probably end up pushing out 3.10 anyway, as soon as nobody is using the deprecated functions anymore.
