### ISSUE TITLE
Streamline printing of complex term calls

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#194]
e.g. nodecov(~cbind(Grade, Grade^2))

just print out `Grade` and `Grade^2` for summary and ergm output.  Similarly for `poly()`.

**Comment by krivit** [comment]
Reproducible example:
```{r}
library(ergm)
data(faux.mesa.high)
summary(faux.mesa.high~nodecov(~cbind(Grade, Grade^2)))
```
outputs
```
nodecov.cbind(Grade,Grade^2).Grade      nodecov.cbind(Grade,Grade^2). 
                              3491                              31123 
```

**Comment by krivit** [comment]
Unfortunately, this appears to be a a base R thing, not an `ergm` thing:
```{r}
x <- 1:5
colnames(cbind(x,x^2))
```
yields
```
[1] "x" "" 
```

There are two ways to work around it, but both require end-user intervention:
```{r}
colnames(cbind(x,x^2,deparse.level=2))
```
sets the column name even if it's not a valid symbol:
```
[1] "x"   "x^2"
```
and
```{r}
colnames(cbind(x,x2=x^2))
```
sets the column name manually:
```
[1] "x"  "x2"
```
and can be used to set an arbitrary name:
```{r}
colnames(cbind(x,`x^2`=x^2))
```
yields:
```
[1] "x"   "x^2"
```

The best remedy I can think of at the moment is:

1. If no column names are set, use numbered indices.
2. If all column names are set, use the set names.
3. If only some are set, fall back to numbered indices for *all* columns and issue a warning.

**Comment by krivit** [comment]
What remains to do:
- [ ] Update `InitErgmTerm.nodecov()` and others to drop the middle expression when column names are given.
- [ ] Update the vignette with examples same as those added to the `nodal_attributes` help.
- [ ] Update the ergm4 manuscript with examples same as those added to the `nodal_attributes` help.
- [ ] Updated the parallel implementation in `ergm.ego` to behave the same.

**Comment by drh20drh20** [comment]
If I understand correctly, https://github.com/statnet/ergm/issues/194#issuecomment-731425614 suggested (under "The best remedy...") that for a matrix with some column names set and others not, there would be numbered indices for all columns plus a warning.  Yet this doesn't appear to be happening:
```
> data(faux.mesa.high)
> ergm(faux.mesa.high ~ nodecov(~cbind(Grade, Grade^2)))$coef
Starting maximum pseudolikelihood estimation (MPLE):
Evaluating the predictor and response matrix.
Maximizing the pseudolikelihood.
Finished MPLE.
Stopping at the initial estimate.
Evaluating log-likelihood at the estimate. 
nodecov.cbind(Grade,Grade^2). 
                   -0.2710443 
Warning message:
In term ‘nodecov’ in package ‘ergm’: Attribute specification ‘~cbind(Grade, Grade^2)’ is a matrix with some column names set and others not; you may need to set them manually. See example(nodal_attributes) for more information. 
```
The warning is there but shouldn't the model have two statistics?  Or are we leaving it to users to read and act on the warning to avoid confusing results?

**Comment by krivit** [comment]
@drh20drh20 , what version are you using? I can't reproduce this.

**Comment by drh20drh20** [comment]
@krivit ,  aha:  It looks like I only get the above behavior using ergm-private.  I can still reproduce it using 4.0.6071 and 4.0.6074.  But using 3.11.0, I don't get the same behavior:
```
> ergm(faux.mesa.high ~ nodecov(~cbind(Grade, Grade^2)))$coef
Starting maximum pseudolikelihood estimation (MPLE):
Evaluating the predictor and response matrix.
Maximizing the pseudolikelihood.
Finished MPLE.
Stopping at the initial estimate.
Evaluating log-likelihood at the estimate. 
nodecov.cbind(Grade,Grade^2).Grade      nodecov.cbind(Grade,Grade^2). 
                       -0.48237886                         0.02406977 
```
I'll open an issue on ergm-private.
