### ISSUE TITLE
predict doesn't yield a correct predicted adjacency matrix for an undirected network.

### ISSUE THREAD

**Issue by komatsuna4747** [statnet/ergm#199]
# Example to replicate the bug
```
library(ergm)

# Prepare a network
g <- network::network.initialize(n = 3, directed = FALSE)
network::add.edges(g, tail = c(1, 2), head = c(2, 3))
network::set.vertex.attribute(g, attrname = "x", value = rnorm(3))

# Estimate logit
logit <- ergm(formula = g ~ edges + absdiff("x"),
              estimate = "MPLE")

# Get a predicted adjacency matrix
predicted_adj <- predict(logit, output = "matrix")

# This should be a 3 x 3 matrix, but...
predicted_adj
```
```
> predicted_adj
   2            3
1  0 4.607926e-11
2 NA 0.000000e+00
```
# Cause of the bug
This bug seems to come from `.df_to_matrix` function in `predict.formula`.

For undirected networks `tail` doesn't contain the last vertex id (3 in the above example), while `head` doesn't have the first vertex id (1 in the example). This results in returning a wrong matrix.
Moreover, the lower triangle elements are missing for undirected networks.

**Comment by mbojan** [comment]
Thanks. It is a bug indeed.

**Comment by krivit** [comment]
@komatsuna4747, thanks for reporting the issue and contributing a fix! I think that a simpler and more robust approach would be to take advantage of R's factors to tell `tapply()` how many rows and columns to use:
``` r
# Default case. Note that I am using data frames, because node IDs may be of potentially different type from the payload.
d <- data.frame(tail = c(1L, 2L),
                head = c(2L, 3L),
                p = c(0.5, 0.5))
d
#>   tail head   p
#> 1    1    2 0.5
#> 2    2    3 0.5
tapply(d$p,list(d$tail,d$head), identity) # Levels determined from composition of d$tail and d$head
#>     2   3
#> 1 0.5  NA
#> 2  NA 0.5

# Now, tell R what the potential values of tail and head are, and in what order.
df <- transform(d, tail = factor(tail, levels=1:3), head = factor(head, levels=1:3))
df
#>   tail head   p
#> 1    1    2 0.5
#> 2    2    3 0.5
tapply(df$p,list(df$tail,df$head), identity) # Levels and ordering specified.
#>    1   2   3
#> 1 NA 0.5  NA
#> 2 NA  NA 0.5
#> 3 NA  NA  NA
```

Take a look at the implementation of `network:::mixingmatrix.network` for an illustration. @mbojan , what do you think?

We might also want to externalise the function that takes a (p+1)-column data frame and constructs a p-dimensional array whose elements indexed by the first three columns have the values in the last column---unless R already has that function buried somewhere. (It might be a good candidate for `statnet.common`, since it's a general-purpose utility that could also be used in, e.g., `ergmMPLE()`.)

**Comment by krivit** [comment]
On further study, the following `replace()`-based syntax (suggested by https://stackoverflow.com/questions/47037504/r-converting-a-data-frame-of-row-column-indices-to-a-matrix#comment81026690_47037548 ) may be the fastest:
``` r
library(Matrix)
library(microbenchmark)

for(N in c(3L, 10L, 100L)){
  df <- data.frame(ROW = 1L:(N-1L), COLUMN = 2L:N, VALUE = rep(1,N-1L))
  cat("\n\n=== N = ",N," ===\n\n")
  print(
    microbenchmark(tapply=tapply(df[[3L]], list(factor(df[[1]],levels=1L:N), factor(df[[2L]],levels=1L:N)), identity),
                   replace=replace(matrix(NA,N,N), as.matrix(df[1L:2L]), df[[3L]]),
                   Matrix=as.matrix( sparseMatrix(j = df[[2L]], i= df[[1L]], x= df[[3L]])))
  )
}
#> 
#> 
#> === N =  3  ===
#> 
#> Unit: microseconds
#>     expr     min       lq     mean  median       uq      max neval cld
#>   tapply  94.377 103.4190 120.2406 111.765 132.7945  245.340   100  a 
#>  replace  74.009  82.4150 104.5882  94.487 111.6950  601.688   100  a 
#>   Matrix 648.296 724.1535 891.8929 749.010 797.5805 7604.623   100   b
#> 
#> 
#> === N =  10  ===
#> 
#> Unit: microseconds
#>     expr     min      lq      mean   median       uq      max neval cld
#>   tapply 108.414 123.988 138.88192 132.4880 146.7105  271.700   100  b 
#>  replace  76.203  84.338  99.30539  91.1915 109.3050  202.861   100 a  
#>   Matrix 651.823 713.919 768.35556 746.3245 789.9815 1245.045   100   c
#> 
#> 
#> === N =  100  ===
#> 
#> Unit: microseconds
#>     expr      min        lq     mean    median       uq      max neval cld
#>   tapply 3111.897 3592.6735 4118.247 3910.4440 4502.985 7435.726   100   c
#>  replace   94.388  150.0815  187.985  180.7595  220.198  346.449   100 a  
#>   Matrix  680.306  877.9770 1031.411 1000.8220 1133.947 2209.564   100  b
```

<sup>Created on 2020-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mbojan** [comment]
Thanks @krivit . Indeed my initial thought was to simplify the initial PR and use factors. The solution with `replace()` is neat.
BTW I'm surprised `sparseMatrix()` is so slow. Perhaps the timing includes the loading of the package? That's also not too sparse of a matrix.

**Comment by krivit** [comment]
I think it's more likely that what the code does is first construct a `sparseMatrix` object (or whatever it's called) and then essentially executes the `replace()` code to construct and populate the ordinary matrix. In any case, I think the `replace()` function is one of those underused functions, where `for` loops with assignments and `ifelse()` functions are used instead, and we should use it more often.

**Comment by mbojan** [comment]
... and I'll fix it as soon as I wave the students goodbye for Xmas.

**Comment by komatsuna4747** [comment]
Thank you guys for your comments! The solution with `replace()` looks much simpler and more robust. It'd be nice if this change is reflected soon, as the package I'm developing will benefit a lot from this modification. 

Wish you guys a Merry Xmas!

**Comment by krivit** [comment]
@mbojan , just checking in, are you planning to fix this? If not, I'll need to add it to my list.

**Comment by mbojan** [comment]
Yes I am.
