### ISSUE TITLE
Possible error in gradient computation for geometrically weighted terms

### ISSUE THREAD

**Issue by jrstew** [statnet/ergm#2]
I recently noticed a possible error in the implementation of the gradient for geometrically weighted terms. I have detailed findings and provide an example in the .pdf document: [etagrad_ergm.pdf](https://github.com/statnet/ergm/files/1565595/etagrad_ergm.pdf), which I attach here.

**Comment by krivit** [comment]
Thanks for the report. As it happens, we had fixed it in the "private" development version, but I never got around to fixing it in the public version. I'll go ahead and port the fix. Thanks for the reminder.
