### ISSUE TITLE
Potential problem with 'Dyads' operator vis a vis bipartite network term

### ISSUE THREAD

**Issue by drh20drh20** [statnet/ergm#201]
This is actually a good use case for the Dyads operator, if it could be made to work:

For the "globalExpansion" bipartite network dataset, the first 55 nodes are cities and the last 46 are firms.  Each firm has a particular type, as determined by `globalExpansion %v% "firm.type"`.

Suppose we want to look at the effect of each type, which is straightforward and has a meaningful interpretation, particularly if this is the base model used to build more complicated models.   Problem: It turns out that for the "Accountancy" firm type, all 5 of those firms are in each of the 55 cities.  So there is no MLE for the "Accountancy" effect.  Furthermore, we can't get correct estimates for the other three effects simplistically:

[globalExpansion.RData.zip](https://github.com/statnet/ergm-private/files/5675405/globalExpansion.RData.zip)

```
> unzip("globalExpansion.RData.zip")
> load("globalExpansion.RData")
> ergm(globalExpansion ~ edges + b2factor("firm.type", levels=3:4))$coef
                           edges b2factor.firm.type.BankingFinance            b2factor.firm.type.Law 
                       1.0986123                        -0.6931472                        -2.1972246 
```

In the output above, the BankingFinance and Law effects are correct but the baseline effect is the combined Accountancy/Advertising effect rather than just the Advertising effect that we desire.  What we'd like to do (to avoid creating a new network) is to fix the Accountancy edges in the estimation process or, equivalently, constrain the sample space to condition on the observed Accountancy-involved dyad values.  Here is a mathematically sloppy way to do it:

```
> ergm(globalExpansion ~ edges + b2factor("firm.type", levels=2:4))$coef
   edges    b2factor.firm.type.Advertising b2factor.firm.type.BankingFinance            b2factor.firm.type.Law 
18.31460                         -17.75499                         -17.90914                         -19.41322 
```
It's sorta correct in the sense that the three effects we care about are correct (we may verify that adding the edges estimate to the other estimates gives the same correct values for the BF and L effects), but it's sloppy because in this case the true "edges" estimate is actually `+Inf`.  Furthermore, the output is hard to interpret at a glance.  Finally, this is a strange thing to think of as a hack; why would a user be aware that defining a singular model will give you the desired answer in disguise?  (Indeed, one could argue that correct ergm behavior would be to throw a warning/error, and future behavior in fact might do this.)  So it would be much nicer to constrain the sample space.  However, this doesn't appear to work:
```
> ergm(globalExpansion ~ edges + b2factor("firm.type", levels=3:4),
+ constraints = ~Dyads(fix=~b2factor("firm.type", levels="Accountancy")))
Error in m | aperm(m, c(2L, 1L, 3L)) : non-conformable arrays
```

Shouldn't this example work to produce the following output?
```
                           edges b2factor.firm.type.BankingFinance            b2factor.firm.type.Law 
                       0.5596158                        -0.1541507                        -1.6582281
```

**Comment by krivit** [comment]
Because it doesn't require the 4.0 API, `Dyads` is actually implemented in `master`, so moved it to public.

**Comment by krivit** [comment]
I don't know who `@pavel` is, but he is probably at least somewhat confused right now.

Anyway, looking at this, what the error-inducing line of code does is, for an undirected network, to symmetrise the matrix of constrained/unconstrained dyads by OR-ing it with its transpose. However, `ergmMPLE()` returns a rectangular representation of a bipartite adjacency matrix (or, more precisely, an array of them stacked together), which causes the error.

The answer is that `ergmMPLE()` probably needs an `expand.bipartite=` argument (see #207 for a quick example) so that it could return a `network.size(nw)*network.size(nw)` square matrix that can then be converted to an RLEBDM (which is always square).
