### ISSUE TITLE
Unlike others, nodemix() and mm() don't have a baseline category. Should they?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#203]
For example, `nodefactor()` by default uses the lexicographically first category as baseline. Should the mixing terms do the same for the first combination (i.e., `levels2=-1`) by default?

```r
library(ergm)
data(faux.mesa.high)
summary(faux.mesa.high~nodefactor("Race"))
#>  nodefactor.Race.Hisp nodefactor.Race.NatAm nodefactor.Race.Other 
#>                   178                   156                     1 
#> nodefactor.Race.White 
#>                    45
summary(faux.mesa.high~nodemix("Race"))
#> mix.Race.Black.Black  mix.Race.Black.Hisp   mix.Race.Hisp.Hisp 
#>                    0                    8                   53 
#> mix.Race.Black.NatAm  mix.Race.Hisp.NatAm mix.Race.NatAm.NatAm 
#>                   13                   41                   46 
#> mix.Race.Black.Other  mix.Race.Hisp.Other mix.Race.NatAm.Other 
#>                    0                    1                    0 
#> mix.Race.Other.Other mix.Race.Black.White  mix.Race.Hisp.White 
#>                    0                    5                   22 
#> mix.Race.NatAm.White mix.Race.Other.White mix.Race.White.White 
#>                   10                    0                    4
summary(faux.mesa.high~mm("Race"))
#> mm[Race=Black,Race=Black]  mm[Race=Black,Race=Hisp]   mm[Race=Hisp,Race=Hisp] 
#>                         0                         8                        53 
#> mm[Race=Black,Race=NatAm]  mm[Race=Hisp,Race=NatAm] mm[Race=NatAm,Race=NatAm] 
#>                        13                        41                        46 
#> mm[Race=Black,Race=Other]  mm[Race=Hisp,Race=Other] mm[Race=NatAm,Race=Other] 
#>                         0                         1                         0 
#> mm[Race=Other,Race=Other] mm[Race=Black,Race=White]  mm[Race=Hisp,Race=White] 
#>                         0                         5                        22 
#> mm[Race=NatAm,Race=White] mm[Race=Other,Race=White] mm[Race=White,Race=White] 
#>                        10                         0                         4
```

**Comment by martinamorris** [comment]
Yes they should.  For consistency with the de facto standard in lm/glm/our attr-based network terms.  And b/c it's easy to specify the complete set of levels with `levels = TRUE`

**Comment by krivit** [comment]
Any objections? @sgoodreau , @drh20drh20 ? If not, it's a straightforward change, though implementing the `version=` setting may be a good idea.

**Comment by drh20drh20** [comment]
I've got no objections and Martina's point is well taken.  Plus, it's a bit odd if a simple-seeming model with just edges + nodemix or edges + mm gives an unidentifiable model.  So yes, I'd favor the change.  

I presume the version= setting would be to keep from breaking existing code?  This seems like a good idea in principle but I'm less clear about this choice...if people have been using the old versions then wouldn't they have already needed to fix the problem by hand?  I'd be OK with merely a warning in the documentation.

**Comment by sgoodreau** [comment]
Yes, I think this makes a lot of sense.

@drh20drh20 In theory some earlier users might have fit a model without an edges term.  Doubt it's common, but you never know.

**Comment by CarterButts** [comment]
@sgoodreau I routinely fit models with no edge term, if I am using a complete set of nodemix terms (since the interpretation often makes more sense).  For what that's worth!

But just to be clear, this is only relevant in cases where the edge term is present, yes?  I.e., with no edge term, full nodemix should include every statistic.  This is just about setting the contrast that we get when an edge term is included?  I agree that it would be nice to have that handled in a sensible way.

**Comment by krivit** [comment]
@CarterButts , the question is what should be the *default*. For example, `nodefactor` drops one of the categories by default, and a user who wants both of them needs to specify a `levels=TRUE` argument. In that, `nodemix` is inconsistent.

**Comment by CarterButts** [comment]
Reasonable enough.  BTW, I have to say that I find the levels/levels2 usage confusing, and the man page seem to repeatedly refer to a another section or page that is missing ("Specifying Attributes and Levels"), at least in the ergm version I have installed (3.11).  I am concerned about encouraging code-breaking changes, but if changes are already being made, perhaps it is worth thinking about whether the current syntax is clear (or maybe could just be explained more clearly).   For reference, here's what the section on nodemix has to say on the subject:

`
          By default, the
          ordering of the attribute values is lexicographic:
          alphabetical (for nominal categories) or numerical (for
          ordered categories), but this can be overridden using the
          ‘levels’ arguments.  The optional arguments ‘levels’,
          ‘levels2’, ‘b1levels’, and ‘b2levels’ control what statistics
          are included in the model, and the order in which they
          appear.  ‘levels2’ apply to all networks; ‘levels’ applies to
          unipartite networks; ‘b1levels’ and ‘b2levels’ apply to
          bipartite networks (see Specifying Vertex Attributes and
          Levels).
`

As noted, the specified section seems not to exist, and it's not obvious from the name alone what levels2 does.  Kind of confusing.  (The connection with the issue of the thread, to be clear, is that the meta-concern appears to be having clear expectations for how the various functions handling categorical variables will behave, and my sense is that setting the default contrast is only one piece of that puzzle.)

**Comment by krivit** [comment]
That's not a section. In the HTML or the PDF file, it would have been a link to another document. (See `? nodal_attributes`.) Unfortunately, it seems to be misleading in the text version. Open a separate ticket?

Perhaps we (who "we", kemosabe?) should develop a library of examples for each term; maybe even a picture gallery.

**Comment by krivit** [comment]
Here's a question for @martinamorris , @sgoodreau , @drh20drh20 , @CarterButts : do we still want the baseline `levels2=-1` if `levels=-1`, say. That is, if in the calls below, `levels2` were not specified, which behaviour would we want?

``` r
library(ergm)
data(faux.mesa.high)
summary(faux.mesa.high~nodemix("Race", levels=-1, levels2=TRUE))
#>   mix.Race.Hisp.Hisp  mix.Race.Hisp.NatAm mix.Race.NatAm.NatAm 
#>                   53                   41                   46 
#>  mix.Race.Hisp.Other mix.Race.NatAm.Other mix.Race.Other.Other 
#>                    1                    0                    0 
#>  mix.Race.Hisp.White mix.Race.NatAm.White mix.Race.Other.White 
#>                   22                   10                    0 
#> mix.Race.White.White 
#>                    4
summary(faux.mesa.high~nodemix("Race", levels=-1, levels2=-1))
#>  mix.Race.Hisp.NatAm mix.Race.NatAm.NatAm  mix.Race.Hisp.Other 
#>                   41                   46                    1 
#> mix.Race.NatAm.Other mix.Race.Other.Other  mix.Race.Hisp.White 
#>                    0                    0                   22 
#> mix.Race.NatAm.White mix.Race.Other.White mix.Race.White.White 
#>                   10                    0                    4
```

<sup>Created on 2021-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sgoodreau** [comment]
> But just to be clear, this is only relevant in cases where the edge term is present, yes? I.e., with no edge term, full nodemix should include every statistic. This is just about setting the contrast that we get when an edge term is included? I agree that it would be nice to have that handled in a sensible way.

To be clear, I was simply relying to Dave's comment: "I presume the version= setting would be to keep from breaking existing code? This seems like a good idea in principle but I'm less clear about this choice...if people have been using the old versions then wouldn't they have already needed to fix the problem by hand?"  That is, I meant that there are cases where users haven't needed to "fix" anything because nothing was broken for them, because they didn't have an edges term.

I was assuming that the discussion included setting a default value to be excluded regardless of other terms in the model., since checking other model terms seems complicated and confusing.  Seems like Pavel's f/up comment confirms that.  It's just a default, so we only need to cover the most commonly desired behavior, not all likely possibilities.

**Comment by drh20drh20** [comment]
I was about to write something akin to Steve's comment, namely, I don't think it's a good idea to try to have the default behavior of any term depend upon whether another term is included in the formula.  I'm not sure it's even possible to do this without some major code rewrites, but I'd strongly like to avoid going down that path.

Also:  Thanks, Steve and Carter.  Of course you're right that current default behavior that includes ALL levels need not lead to an MLE-less ERGM.  Shoulda noticed that!

**Comment by sgoodreau** [comment]
> Here's a question for @martinamorris , @sgoodreau , @drh20drh20 , @CarterButts : do we still want the baseline `levels2=-1` if `levels=-1`, say. That is, if in the calls below, `levels2` were not specified, which behaviour would we want?

That is a good question. I think the answer ultimately depends on what the most likely use cases are in this situation. None come directly to mind for me.

Barring that I see the arguments in favor as:
- Option 1: recognizes that, with levels=-1 set, that there no longer is a likely case of collinearity.
- Option 2: maintains consistency with the regular case with levels unset.  Might make sense if the reason that level 1 is excluded has something to do with there not being enough data or something like that.

I think I lean towards 2 for consistency but not strongly so.  Either way the decision should be included in the man page somewhere.

**Comment by martinamorris** [comment]
> BTW, I have to say that I find the levels/levels2 usage confusing, and the man page seem to repeatedly refer to a another section or page that is missing 

I totally agree -- this needs to be rationalized into a single levels vignette.  That's on my list, I just haven't been able to find the time.

**Comment by krivit** [comment]
In principle, we could develop an algorithm that acts on nonidentifiability detection results (i.e., are all MPLE predictors linearly independent?) and drops parameters (by fixing them at 0) accordingly. It's pretty straightforward, and perhaps by excluding dyad-dependent effects from the calculation, it could entirely avoid false positives. Then, it would make sense to set *all* default level selectors to `NULL`/`TRUE` and let the algorithm handle it (as it does in `lm()`).

Barring that, I agree with @sgoodreau  on predictability. Any other thoughts?

Regarding levels documentation, there is also the vignette, which is basically a copy of the help files.

**Comment by sgoodreau** [comment]
In theory we could do all of that, but in the end it feels to me like we're trying to be clever on the user's behalf in ways that end up annoying many users more than help them.  From @drh20drh20's last comment I think he feels the same. Yes?

**Comment by drh20drh20** [comment]
Strong yes to Steve's question.  I'd hate to see any attempt to have the default behavior attempt to act on nonidentifiability.  This seems unnecessarily complicated both on the coding side and, more importantly, from the users' standpoint.  Whatever we do, let's keep it simple.

**Comment by martinamorris** [comment]
I'll just point out that every other lm() and glm() function I've worked with *does* automate identifiability (as well as set a default omitted level), and it's something I've been asking for for years.  We don't have to do it right now, but I would like to see ergm implement this basic functionality as soon as we can.

**Comment by CarterButts** [comment]
I was coming from the same place as @martinamorris on this, particularly the idea of following lm()/glm() -like behavior.  But @sgoodreau, @drh20drh20, @krivit your points about the potential pitfalls are well-taken.  It also complicates initialization quite a lot, because in addition to needing terms to signal whether they are dyad dependent, we'd need them to signal something about whether they behave differently when there is an edge term.  And then, since combinations of them cause new complications, we probably need something clever-er to get good and consistent results.   

In light of these issues, having a "probably OK enough" default that works well in a typical "edge + term" model does seem like a reasonable compromise, so long as it stays easy to modify the default and the functionality is clearly documented (in a form that doesn't require HTML help, or RStudio, or vignettes, or whatnot).  We also need to make sure that we have good examples....

**Comment by drh20drh20** [comment]
Incidentally, I would favor addressing linear dependencies/non-identifiability _after_ a model is fit; just not trying to code a "smart default" that would attempt to head it off in advance by, say, dropping some factor levels before attempting a fit.  Do lm() and glm() do the latter?  I must admit I'm not aware of this type of thing but would be curious to see it in action.

**Comment by krivit** [comment]
@drh20drh20 , the problem with that is that whereas having nonidentifiability in `lm()` or `glm()` simply means that the QR decomposition reports a non-full-rank matrix and indicates which variables are redundant, in `ergm` that can mess with many aspects of the estimation algorithm.

**Comment by drh20drh20** [comment]
And that's a problem why?  A user can fix redundant variables and re-run the model after getting a report on why the original run didn't work out.  Alternatively, we can throw an error and report in such cases _before_ the model is run but after an initial, say, MPLE phase.  

On the other hand: I just tried a simple `lm` example and indeed, it appears that the interpretation of a factor can change, depending on whether there's an intercept in the model.  I did not realize this!  (Apologies to those of you who clearly did know already; I missed that nuance in Martina's and Carter's earlier comments.)
```
set.seed(123)
a <- LETTERS[sample(3, 30, replace=TRUE)]
y <- rnorm(30)
lm(y~a)$coef # WITH INTERCEPT: a HAS 2 LEVELS
(Intercept)          aB          aC 
 -0.4693585   0.2855755   0.2925610 
lm(y~a-1)$coef # WITHOUT INTERCEPT: a HAS 3 LEVELS
        aA         aB         aC 
-0.4693585 -0.1837830 -0.1767975 
```
So now I'm more sold on the virtue of implementing a similar capability for `ergm`.

**Comment by sgoodreau** [comment]
I also didn't realize that lm and glm do this.  So go forth.

**Comment by krivit** [comment]
Y'all realise that implementing this autodetection is going to take a while, right? Just because the maths are straightforward doesn't mean that seamlessly integrating it into our existing infrastructure and make sure it fails gracefully is going to be quick and easy, particularly in the presence of operator terms. I'll open a ticket.

For this ticket, the bottom line question is what the default values for `levels` and `levels2` should be in `nodemix()` and `mm()`. Do we some sort of consensus on that?

**Comment by martinamorris** [comment]
I hear you Pavel, and I'm not suggesting do it now.  Just joined the convo to say I think it's a good idea.

my preference for default values:  level 1, levels2(1,1)

**Comment by krivit** [comment]
@martinamorris , to clarify, do you mean that the default should be `nodemix(attr, levels=-1, levels2=-1)`?

**Comment by martinamorris** [comment]
@krivit if `levels2 = -1` omits the `(1,1)` cell in the mixing matrix, yes.

**Comment by krivit** [comment]
I agree at this point. Any objections?

**Comment by drh20drh20** [comment]
No objections.

**Comment by krivit** [comment]
The changes are in the branch `nodemix_mm_baseline`. Could someone please update the tests?

**Comment by krivit** [comment]
Ran into an issue finalising this: `hammingmix()` uses `nodemix()` as a helper function, but how should it behave? What should its defaults be? I've never used that. @drh20drh20 , @handcock , any thoughts?

**Comment by handcock** [comment]
I suggest removing it. It was an idea useful in the pre-separable STERGM days, but I have not used it since then. It is likely it is not used by others either.
