### ISSUE TITLE
Explanation and interpretation of valued ERGM terms - nodecovar

### ISSUE THREAD

**Issue by Yaxin-Cui** [statnet/ergm#204]
I am working on modeling a weighted (valued) network using valued ERGMs. However, I feel it is hard to understand the "nodecovar" term. In the ergm-term document, it was described as "Uncentered covariance of dyad values incident on each actor" and "can be viewed as a valued analog of the kstar(2) statistic". However, I cannot really understand what this statistic measures and how should we interpret it in an undirected network?

Thank you so much!

**Comment by krivit** [comment]
I believe it's discussed in detail in the Krivitsky (2012) paper (e.g., https://arxiv.org/abs/1101.1359). Again, I would recommend asking Statnet Help.

**Comment by Yaxin-Cui** [comment]
Thank you for your suggestion!
