### ISSUE TITLE
Improving convergence for valued-ERGMs

### ISSUE THREAD

**Issue by Yaxin-Cui** [statnet/ergm#205]
Hello,

I am working on valued-ERGM models and feel it is very hard to get the model converged. Given my network is quite sparse, where I have around 400 nodes and a density of 0.14, are there any general suggestions to make the model converged via "control. ergm"? 

Any resources are welcomed! Thanks so much!

**Comment by krivit** [comment]
This is more of a question about how to use the package, rather than an issue that can be fixed in the package. I suggest using https://mailman13.u.washington.edu/mailman/listinfo/statnet_help (though we are working on other places to ask for help as well).
