### ISSUE TITLE
Attribute ‘"years"’ has missing data, which is not currently supported by ergm

### ISSUE THREAD

**Issue by jszhao** [statnet/ergm#206]
```
library(ergm)
library(ergmharris)
data(lhds)
ergm(lhds ~ edges + nodecov('popmil') + nodefactor('years'))
```
 will give error message
```
Error: In term ‘nodefactor’ in package ‘ergm’: Attribute ‘"years"’ has missing data, which is not currently supported by ergm.
Run `rlang::last_error()` to see where the error occurred.
```

I run the above code with the latest `ergm` on CRAN:
```
> packageVersion("ergm")
[1] ‘3.11.0’
```

I try `3.10.4`, it run normally and give the following result.
```
MLE Coefficients:
             edges      nodecov.popmil  nodefactor.years.1  nodefactor.years.2  nodefactor.years.3  
           -6.2254              0.1966              0.1438              0.2793              0.3369 
```

My question is how the old version deal with the NA in the attribute "years", and how to workaround the NA in the new version?

I appreciate you for any suggestion or hint.

Best,
Jinsong

**Comment by krivit** [comment]
Thanks for reporting the issue! I believe the new behaviour is the correct behaviour.

I don't remember off the top of my head exactly what the 3.10.4 behaviour was, but we've added extra checks to the code in a number of places. The summary statistics (and therefore the coefficients) under 3.10.4 were probably not strictly correct.

**Comment by cliweichen** [comment]
Assigning the node with missing years to 0 can temporarily skip this problem, and the code is as follows:
years = get.vertex.attribute(lhds,'years')
years <- ifelse(is.na(years),0,years)
is.na(years)
lhds %v% "years" <- years
