### ISSUE TITLE
Mapping covariates to terms to coefficients

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#217]
Currently `ergm_model()` seems like a canonical way of querying the model structure, in particular via the `terms` element: it is possible to query the terms and get the names of the associated coefficients that in turn can be used to index coef vector and other things. For example:

```r
data("faux.mesa.high")
frm <- faux.mesa.high ~ nodefactor("Grade") + nodefactor("Race") +
  nodefactor("Sex") + nodematch("Grade",diff=TRUE) +
  nodematch("Race",diff=TRUE) + nodematch("Sex",diff=FALSE) + edges
fit <- ergm(frm)
em <- ergm_model(fit$formula, nw = fit$network)
str(em$terms)
## List of 7
##  $ :List of 6
##   ..$ name      : chr "nodefactor"
##   ..$ coef.names: chr [1:5] "nodefactor.Grade.8" "nodefactor.Grade.9" "nodefactor.Grade.10" "nodefactor.Grade.11" ...
##   ..$ inputs    : num [1:208] 0 5 205 -1 -1 3 0 2 2 0 ...
##   ..$ dependence: logi FALSE
##   ..$ minval    : num 0
##   ..$ pkgname   : chr "ergm"
##  $ :List of 6
##   ..$ name      : chr "nodefactor"
##   ..$ coef.names: chr [1:4] "nodefactor.Race.Hisp" "nodefactor.Race.NatAm" "nodefactor.Race.Other" "nodefactor.Race.White"
##   ..$ inputs    : num [1:208] 0 4 205 0 0 1 0 3 0 1 ...
##   ..$ dependence: logi FALSE
##   ..$ minval    : num 0
##   ..$ pkgname   : chr "ergm"
##  $ :List of 6
##   ..$ name      : chr "nodefactor"
##   ..$ coef.names: chr "nodefactor.Sex.M"
##   ..$ inputs    : num [1:208] 0 1 205 -1 -1 0 0 -1 -1 0 ...
##   ..$ dependence: logi FALSE
##   ..$ minval    : num 0
##   ..$ pkgname   : chr "ergm"
##  $ :List of 6
##   ..$ name      : chr "nodematch"
##   ..$ coef.names: chr [1:6] "nodematch.Grade.7" "nodematch.Grade.8" "nodematch.Grade.9" "nodematch.Grade.10" ...
##   ..$ inputs    : num [1:214] 0 6 211 1 2 3 4 5 6 1 ...
##   ..$ dependence: logi FALSE
##   ..$ minval    : num 0
##   ..$ pkgname   : chr "ergm"
##  $ :List of 6
##   ..$ name      : chr "nodematch"
##   ..$ coef.names: chr [1:5] "nodematch.Race.Black" "nodematch.Race.Hisp" "nodematch.Race.NatAm" "nodematch.Race.Other" ...
##   ..$ inputs    : num [1:213] 0 5 210 1 2 3 4 5 2 2 ...
##   ..$ dependence: logi FALSE
##   ..$ minval    : num 0
##   ..$ pkgname   : chr "ergm"
##  $ :List of 6
##   ..$ name      : chr "nodematch"
##   ..$ coef.names: chr "nodematch.Sex"
##   ..$ inputs    : num [1:208] 0 1 205 1 1 2 2 1 1 2 ...
##   ..$ dependence: logi FALSE
##   ..$ minval    : num 0
##   ..$ pkgname   : chr "ergm"
##  $ :List of 8
##   ..$ name                 : chr "edges"
##   ..$ coef.names           : chr "edges"
##   ..$ dependence           : logi FALSE
##   ..$ minval               : num 0
##   ..$ maxval               : num 20910
##   ..$ conflicts.constraints: chr "edges"
##   ..$ pkgname              : chr "ergm"
##   ..$ inputs               : num [1:3] 0 1 0
```

I'm looking into having a reliable way of mapping terms to the names of e.g. vertex covariates. I really do not want to `grep()` coefficient names... Is there any other structure apart from `ergm_model` that I could use?

If not, I think it would be a valuable addition to the objects returned by `InitErgmTerm.*()` functions. The initialization of the most of the covariate-related terms could simply return additionally the value of `attrname` as used in the term in the model formula,

My main motivation is to be able generalize VIF calculation from per-coefficient to per-term.

Any thoughts? @martinamorris @krivit

**Comment by krivit** [comment]
Some kind of reflection API is something I've been thinking about as well. One complication is that most terms now accept nodal attribute expressions, and so there needs to be a mechanism for figuring out that `nodecov(~Grade^2)` depends on nodal attribute `Grade`.

**Comment by mbojan** [comment]
Perhaps the first step could be to keep the unevaluated call of the term (as used in the formula) as an element of the list returned by the `initErgmTerm.*()`? Unfortunately I think this would require modifying all these init functions. If we are ever going after that I think it would make sense for the `InitErgmTerm.*()` functions to use some sort of constructor function to return its results so that changes like these will be less intrusive.

**Comment by krivit** [comment]
I don't think it necessarily requires modifying the individual functions. We can modify `ergm_model()` to tack the call on to the term after it's been initialised.

**Comment by krivit** [comment]
@mbojan , I can create a branch (probably off `dev`) that will store each term's call. What would be the next step?

**Comment by mbojan** [comment]
Awesome! Thanks. Can we do it on `master`? I'd like to use it in the implementation of VIFs which I already have half-baked on a branch off `master`. The small usecase there is to have a good *unique* label for the terms, i.e. different ones for `nodefactor("x")` and `nodefactor("y")`, which in turn I need to map to the row/cols of the `vcov` matrix.

I guess that if now the term functions accept expressions, the mapping term-attribute is no longer guaranteed to be 1-to-many. I need to think about usecases some more.

**Comment by krivit** [comment]
I can do it off `master` as well. The reason I was suggesting to do it off `dev` is because that's one of the places where the `master` and `dev` code differs, so I'd have to do it twice. Anyway, it's a one-line change so it's fine.

I don't have any use cases at the moment beyond just having to write "interpreters" every time I want to have reproducible tables.

It might make sense to add an option to `param_names()` to return, instead of the names from the `InitErgmTerm.*()` function, the deparsed term calls with an index tacked on.

**Comment by krivit** [comment]
Anyway, let me know what branch you want me to put it in.

**Comment by mbojan** [comment]
@krivit , let's do it on `master` then.

**Comment by krivit** [comment]
@mbojan , in the `term_metadata` branch off `master`, the term's call is now stored:
``` r
library(ergm)
data(sampson)
str(ergm_model(~edges+nodemix("group"), nw=samplike))
#> List of 9
#>  $ coef.names    : chr [1:9] "edges" "mix.group.Outcasts.Loyal" "mix.group.Turks.Loyal" "mix.group.Loyal.Outcasts" ...
#>  $ offset        : logi [1:2] FALSE FALSE
#>  $ terms         :List of 2
#>   ..$ :List of 9
#>   .. ..$ name                 : chr "edges"
#>   .. ..$ coef.names           : chr "edges"
#>   .. ..$ dependence           : logi FALSE
#>   .. ..$ minval               : num 0
#>   .. ..$ maxval               : num 306
#>   .. ..$ conflicts.constraints: chr "edges"
#>   .. ..$ pkgname              : chr "ergm"
#>   .. ..$ call                 : symbol edges
#>   .. ..$ inputs               : num [1:3] 0 1 0
#>   ..$ :List of 7
#>   .. ..$ name      : chr "nodemix"
#>   .. ..$ coef.names: chr [1:8] "mix.group.Outcasts.Loyal" "mix.group.Turks.Loyal" "mix.group.Loyal.Outcasts" "mix.group.Outcasts.Outcasts" ...
#>   .. ..$ inputs    : num [1:37] 16 8 34 2 3 1 2 3 1 2 ...
#>   .. ..$ dependence: logi FALSE
#>   .. ..$ minval    : num 0
#>   .. ..$ pkgname   : chr "ergm"
#>   .. ..$ call      : language nodemix("group")
#>  $ networkstats.0: NULL
#>  $ etamap        :List of 6
#>   ..$ canonical  : int [1:9] 1 2 3 4 5 6 7 8 9
#>   ..$ offsetmap  : logi [1:9] FALSE FALSE FALSE FALSE FALSE FALSE ...
#>   ..$ offset     : logi [1:2] FALSE FALSE
#>   ..$ offsettheta: logi [1:9] FALSE FALSE FALSE FALSE FALSE FALSE ...
#>   ..$ curved     : list()
#>   ..$ etalength  : num 9
#>  $ term.skipped  : logi [1:2] FALSE FALSE
#>  $ minval        : num [1:9] 0 0 0 0 0 0 0 0 0
#>  $ maxval        : num [1:9] 306 Inf Inf Inf Inf ...
#>  $ duration      : logi [1:2] FALSE FALSE
#>  - attr(*, "class")= chr "ergm_model"
```
<sup>Created on 2021-01-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mbojan** [comment]
Thanks @krivit ! Is there any argument against merging this into master? I'd be happy to take advantage of that in the VIF code.

**Comment by krivit** [comment]
No strong argument. I thought you were going to build the VIF code on top of it; is it for an external package?

**Comment by mbojan** [comment]
Sorry if I was too convoluted above. No external package. My point was that since I'm already working on it on a branch off `master` and we would like to merge it into `master` when done, then it will be easier for me to have this `ergm_model` extension merged into master so that my VIF branch can be rebased (or have `master` merged into it) with these changes. Otherwise I will have to rebase my VIF branch onto the `term_metadata` branch (or have it merged to my VIF branch) and the `ergm_model` will be merged into `master` together with my VIF code.

(apologies if this was even more convoluted for a rather cosmetic practical issue after all).

**Comment by krivit** [comment]
I see. OK, I'll merge it into `master`. I don't think it has the potential to break anything.

**Comment by krivit** [comment]
Done.

**Comment by mbojan** [comment]
Thanks!
