### ISSUE TITLE
In terms that take the levels2= argument, allow the user to specfy a logical matrix.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#218]
Specifying `levels2` can be confusing, since it depends on the order of combined levels of senders and receivers. For example,
``` r
library(ergm)
data(faux.mesa.high)
summary(faux.mesa.high~mm(~(Grade==7), levels2=TRUE))
#> mm[(Grade==7)=FALSE,(Grade==7)=FALSE]  mm[(Grade==7)=FALSE,(Grade==7)=TRUE] 
#>                                   125                                     3 
#>   mm[(Grade==7)=TRUE,(Grade==7)=TRUE] 
#>                                    75
```
<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

To select the heterophilous mixing, one needs to realise that the `FALSE`-`TRUE` combination is the second one on the list.

Using an R matrix to specify should be a bit easier on the end-user.

**Comment by krivit** [comment]
- [ ] Implement the `ergm_attr_levels.matrix()` function.
- [ ] Document the capability in the `nodal_attributes` help.
- [ ] Document the capability in the term documentation.
- [ ] Document the capability in the vignette.
- [ ] Add tests.

**Comment by krivit** [comment]
@martinamorris , @chad-klumb , here it is. @sgoodreau , what do you think?

``` r
suppressMessages(library(ergm))
data(faux.mesa.high)
summary(faux.mesa.high~mm(~(Grade==7), levels2=TRUE))
#> mm[(Grade==7)=FALSE,(Grade==7)=FALSE]  mm[(Grade==7)=FALSE,(Grade==7)=TRUE] 
#>                                   125                                     3 
#>   mm[(Grade==7)=TRUE,(Grade==7)=TRUE] 
#>                                    75
(M <- matrix(c(FALSE,FALSE,TRUE,TRUE),2,2))
#>       [,1] [,2]
#> [1,] FALSE TRUE
#> [2,] FALSE TRUE
summary(faux.mesa.high~mm(~(Grade==7), levels2=M))
#> mm[(Grade==7)=FALSE,(Grade==7)=TRUE]  mm[(Grade==7)=TRUE,(Grade==7)=TRUE] 
#>                                    3                                   75
(M <- matrix(c(2,1),1,2))
#>      [,1] [,2]
#> [1,]    2    1
summary(faux.mesa.high~mm(~(Grade==7), levels2=M))
#> mm[(Grade==7)=FALSE,(Grade==7)=TRUE] 
#>                                    3

data(faux.dixon.high)
summary(faux.dixon.high~mm(~(grade==7), levels2=TRUE))
#> mm[(grade==7)=FALSE,(grade==7)=FALSE]  mm[(grade==7)=TRUE,(grade==7)=FALSE] 
#>                                  1110                                    20 
#>  mm[(grade==7)=FALSE,(grade==7)=TRUE]   mm[(grade==7)=TRUE,(grade==7)=TRUE] 
#>                                    25                                    42
(M <- matrix(c(TRUE,FALSE,TRUE,TRUE),2,2))
#>       [,1] [,2]
#> [1,]  TRUE TRUE
#> [2,] FALSE TRUE
summary(faux.dixon.high~mm(~(grade==7), levels2=M))
#> mm[(grade==7)=FALSE,(grade==7)=FALSE]  mm[(grade==7)=FALSE,(grade==7)=TRUE] 
#>                                  1110                                    25 
#>   mm[(grade==7)=TRUE,(grade==7)=TRUE] 
#>                                    42
```
<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krivit** [comment]
@mbojan as well. @drh20drh20 , should this go into the paper?

**Comment by martinamorris** [comment]
I like the concept, and the execution.  Just a couple of questions:

1. It's confusing for the undirected case that `summary` shows 3 stats, but the matrix has 4.  Not sure what to do about that...
2. I don't understand how this case is working:


```
(M <- matrix(c(2,1),1,2))
#>      [,1] [,2]
#> [1,]    2    1
summary(faux.mesa.high~mm(~(Grade==7), levels2=M))
#> mm[(Grade==7)=FALSE,(Grade==7)=TRUE] 
#>                                    3
```

Why does the matrix only have 1 row?  And how do (1,2) map to (T,F)?

**Comment by krivit** [comment]
1. In an undirected network with the same attribute, the mixing matrix is symmetric, hence only three distinct statistics.
2. The full mixing matrix is as follows:
    | Sender \ Receiver | `FALSE` | `TRUE` |
    | --- | --- | --- |
    | **`FALSE`** |   |   |
    | **`TRUE`**  |   |   |

    Cell (2,1) therefore corresponds to (`TRUE`,`FALSE`), but since it's symmetric, it gets mapped to (`FALSE`,`TRUE`).

**Comment by martinamorris** [comment]
Thx for the explanation of (2,1), and that's another nice option for specifying the constraint.

I understand the undirected network issue, I'm just pointing out it's a bit confusing to have a 3 level statistic and a 4 level specification matrix.  That will need documentation...

**Comment by krivit** [comment]
> That will need documentation...

Indeed, *someone* should probably write better documentation. :-) I've pasted basically this example into the help and the vignette, but something more narrative would help.

**Comment by sgoodreau** [comment]
Agreed, the idea is great, and the execution overall clear (except for the perpetual issue that undirected networks need triangular matrices, which are a weird messy thing relative to square matrices, in general and in R). I really like the face that you can specify it as a logical matrix, or as a 2-column list of cell positions. Thanks!
