### ISSUE TITLE
simulate.ergm() yields an empty MCMC traceplot when control$MCMC.runtime.traceplot = TRUE.

### ISSUE THREAD

**Issue by komatsuna4747** [statnet/ergm#222]
# Problem

I would like to check if simulated networks are OK by inspecting MCMC traceplots. As far as I look at the document, `control$MCMC.runtime.traceplot = TRUE` seems what I need.

However, it only yields an empty MCMC traceplot as attached, while it works when estimating an ERGM.

![traceplot_sim](https://user-images.githubusercontent.com/27943678/107479578-aa4c0880-6bbe-11eb-82cb-40693973c689.png)

# Code to replicate the issue
```
library(ergm)
g_seed <- network(x = 20, density = 0.1, directed = FALSE)

# This yields an empty traceplot...
g <- simulate(g_seed ~ edges + triangle,
              coef = c(-2, 0.1),
              control = control.simulate.formula(MCMC.runtime.traceplot = TRUE))

# When estimating an ERGM, it works.
data(florentine)
result <- ergm(flomarriage ~ edges + triangle,
               control = control.ergm(MCMC.runtime.traceplot = TRUE))
```

**Comment by krivit** [comment]
This is working as intended. Burn-in is never stored, and what the `simulate()` call is being asked to do here is to run `control$MCMC.burnin` iterations forward, then return the final network. Therefore, there is nothing to plot.

**Comment by komatsuna4747** [comment]
@krivit 
Thank you for your comment, and now it's clear. Then how could we check if a simulation is converging, especially when we start a simulation from a seed network without any edges?
