### ISSUE TITLE
In terms that take the levels2 argument, allow a character or factor matrix to specify the grouping among the levels.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#223]
I ran into this while working on some complex mixing matrices. Suppose, for example, that we have an undirected network with a nodal attribute `x` with three levels encoded 1, 2, and 3.

We want to specify a model with one parameter that controls homophilous ties, one that controls ties between 1 and 2, and one that controls all non-homophilous ties of 3. It would be convenient to be able to specify a matrix of the form, e.g.,
```r
M <- matrix(c("A","B","C",
               NA,"A","C",
               NA, NA,"A"), 3, 3, byrow=TRUE)
```

then `nodemix("x", levels2=M)` would add 3 elements to the statistic, e.g., `nodemix.x.A`, `nodemix.x.B`, and `nodemix.x.C`, counting the ties in the respective combinations of cells.

This particular case can, of course, be accomplished by a combination of `nodematch("x") + nodemix("x", levels2=2) + nodemix(~(x==3), levels2=2)` (or the use of the `Sum()` operator), but that strikes me as cumbersome.

@martinamorris , @sgoodreau , @smjenness , would something like this be generally useful?

**Edit:** To complete the specification, `NA` means to exclude the level and I would define `""` as model that cell individually with default name. Similarly for the `mm()` term, though the matrix may be rectangular there.

**Edit 2:** Grouped statistics (i.e., those from from labelled cells) should be sorted by label. Ungrouped statistics should be labelled as they would be by default and appended to the grouped, without changing their order from the default.

**Comment by martinamorris** [comment]
It would be useful, and the `nodemix` term is the natural home for it.  Supplying a design matrix like this is something that I used to do in the original glm packages back in the 90's...

**Comment by krivit** [comment]
``` r
library(ergm)
data(faux.mesa.high)

# Reference statistic:
summary(faux.mesa.high ~ absdiffcat("Grade"))
#> absdiff.Grade.1 absdiff.Grade.2 absdiff.Grade.3 absdiff.Grade.4 absdiff.Grade.5 
#>              15              15               7               2               1

# Reimplementation using the proposed interface:
M <- matrix(NA, 6, 6)
M[] <- letters[c(abs(row(M)-col(M)))+1]
M[lower.tri(M,TRUE)] <- NA
M
#>      [,1] [,2] [,3] [,4] [,5] [,6]
#> [1,] NA   "b"  "c"  "d"  "e"  "f" 
#> [2,] NA   NA   "b"  "c"  "d"  "e" 
#> [3,] NA   NA   NA   "b"  "c"  "d" 
#> [4,] NA   NA   NA   NA   "b"  "c" 
#> [5,] NA   NA   NA   NA   NA   "b" 
#> [6,] NA   NA   NA   NA   NA   NA

## Running (currently doesn't run):
# summary(faux.mesa.high~nodemix("Grade", levels2=M))

## Expected output:
# absdiff.Grade.b absdiff.Grade.c absdiff.Grade.d absdiff.Grade.e absdiff.Grade.f 
#              15              15               7               2               1 
```
<sup>Created on 2021-07-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

@joycecheng, here's a test case.

**Comment by krivit** [comment]
Secondly, the test doesn't test that labelled terms are handled correctly. At the moment, the reference case doesn't run correctly because of a regression, but here is the code:

``` r
# This tests that the "" cells are ungrouped, tagged by the default label, and positioned consistently.
library(ergm)
library(testthat)
data(faux.mesa.high)

M <- matrix(NA, 6, 6)
M[] <- letters[c(abs(row(M)-col(M)))+1]
M[lower.tri(M,TRUE)] <- NA

# Now, set them to "":
M[1,2] <- M[2,3] <- M[3,4] <- M[1,6] <- ""
M

## Running (currently doesn't work and may even cause segfaults):
(test <- summary(faux.mesa.high~nodemix("Grade", levels2=M)))

## Expected output constructed as follows;
M[1,2] <- M[2,3] <- M[3,4] <- M[1,6] <- NA
grouped <- summary(faux.mesa.high~nodemix("Grade", levels2=M))
M <- matrix(FALSE, 6,6)
M[1,2] <- M[2,3] <- M[3,4] <- M[1,6] <- TRUE
ungrouped <- summary(faux.mesa.high~nodemix("Grade", levels2=M))
(ref <- c(grouped, ungrouped)) # Expected result

expect_equal(test, ref)
```
