### ISSUE TITLE
Names appear to be lost for formula nodecov

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#225]
``` r
library(ergm)
# [...]
data(faux.mesa.high)
coef(ergm(faux.mesa.high ~ edges + nodecov(~poly(Grade, 2))))
# [...]
#>     edges nodecov.1 nodecov.2 
#> -4.662459 -1.207241  2.512615
```
<sup>Created on 2021-02-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The coefficient name vector should be along the lines of `c("edges", "nodecov.poly(Grade,2).1", "nodecov.poly(Grade,2).2")`.

**Comment by mbojan** [comment]
For `statnet/ergm#220` I would like to use the "stem" such as `nodecov.poly(Grade,2)`. Can we isolate that somehow such that sth like `term_label()` would return `"nodecov.poly(Grade,2)"` and `param_label()` a vector `"nodecov.poly(Grade,2).1", "nodecov.poly(Grade,2).2"`?

**Comment by krivit** [comment]
One option is to have the term also output a list of unjoined vectors, e.g., `coef.comps = list(c("nodecov","poly(Grade,2)","1"),c("nodecov","poly(Grade,2)","2"))`.

**Comment by mbojan** [comment]
Would that have to be produced within `ergm_model()` or inside each `InitErgmTerm.*()` (😨)? 

Another option is to factor it out and write each term- and parameter-labeller as a function of the saved call that we added recently that will add them after the terms are initialized. Is that viable?

**Comment by mbojan** [comment]
I am thinking along:

```
cl <- str2lang("nodecov(~poly(Grade, 2))")
> (term_name <- cl[[1]])
nodecov
> (term_label <- deparse(cl))
[1] "nodecov(~poly(Grade, 2))"
```

although there is no clear way of getting param names without evaluating the expression inside the term, but that happens during the initialization, right?

**Comment by mbojan** [comment]
> 
> 
> One option is to have the term also output a list of unjoined vectors, e.g., `coef.comps = list(c("nodecov","poly(Grade,2)","1"),c("nodecov","poly(Grade,2)","2"))`.

One downside I see with such design is that the term labeller code would have to scan how long the vectors are, whether second element is always the same etc., so essentially partly reverse-engineer the very code that produces it, or am I missing something?

**Comment by krivit** [comment]
It would have to be written inside each term. I guess I am not 100% sure what you are trying to accomplish here.
