### ISSUE TITLE
predict method output working as intended? conditional=TRUE vs. conditional=FALSE

### ISSUE THREAD

**Issue by drh20drh20** [statnet/ergm#226]
Possibly this is fine, but noticed the differences in format between the two outputs below so checking whether it's as intended.

```r
data(g4)
set.seed(123)
SimpleERGM <- ergm(g4 ~ edges)
## Starting maximum pseudolikelihood estimation (MPLE):
## Evaluating the predictor and response matrix.
## Maximizing the pseudolikelihood.
## Finished MPLE.
## Stopping at the initial estimate.
## Evaluating log-likelihood at the estimate. 
predict(SimpleERGM, conditional = TRUE, output = "matrix")
##           [,1]      [,2]      [,3]      [,4]
## [1,] 0.0000000 0.4166667 0.4166667 0.4166667
## [2,] 0.4166667 0.0000000 0.4166667 0.4166667
## [3,] 0.4166667 0.4166667 0.0000000 0.4166667
## [4,] 0.4166667 0.4166667 0.4166667 0.0000000
predict(SimpleERGM, conditional = FALSE, output = "matrix", nsim = 1000)
##      V1   V2   V3   V4
## V1 0.00 0.40 0.42 0.41
## V2 0.47 0.00 0.39 0.45
## V3 0.38 0.42 0.00 0.40
## V4 0.42 0.40 0.55 0.00
```

**Comment by mbojan** [comment]
Thanks @drh20drh20 . I think that's an unintended side-effect of `apply()`. I guess I'll drop the row/colnames from the result or perhaps set them to `vertex.names`.

**Comment by mbojan** [comment]
Hmm, in the unconditional case the row/colnames of the matrix are in fact the vertex names of the `g4` network. I guess this is what we want in general, namely:

- matrix output has row/colnames set to `vertex.names` of the network used on LHS of the model formula
- data frame output has numeric vertex IDs in the `from` and `to` columns.

I will fix the conditional case's matrix output to have the row/colnames as well.

**Comment by mbojan** [comment]
@krivit , can we please limit force-pushing to absolute minimum? I fetched and now have a total mess in my working copy.

**Comment by krivit** [comment]
@mbojan , fair enough. In this case, I merged into `master` a few minutes after the force-push, so there wasn't really anything in that branch that would need to be fetched. These days, I try to limit force-pushing to development, PR, and other disposable branches.

**Comment by krivit** [comment]
Looks like the Rmpi on Windows thing has fixed itself.

**Comment by drh20drh20** [comment]
@mbojan sorry I couldn't verify this prior to it being merged; the other day I could not find the branch you created using RStudio and don't know why.  But I can verify post-merge that your fix works, FWIW.

**Comment by mbojan** [comment]
Thanks @drh20drh20 .
