### ISSUE TITLE
Use the same calling convetion for constraints, proposals, etc. as for terms?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#230]
At the moment, the calling convention for terms is `Init<WT?>ErgmTerm.<NAME> <- function(nw, arglist, ...)`, where `nw` is the network on the LHS of the formula (or `basis`),  `...` are global term options passed through the `term.options=` control parameters, and `arglist` is an `alist()` with the arguments (technically, promises) to the term. Then, `check.ErgmTerm()` is used to validate the arguments.

For constraints, it's `InitErgmConstraints.<NAME> <- function(lhs.nw, <ARG1>, <ARG2>, ...)`, where `lhs.nw` is the LHS network,  `<ARG#>` are argument names, and `...` are generally unused and trigger an error if present.

For references, it's the same as for constraints: `InitErgmReference.<NAME> <- function(lhs.nw, <ARG1>, <ARG2>, ...)`.

For proposals, it's `Init<WT?>ErgmProposal.<NAME> <- function(arguments, nw)`, where `nw` is the LHS network, and `arguments` is a list combining control parameters, sublist `constraints`, and the `reference` formula.

It seems to me that these should be harmonised. Since the ErgmTerm API is the only one we've published, rejiggering them all to use that form seems like the best approach, and they can use `check.ErgmTerm()` for argument checking.

It should be possible to make this completely backwards compatible, by having the caller check the argument names of the function and shift them around accordingly, after firing a deprecation warning.

Do we want to do this?

**Comment by krivit** [comment]
@chad-klumb , @martinamorris , it occurs to me that this could be used to allow Sampling, CD, and SAN to "inform" the proposal initialiser which mode it's in.

**Comment by martinamorris** [comment]
@krivit i would need a bit of an idiot's guide here to understand and respond.

**Comment by krivit** [comment]
> @krivit i would need a bit of an idiot's guide here to understand and respond.

It's basically `term.options` but for proposals, constraints, etc..
