### ISSUE TITLE
Port the MPLE C code to use khash.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#246]
Right now, we use a hash table of prespecified size (`maxNumDyadTypes`). Before the transition to the `.Call()` API, our return vector sizes had to be prespecified, so this was a necessary limitation, but that is no longer a limitation.

It is likely to be faster, and it would grow automatically as needed.

**Comment by krivit** [comment]
@chad-klumb , @martinamorris , in particular, I removed the maximum dyad types setting (because `khash` tables can grow dynamically), but I am concerned about excess memory use under some scenarios.

**Comment by chad-klumb** [comment]
Would it make sense to leave maximum number of dyad types in (possibly defaulting to `+Inf`) so the user can cap the memory usage in cases where they need to?

I can try to do some benchmarking with the cohab model over the weekend but it may not pertain directly to memory limitations.

**Comment by krivit** [comment]
It should be possible.

**Comment by krivit** [comment]
It might be worth testing on that, though it's not that urgent.

On further thought, regarding maximum dyad types, if the user's application doesn't require the full predictor matrix, then they can just use case-control likelihood that is invoked when the number of dyads exceeds the maximum dyads setting; but if the application does require it, it would be better for it to stop with an out-of-memory error than to return an incorrect result.

That said, if there is an out-of-memory error, I am not sure the current implementation will free all the memory. Perhaps the code should be modified to do that. (`R_alloc()` seems like the thing to use here.)

**Comment by krivit** [comment]
I think this is a net improvement, so I'll go ahead and merge this. We can sort out the downstream optimisations later.
