### ISSUE TITLE
nodefactor ergm term argument undefined in docs

### ISSUE THREAD

**Issue by smjenness** [statnet/ergm#25]
As of `erm3.9.4` `nodefactor` now has a new argument `labels`, but as far as I can see this is never defined in the docs:

<img width="958" alt="screen shot 2018-09-25 at 11 15 53 am" src="https://user-images.githubusercontent.com/2521570/46024289-7555be80-c0b4-11e8-9c07-99b8afaed401.png">

**Comment by krivit** [comment]
It's documented near the top of the file. It lets you override the set and the ordering of levels of the categorical factor.
