### ISSUE TITLE
Harmonise the name of the "hint" in the c_ and u_ functions.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#250]
A c_ and a u_ function in the new API currently gets the following arguments:
* `Vertex tail` -- tail of focus dyad
* `Vertex head` -- head of focus dyad
* `double weight` (valued only) -- new weight for the focus dyad
* `(Wt)ModelTerm *mtp` -- model term
* `(Wt)Network *nwp` -- network state (pre-change)
* `Rboolean edgeflag` (binary) / `double edgeweight` (valued) -- presence/weight of the focus dyad pre-change (i.e., `nwp[tail,head]`)

For consistency, it would be helpful to have the last argument---the "hint" about the current presence indicator / weight---had the same argument name. There has been some discussion, which was tabled until the code was merged, so the time is now to make the change. Some possible replacements for `edgeflag`/`edgeweight`:

* edgestatus
* edgestate
* edgeval
* edgehint

Any other ideas or preferences?  @mbojan @drh20drh20 @chad-klumb @handcock @sgoodreau @CarterButts

**Comment by krivit** [comment]
This follows up from https://github.com/statnet/ergm-private/issues/261 .

**Comment by krivit** [comment]
What about `edgenow`? It's shorter than status...

**Comment by krivit** [comment]
`edgestate` is another slightly shorter option.

**Comment by martinamorris** [comment]
that seems like a good choice

**Comment by krivit** [comment]
It's trivial to change (since it's a search-and-replace of a unique string), so I'll go with it for now.

**Comment by krivit** [comment]
@drh20drh20  suggested `edgeval`.

**Comment by krivit** [comment]
In the end, I am going with `edgestate`: `edgeval` is shorter, but it feels ambiguous in that it's not necessarily the *current* value; `edgehint` is also shorter, but it's vague.

**Comment by krivit** [comment]
@smjenness , @ifellows , both `EpiModel` and `lolog` link to `ergm`. If those packages don't define any new-style (`c_` and `u_`) statistics, they should not be affected---and as far as I can tell, they don't---but I want to flag this to avert surprises.
