### ISSUE TITLE
Duplicated vignette entry

### ISSUE THREAD

**Issue by jeroen** [statnet/ergm#257]
Any guess what might cause this? When running R CMD build on your master branch we get:

```
* creating vignettes ... ERROR
duplicated vignette title:
  ‘API for ergm Terms’
...

--- finished re-building ‘ergm.Rnw’

Error: Duplicate vignette titles.
  Ensure that the %\VignetteIndexEntry lines in the vignette sources
  correspond to the vignette titles.
Execution halted
```

See https://statnet.r-universe.dev/ui#builds

**Comment by krivit** [comment]
Indeed, thanks! Actually, I had no idea there even was that r-universe thing.

**Comment by jeroen** [comment]
If you enable the r-universe app for the statnet github organization, you even get a green checkmark https://github.com/apps/r-universe/installations/new

**Comment by krivit** [comment]
A green checkmark?
