### ISSUE TITLE
The main ERGM vignette: should egocentric data be in it?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#26]
@martinamorris , @sgoodreau , it's there because it was a part of a workshop. However, `ergm.ego` is far more user-friendly about it, and makes checks take significantly longer, so is it worth moving there?

**Comment by martinamorris** [comment]
> @martinamorris , @sgoodreau , it's there because it was a part of a workshop. However, ergm.ego is far more
> user-friendly about it, and makes checks take significantly longer, so is it worth moving there?

absolutely.  we've modified the workshops long ago.  i never look at (or 
think about the vignette) and that is definitely overdue for an overhaul.

for now, feel free to just replace the current egocentric material with 
this from the ergm workshop:

https://statnet.github.io/Workshops/ergm_tutorial.html#7_working_with_egocentrically_sampled_network_data
