### ISSUE TITLE
SAN.invcov argument to control.san() is not actually applied in san

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#260]
Currently `control.san` advertises a `SAN.invcov` argument that is supposed to allow the user to set the initial weights matrix:

https://github.com/statnet/ergm/blob/15a950ac188365a90e1716a85f2e757b0cc88fc3/R/control.san.R#L30-L34

Inspection of the `san` R code suggests this argument is never actually used.  More specifically, the initial weights matrix is set here

https://github.com/statnet/ergm/blob/15a950ac188365a90e1716a85f2e757b0cc88fc3/R/ergm.san.R#L304

without regard to whether or not `SAN.invcov` was specified in the control argument.

The default initial weights may be suboptimal in various situations so it would probably be best if we actually let the user set an alternative.

**Comment by krivit** [comment]
Should be fixed. Do you by any chance have a small example we can use as a unit test?

**Comment by chad-klumb** [comment]
Not clear it's working, since the control argument is called `SAN.invcov`, while the new code 

https://github.com/statnet/ergm/blob/05c0d1814ec944fc09192c64d1e21bacf7487d95/R/ergm.san.R#L304-L307

references only `invcov`.

**Comment by krivit** [comment]
Oops... Hence the need for the test case.

**Comment by krivit** [comment]
@chad-klumb , can you please confirm if this fixes the issue?

**Comment by chad-klumb** [comment]
Appears to work.  Ran this as a test

```
require(ergm)

set.seed(0)

default <- double(10000)
custom <- double(10000)

for(i in seq_len(10000)) {
  print(i)
  
  nw <- network.initialize(30, dir = FALSE)
  nw %v% "race" <- rep(c("A", "B", "C"), length.out = 30)
  nw %v% "attr" <- 500000 + (runif(30) - 1/2)*10000

  target_stats <- c(20, 20, 10, 20, 10, 20, 100000000)

  rv <- san(nw ~ nodemix("race", levels2 = NULL) + nodecov("attr"), target.stats = target_stats, control = list(SAN.maxit = 1, SAN.nsteps = 2000))

  default[i] <- max(abs((summary(rv ~ nodemix("race", levels2 = NULL) + nodecov("attr")) - target_stats)/target_stats))

  rv <- san(nw ~ nodemix("race", levels2 = NULL) + nodecov("attr"), target.stats = target_stats, control = list(SAN.maxit = 1, SAN.nsteps = 2000, SAN.invcov = diag(1/target_stats**2)/sum(1/target_stats**2)))

  custom[i] <- max(abs((summary(rv ~ nodemix("race", levels2 = NULL) + nodecov("attr")) - target_stats)/target_stats))
}
```

In the 10000 runs, the minimum maximum error for the default weights was 0.3, while the maximum maximum error for the custom weights was 0.004434304, so a test could be performed by checking against, say, 0.1.

**Comment by krivit** [comment]
Is there a way to shorten this test? It took more than 10 minutes on my PC.

What about something like this?

1. Set up a self-contradicting SAN call (e.g., `~edges + edges`, `target.stats = c(0, 10)`)
2. Set the maximum top-level iterations to 1, burn-in to something modest.
3. Make two calls, one with `SAN.invcov = diag(c(100000,1))`, the other with `SAN.invcov = diag(c(1,100000))`.
4. Confirm that the correct objective is being prioritised.

On further thought, perhaps the code that enforces that SAN.invcov must be SPD should instead enforce that it's symmetric non-negative definite, so that `SAN.invcov = diag(c(1,0))` is legal---if the user, for example, wants to completely ignore a particular statistic during the first iteration.

**Comment by chad-klumb** [comment]
The test would run only one iteration, not all 10000.

**Comment by krivit** [comment]
E.g.,
```r
library(ergm)
nw <- network(10)
stopifnot(network.edgecount(san(nw~edges+edges, target.stats=c(0,20), control=control.san(SAN.invcov=diag(c(1,10000)),SAN.maxit=1)))==20)
stopifnot(network.edgecount(san(nw~edges+edges, target.stats=c(0,20), control=control.san(SAN.invcov=diag(c(10000,1)),SAN.maxit=1)))==0)
```
