### ISSUE TITLE
Rename Undir() operator to Sym()/Symm()?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#263]
Raised by @CarterButts, the latter is a more common name.

**Comment by krivit** [comment]
One "m" or two? @CarterButts , @drh20drh20 , @martinamorris, @chad-klumb , @mbojan

**Comment by martinamorris** [comment]
Is there any reason not to use `symmetrize()`?

**Comment by krivit** [comment]
@martinamorris , brevity, mostly.

**Comment by drh20drh20** [comment]
I cast a lukewarm vote for `Symm` to maintain brevity while sympathetic (sorry, couldn't resist) to potential ambiguity around other words starting with sym.

**Comment by sgoodreau** [comment]
Agree with Dave. That said I'm a fan of slightly longer commands that are unambiguous, so would not be opposed to Symmetrize

**Comment by martinamorris** [comment]
If this function is mostly behind the scenes, or used with command completion, I don't see much of an argument for brevity over consistency with SNA.  I'd still favor Symmetrize()

**Comment by krivit** [comment]
@martinamorris , command completion doesn't work for ERGM terms, and I don't even know where to start in implementing it. I like `Symm()` or `Symmetrize()`.

**Comment by martinamorris** [comment]
i'd favor `symmetrize()` then, for consistency with `sna`.  is there a reason it needs to be capitalized?

**Comment by krivit** [comment]
It's an operator term, so it should be capitalised.
