### ISSUE TITLE
Add Prod() operator to match Sum() et al.

### ISSUE THREAD

**Issue by CarterButts** [statnet/ergm#267]
Per discussion on the ergm 4.0 paper, it would be nice to have the new operator syntax support a `Prod` operator to match the `Sum` operator.  Functionally, this should take a set of terms and construct a term that is equal to their product.  (For funsies, could could also support applying a power transform to obtain a geometric mean.)  This would allow users to easily implement terms to preserve the expected product-moment between two (or more) statistics, among other exotic effects (e.g., specifying polynomials in one or more base statistics).  From a network-level perspective, these are also the natural way of describing interaction effects.

**Comment by krivit** [comment]
Assuming that all statistics in question are positive, one quick-and-dirty solution is to instead implement `Log()` and `Exp()` operators and then implement `Prod()` as `Exp(~Sum("sum"~Log(~...)))`, where `...` are the terms whose product is to be taken.

**Comment by krivit** [comment]
On further thought, the `Log()` operator might be dangerous to use, since it can produce infinite results. It might be possible to "insulate" it inside an `Exp()` operator, however.

**Comment by krivit** [comment]
@CarterButts , what do you think, for the time being? I don't know how quickly the numeric errors will add up when MCMC sampling. It did expose a bug in the core code, so either way it wasn't a complete waste.

**Comment by CarterButts** [comment]
The problem with the log sum issue, as you observe, is that not every statistic is non-negative.  But it would be also be possible to start with the easy-to-implement limited option and extend it later if it turns out to be useful (it wouldn't break user code), so it's probably pretty harmless in that respect.  Not sure about the numerical question - it can be hard to know, IMHO, until one sees what happens in practice.....
