### ISSUE TITLE
Possible bug in fix.curved handling of dgwesp term

### ISSUE THREAD

**Issue by jrstew** [statnet/ergm#27]
I noticed that the fix.curved function does not behave as expected for the dgwesp terms. 

I have a reproducible example: 

library(ergm)
net <- network.initialize(10)
form <- net ~ dgwesp(fixed = FALSE)

#### Try fixing dgwesp
fix.curved(form, c(0.5, 0.5))$formula 

Returns: 
net ~ dgwesp(fixed = FALSE)

where fixed = FALSE, but should be fixed = TRUE

#### Comparing to GWESP: 
form <- net ~ gwesp(fixed = FALSE)
fix.curved(form, c(0.5, 0.5))$formula 

Returns:
net ~ gwesp(fixed = TRUE, decay = 0.5)

where fixed = TRUE, as would be expected.

**Comment by krivit** [comment]
Thanks for the report. Unfortunately, each term needs to have its "recipe" for fixing specified manually, and the new terms got left out.

**Comment by jrstew** [comment]
Thank you so much for the fast fix!
