### ISSUE TITLE
scode vertex attribute undocumented for faux.dixon.high

### ISSUE THREAD

**Issue by drh20drh20** [statnet/ergm#271]
Furthermore, `faux.dixon.high %v% "scode"` has the same value for all nodes.  Should we document it or remove it?

**Comment by martinamorris** [comment]
The other directed network has the same property (`faux.desert.high`).

@sestansfield constructed these datasets.  She doesn't have access to this repo, so I've emailed her with this question.

**Comment by mbojan** [comment]
I moved them already to https://github.com/statnet/statnet.data. If there is a consensus to have it on CRAN by the next release (and other statnet packages updated accordingly) perhaps we should address such issues there?

**Comment by martinamorris** [comment]
@sestansfield did not find any useful info in her old files (these were constructed in 2014).  So I would say yes, let's delete the `scode` attribute for both `faux.dixon` and `faux.desert`.  @mbojan did you want to take responsibility for that?

**Comment by drh20drh20** [comment]
Thanks for looking into it, @martinamorris .  I'd be willing to make the changes in both `ergm` and `statnet.data`.  @mbojan I assume you have no objections if I do it?

**Comment by mbojan** [comment]
I guess then we need to 

1. Fix the objects in `statnet.data`
2. Update `ergm` and other packages by 
    + deleting respective data objects and 
    + add `statnet.data` as Imports
    + update examples/tests to use data from `statnet.data`

I'll be happy to take charge @martinamorris and welcome any help with that @drh20drh20 .

**Comment by krivit** [comment]
Has there been any movement on this? I need to start putting together the release for CRAN.

**Comment by martinamorris** [comment]
Yes -- I must have replied by email instead.

Delete the scode attribute.

**Comment by krivit** [comment]
@drh20drh20 , @mbojan , could you please do what @martinamorris mentioned? I'm trying to fix other stuff before the release deadline.

**Comment by mbojan** [comment]
@krivit I will fix this issue in `ergm`. As for the rest, I'm afraid I will not be able to make all the data-related and `statnet.data`-related updates to the packages before Sunbelt/NetSci... Soon after though.

**Comment by mbojan** [comment]
@krivit @martinamorris @sgoodreau , for future release of `statnet.data` I already dropped `faux.mesa.high.withnumericattributes` and `faux.magnolia.high.withnumericattributes` (as per https://github.com/statnet/statnet.data/issues/3). Can I remove them from `ergm` at this moment too? An extra user inconvenience with them is that the actual objects loaded are identical with `faux.magnolia.high` etc....

**Comment by krivit** [comment]
Yes, please remove it from `ergm` as soon as possible.

**Comment by mbojan** [comment]
On it as we write.

**Comment by mbojan** [comment]
@krivit where should I merge it into? `master` or `4.0`?

**Comment by krivit** [comment]
`master`

**Comment by mbojan** [comment]
Closed with ed74d81c

**Comment by krivit** [comment]
@mbojan , generally, fixes should go to `master`, and I'll propagate them to `4.0` in due time.

**Comment by drh20drh20** [comment]
@mbojan I'm just noticing your comment about `statnet.data`.  So @krivit if I wanted to get the `cohab` dataset into the package then I should add it to `ergm` ASAP, correct?

**Comment by krivit** [comment]
@drh20drh20 , yes. The planned release date for ERGM is 10 June: https://github.com/orgs/statnet/projects .

**Comment by mbojan** [comment]
@drh20drh20 yes

**Comment by krivit** [comment]
@drh20drh20 , to clarify, is `cohab` going into `ergm` or `statnet.data`? It's been a while.

**Comment by martinamorris** [comment]
@krivit @drh20drh20 it should probably go into `ergm`, unless `statnet.data` is being released now.  it's a key dataset for the `ergm 4.0` paper, so should be available when `ergm` gets loaded.

**Comment by drh20drh20** [comment]
I'll put it in `ergm` or, rather, submit a pull request to `ergm`.  I'll need a few hours to finalize this due to meetings but I can have it ready today.  (@krivit is the deadline June 10 AEST or some other time zone?)

**Comment by drh20drh20** [comment]
Of course, we can also add `cohab` to `statnet.data` but it sounds like this is a "both" situation given the imminent `ergm` release.

**Comment by krivit** [comment]
I'm going to assume it's June 10 Seattle time.
