### ISSUE TITLE
Put $coef back into ergm?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#277]
After fixing #158 and replacing `$coef` with `$coefficients`, it looks like, we've been teaching people to use `$coef` to obtain parameter estimates from an `ergm` object. (The correct way is, of course, to use `coef()` or `coefficients()`.)

It might be a good idea to put it back, in case people rely on it in their existing code and habits.

We could do a soft-deprecation, by overriding `$.ergm` and having it issue a warning when someone tries to access `$coef`.

**Comment by martinamorris** [comment]
soft deprecation seems appropriate.  is this a specific case of the more general requests that users move away from direct access to accessor functions?
