### ISSUE TITLE
Convert ergm-terms documentation to Roxygen?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#28]
At the moment, all the `ergm` terms are documented in one big file (`ergm-terms.Rd`) with a "standard" syntax for keywords. Porting them to Roxygen (somehow) would greatly simplify maintenance in the following ways:
* Documentation "source" could be placed next to the `InitErgmTerm` function definitions, for much better maintainability.
* Using `@template`, common bits of text (like meanings of arguments common among many terms) only need to be written and updated once.
* Markdown is less clunky than the `Rd` format.

AFAIK, `roxygen2` has an API for custom `@` tags and document types, and we could write them to generate automatically formatted `Rd` files. Some other things we might be able to do:
* Generate a help file for each term *and* a help file with all the terms and/or a term index. This would allow us to link to a specific term's help.
* `@seealso`-style cross-referencing for related terms.

Any thoughts?

**Comment by krivit** [comment]
Another possibility is to use the [dynamic pages mechanism](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Dynamic-pages), which could also be used to make `help("ergm-terms")` list *all* terms defined so far. E.g., something like this:

1. Each `InitErgmTerm.*()` function is to be able to define `attr` attributes that document it. For example,
    ```r
    InitErgmTerm.absdiff <- structure(
      function(nw, arglist, ..., version=packageVersion("ergm")) {
        ### Check the network and arguments to make sure they are appropriate.
        a <- check.ErgmTerm(nw, arglist, directed=NULL, bipartite=NULL,
                            varnames = c("attr","pow"),
                            vartypes = c(ERGM_VATTR_SPEC,"numeric"),
                            defaultvalues = list(NULL,1),
                            required = c(TRUE,FALSE))
        ### Process the arguments
        nodecov <- ergm_get_vattr(a$attr, nw, accept="numeric")
        covname <- attr(nodecov, "name")
        ### Construct the list to return
        list(name="absdiff",                                     #name: required
             coef.names = paste(paste("absdiff",if(a$pow!=1) a$pow else "",sep=""), covname, sep="."), #coef.names: required
             inputs = c(a$pow,nodecov),  # We need to include the nodal covariate for this term
             dependence = FALSE # So we don't use MCMC if not necessary
             )
      },
      args = alist(attr, pow=1),
      keywords = c("binary", "dyad-independent", "frequently-used", "directed", "undirected", "quantitative nodal attribute"),
      title = "Absolute difference",
      description = "The \\code{attr} argument specifies a quantitative attribute (see \\NodalAttr for details). This term adds one network statistic to the model equaling the sum of \\code{abs(attr[i]-attr[j])^pow} for all edges (i,j)  in the network.")
    ```
2. A helper function (e.g., `.gen_term_docs()`) scans through the namespaces of loaded packages and generates Rd code for their list, sorted and sectioned as needed based on the attributes.
3. The `ergm-terms.Rd` calls `\Sexpr[stage=render,results=rd]{.gen_term_docs()}`.

I see the following upsides and downsides relative to the Roxygen approach:

* Does not require learning the Roxygen extension API.
* Should be able to generate term documentation dynamically, with entries added as new packages are loaded.
    * Though it should be possible to generate aliases (i.e., so that `?absdiff` brings up the help for the terms), I suspect that that can only be done at the build or the installation stage, which means that those can't be dynamically updated.
* Does require writing raw Rd (rather than Markdown) code. (It may be worth seeing if Roxygen exports the function it uses to convert Markdown to Rd.)
* Less amenable to other preprocessing, such as being able to create a separate help file for each term, as opposed to a wall of text.
    * Code in `.gen_term_docs()` could be run before build as a poor man's Roxygen, however.

@martinamorris , @mbojan , @chad-klumb , @drh20drh20 , @sgoodreau , @CarterButts , @handcock , any thoughts?

**Comment by krivit** [comment]
For comparison, I imagine documentation for customised Roxygen would look something like this:
```r
#' @docType ergmTerm
#' @usage absdiff(attr, pow=1)
#' @title Absolute difference
#' @details The \code{attr} argument specifies a quantitative attribute (see \NodalAttr for details). This term adds one network statistic to the model equaling the sum of \code{abs(attr[i]-attr[j])^pow} for all edges (i,j)  in the network.
#' @keywords binary, dyad-independent, frequently-used, directed, undirected, quantitative nodal attribute
InitErgmTerm.absdiff <- function(nw, arglist, ..., version=packageVersion("ergm")) {
  ETC...
}
```

**Comment by mbojan** [comment]
I think I Iike Roxygen more than the idea from https://github.com/statnet/ergm/issues/28#issuecomment-770472370. I think we can use `@family` for all the tagging/grouping. What would we need the custom Roxygen API for?

Is the idea to still have all the terms documented on a single page, grouped somehow or each one having its own?

I'm not a big fan of the current setup with one big page because its cumbersome to scroll/search through.

**Comment by krivit** [comment]
Roxygen API is designed for documenting functions, and it wouldn't know what to do with `InitErgmTerm.*()` functions.

I am having trouble envisioning how to use Roxygen here without extensions. Can I ask you to prototype it for 2-3 terms (e.g., `edges` and `absdiff`) in a branch?

**Comment by mbojan** [comment]
Sure, I'll have a look.

**Comment by krivit** [comment]
I was thinking either one big page or both. (Alternatively, the one big page could be an index page with brief term descriptions linking to separate ones.)

**Comment by mbojan** [comment]
Or one big vignette and separate Rd files?

**Comment by martinamorris** [comment]
I like some version of both.  The one big page makes searching within page easy.

**Comment by krivit** [comment]
There is already an `ergm-term-crossRef.Rmd` vignette written by @skyebend that indexes the terms by parsing the `ergm-terms.Rd` file.

In any case, I am still not sure if one can use unmodified Roxygen to get this to work. In particular, `@family` doesn't create an index page. Rather, it cross-links all members of a given family with each other.

**Comment by mbojan** [comment]
> Pavel: I was thinking either one big page or both. (Alternatively, the one big page could be an index page with brief term descriptions linking to separate ones.)
> 
> Martina: I like some version of both. The one big page makes searching within page easy.

The question is if user asks `?absdiff` what should open? At this moment one gets the "ergm-terms" page. We may keep the "ergm-terms" more or less as it is now but write documentation in Roxygen next to the `initErgmTerm.*()` functions. We won't need `@family` but I think the issue will be to ensure the alphabetic ordering of the terms in the Rd output. There is `@order` but I'm not sure it will work because we are not documenting real R objects and it seems it only accept numbers as a basis for sorting.

On the other hand if we want to have individual pages for the terms (`?absdiff` will open its own man page) I think it could mimic a man page of a standard R function with Usage etc. inserted as a `@section` with preformatted content (instead of `@usage` directly), use some Roxygen template and so on. I'm not yet sure what would be the best way to auto-build the "index page".

> There is already an `ergm-term-crossRef.Rmd` vignette written by @skyebend that indexes the terms by parsing the `ergm-terms.Rd` file.

Right! Forgot about that.

 
> In any case, I am still not sure if one can use unmodified Roxygen to get this to work. In particular, `@family` doesn't create an index page. Rather, it cross-links all members of a given family with each other.

I think I saw some code snippet somewhere with which one can dump the list of family members to Rd...

**Comment by krivit** [comment]
Here's what would work nicely:

* A page for each term. For some of them, we have to be careful with aliases, because, for example `hamming` and `edges` are both a term and a constraint, so currently a disambiguation page is used.
* An index page (updated dynamically) with:
    * All terms, in alphabetical order, indicating their package, keywords, and title.
    * For each package, a list of terms it exports.
    * For each keyword, a list of terms with that keyword.

In other words, much of what @skyebend 's vignette does, but integrated into the R's help system and updated as more packages are loaded.

If an acceptable formatting could be produced for each term using Roxygen, we can then piggyback on @skyebend 's code to scan through all the help pages with an appropriate title/keyword, parse their term information, and put them in the index using the Dynamic Pages method.

This would probably give us the best of both worlds: the term writer uses Roxygen and Rmarkdown, but the end-user sees a detailed and self-updating index.

Lastly, I think `@family` is less than ideal, because every term doc will have a list of all other terms in it, unless there is a way to suppress that behaviour.

**Comment by mbojan** [comment]
> Here's what would work nicely, I think:
> 
>     * A page for each term. For some of them, we have to be careful with aliases, because, for example `hamming` and `edges` are both a term and a constraint, so currently a disambiguation page is used.
> 
>     * An index page (updated dynamically) with:
>       
>       * All terms, in alphabetical order, indicating their package, keywords, and title.
>       * For each package, a list of terms it exports.
>       * For each keyword, a list of terms with that keyword.

That sounds good.

WRT `@family` I was thinking of using it for "tagging" groups of terms e.g. 

```
@family terms for directed networks
@family dyad-independent terms
```

and so on, and indeed one will get a list of terms by each "family".

I'm anyway looking into Roxygen API if there is any promising value for effort of creating our own tags.

**Comment by krivit** [comment]
> WRT `@family` I was thinking of using it for "tagging" groups of terms

Unfortunately, it'll do more than that. According to [the Roxygen2 docs](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html), `@family` will "cross-reference each function to every other function within the family". That means that every term will have a link to every other term in the package. `@concept` might work better.

**Comment by mbojan** [comment]
I used it in [`statnet.data`](https://github.com/statnet/statnet.data) to create families "directed networks", "undirected networks" and "bipartite networks". I think it is useful because you can see what other datasets of similar type are available and you can jump to their man page directly. If we make families for, say "dyad-independent terms", "node-covariate effects", "dyadic covariate effects" and so on (will have to carefully pick the family names though) one can open, say, `absdiff` and will have links to `nodematch`, `dyadcov` and so on. Isn't that useful? The `@concept` on the other hand AFAIK only allows for pages to be found by `help.search()`, doesn't it?

**Comment by krivit** [comment]
OK, I see how that could work. It might still make things a bit crowded, but as long as the crowing is out of the way, it shouldn't be too much of a problem.

**Comment by mbojan** [comment]
I'll try it out. Alternative ideas for the content and layout of the term page are welcome. Unfortunately `@family` gets somewhat special treatment in Roxygen so it might not be that straightforward (at least it isn't to me at this moment) to implement our own tag with similar features (e.g. collecting term names with particular keywords etc.).

**Comment by mbojan** [comment]
I gave it a shot at https://github.com/mbojan/ergm/tree/i28-roxyterms and the man page for `absdiff` looks like

![image](https://user-images.githubusercontent.com/636574/107826736-ac13f880-6d85-11eb-9869-72f41627e482.png)

so somewhat OK but not perfect, in particular:

- We can't use standard `@usage` because `absdiff()` is not an actual object so I mimic Usage as a normal `@section`. Unfortunately there is no way to position the sections manually and they will be after other sections (including Arguments)
- Perhaps we could implement a custom tag, say, `@termParam` for term arguments, such that the section is in the proper place (after Description and Usage)
- `@family` works although it will not be too useful if we use it for existing term "keywords"

I'm still not quite sure how do we want the output to look like. Perhaps we should backward-deduce the Roxygen from the Rd how would one document a term in its own Rd file. Ideas?

**Comment by krivit** [comment]
Thanks! Some thoughts:

1. What if we attach the doc to the `InitErgmTerm.*()` function rather than to `NULL`? Then, it'll accept `usage` and similar. Since it's not an exported function, I am pretty sure that `R CMD check` doesn't care.
2. We can use `@name` to give it a specialised name, e.g., `absdiff-ergmTerm`. It can then be selected with `ergmTerm?edges` as opposed to, say, `ergmConstraint?edges`.
3. The part after the dash can also be used by the eventual dynamic documentation code to grab help for all terms from all packages.
4. I am still not very fond of `@family`: it can't "see" members in other packages, and some of the bigger families will clutter things up.
5. Past behaviour stuff should probably be in a separate `@note` section, but that can wait.

**Comment by krivit** [comment]
Actually, it looks like it does care about item 1. Oh well...

**Comment by krivit** [comment]
There is a "cheat" we can use: if the usage statement is commented out, it's not checked. For example,
```r
#' @usage
#' # binary: absdiff(attr, pow=1)
#' # valued: absdiff(attr, pow=1, form="sum")
```
doesn't trigger the check.

**Comment by mbojan** [comment]
>     1. What if we attach the doc to the `InitErgmTerm.*()` function rather than to `NULL`? Then, it'll accept `usage` and similar. Since it's not an exported function, I am pretty sure that `R CMD check` doesn't care.

The cheat seems to work well and I think is acceptable.


>     2. We can use `@name` to give it a specialised name, e.g., `absdiff-ergmTerm`. It can then be selected with `ergmTerm?edges` as opposed to, say, `ergmConstraint?edges`.
> 
>     3. The part after the dash can also be used by the eventual dynamic documentation code to grab help for all terms from all packages.

Good idea of grouping into separate topic `ergmTerm`. I like that.


>     4. I am still not very fond of `@family`: it can't "see" members in other packages, and some of the bigger families will clutter things up.

Yeah. I think it would make sense if the are not so many "specialized" families (with not a lot of overlap).


>     5. Past behaviour stuff should probably be in a separate `@note` section, but that can wait.

Yep, I think so too.

**Comment by mbojan** [comment]
So now with

```
#' @name absdiff
#' @aliases absdiff-ergmTerm
#' @title Absolute difference
#' @description Absolute difference in nodal attribute. The `attr` argument
#'   specifies a quantitative attribute (see Specifying Vertex attributes and
#'   Levels (`?nodal_attributes`) for details). This term adds one network
#'   statistic to the model equaling the sum of `abs(attr[i]-attr[j])^pow` for
#'   all edges `(i,j)` in the network.
#'
#'   Note that ergm versions 3.9.4 and earlier used different arguments for this
#'   term. See the above section on versioning for invoking the old behavior.
#' 
#' @usage
#' # absdiff(attr, pow) # binary
#' # absdiff(attr, pow, form="sum") # valued
#' 
#' @param attr name of vertex attribute
#' @param pow power, default to 1
#' @param form character how to aggregate tie values in a valued ERGM
#' 
#' @family binary
#' @family dyad-independent
#' @family directed
#' @family undirected
#' @family nodal-quantitative
NULL
```

We're getting:

![image](https://user-images.githubusercontent.com/636574/107862010-0a0a1400-6e4a-11eb-9f6a-b05d7f2bb763.png)

**Comment by krivit** [comment]
@mbojan , can I ask you to move this to a branch off `statnet/ergm@master`? That way, I can push to it too.

**Comment by mbojan** [comment]
Sure. Done.

**Comment by krivit** [comment]
I've done more experimentation. It looks like this is a good way forward. I'll start putting together a "tender" to port the documentation and implement the indexer.

**Comment by krivit** [comment]
I've started a private Wiki document to discuss a possible tender here: https://github.com/statnet/ergm-private/wiki/Tender-for-roxygenising-and-indexing-term,-constraint,-etc.-documentation .

**Comment by CarterButts** [comment]
Notwithstanding the worry that we may end up creating extra dependencies via dragging another tool into the process (vanilla solutions endure better than Baroque ones), I like the ability to have a modularized solution that can follow the way the terms themselves are defined - that fits with our design concept, and so long as we can keep the core requirements from getting out of hand, could even make maintenance easier in the long run.  Also, our current approach is ungood.  So good work on this!  Glancing at the demo examples above, the one thing I don't immediately see that I would add is the ability to have an author and a citation for each term.  We definitely want this functionality, especially if we (1) want terms from ergm.userterms to be seamlessly integrated into the help system, and (2) want to be able to incorporate contributed terms.  But I presume it should be pretty straightforward....

**Comment by krivit** [comment]
@CarterButts , thanks for the feedback! The terms themselves only use Roxygen, and the indexing uses base R mechanisms and APIs, so there are no extra dependencies whatsoever.

Regarding the other aspects, the individual term doc mechanism piggybacks on the standard Roxygen and Rd mechanisms, so author, reference, and other arbitrary information can be incorporated as it would be for any other function.

**Comment by CarterButts** [comment]
Hmm, is Roxygen currently part of base R?  I can never keep track of the newfangled tricks you kids use these days.  When I started writing packages, you did it on stone tablets.....

But OK, this sounds good.  Perhaps it's a matter of setting up our term documentation "norms" to include those tags?

**Comment by krivit** [comment]
No, Roxygen is a package, but 1) it's not a dependency in the strict sense of the word, since it's run on R source code to generate documentation and `NAMESPACE`; and 2) we already use it everywhere, including `network`.

We can certainly include authorship and citation information in the examples. There will likely be required components and formatting that the indexing code will rely on, and the rest is up to the writer, as is the case with other function docs.

**Comment by CarterButts** [comment]
Well, the currently released branch of network does not depend on Roxygen, FWIW.  But otherwise, sounds good.

**Comment by krivit** [comment]
It depends on it in the sense that its (static) documentation is generated by Roxygen.

**Comment by CarterButts** [comment]
Fair.

**Comment by krivit** [comment]
By the way, here's what it looks like now:
![image](https://user-images.githubusercontent.com/15682462/107873891-de4e6300-6f09-11eb-8c04-1b95aeeb9b21.png)
I do think that we might want to have some dynamic handling for concepts, e.g., just link them to the dynamic index page.

**Comment by mbojan** [comment]
I think I'd use "edges" as `@name` and `edges-ergmTerm` in `@aliases`.

**Comment by mbojan** [comment]
So I guess once we settle on the Roxy-layout for a term, it would be nice to have a script that will re-write the existing term documentation?

**Comment by martinamorris** [comment]
This is looking really good :)

**Comment by krivit** [comment]
> I think I'd use "edges" as `@name` and "edges-ergmTerm" in `@aliases`.

My reasons for doing it that way:

* `edges` is not actually a proper R function.
* This is exactly how different documentation types are supposed to work in R's help system. 
* Topic `edges` shows up in other places, such as constraints. Even now, there is a disambiguation page.
* Having a topic name following a consistent and distinct pattern makes it much simpler, faster, and more reliable for the term indexer code to locate the documentation that needs to be parsed. (See [this implementation note](https://github.com/statnet/ergm-private/wiki/Tender-for-roxygenising-and-indexing-term,-constraint,-etc.-documentation).)

> So I guess once we settle on the Roxy-layout for a term, it would be nice to have a script that will re-write the existing term documentation?

I was going to see about hiring someone to do it manually (because there are nontrivial bits like extracting boiler plate code into templates, valued vs. binary terms, etc.---see [the tender draft](https://github.com/statnet/ergm-private/wiki/Tender-for-roxygenising-and-indexing-term,-constraint,-etc.-documentation) ), but if you can script it and have it do a good job, that would be great and would get this done far sooner.

In particular, if someone volunteers to do the term conversion (Item 1 in the [Specification](https://github.com/statnet/ergm-private/wiki/Tender-for-roxygenising-and-indexing-term,-constraint,-etc.-documentation#specification) and Steps 3-4 in the [Outline](https://github.com/statnet/ergm-private/wiki/Tender-for-roxygenising-and-indexing-term,-constraint,-etc.-documentation#outline-of-the-project)), I volunteer to implement the indexing code (Item 2 and Step 2).

**Comment by mbojan** [comment]
> > I think I'd use "edges" as `@name` and "edges-ergmTerm" in `@aliases`.
> 
> My reasons for doing it that way (...)

Good points.

> I was going to see about hiring someone to do it manually (because there are nontrivial bits like extracting boiler plate code into templates, valued vs. binary terms, etc.---see [the tender draft](https://github.com/statnet/ergm-private/wiki/Tender-for-roxygenising-and-indexing-term,-constraint,-etc.-documentation) ), but if you can script it and have it do a good job, that would be great and would get this done far sooner.

Sounds like a good idea. I think using Skye's code for parsing the Rd and then spitting the content out in a Roxygen form might save some of the editing but probably not the copy-pasting into proper places of the `InitErgmTerm` files.

**Comment by krivit** [comment]
> Sounds like a good idea. I think using Skye's code for parsing the Rd and then spitting the content out in a Roxygen form might save some of the editing but probably not the copy-pasting into proper places of the `InitErgmTerm` files.

For avoidance of doubt, are you volunteering to do the term conversion, or shall I proceed with the tender?

**Comment by mbojan** [comment]
> For avoidance of doubt, are you volunteering to do the term conversion, or shall I proceed with the tender?

I'm not :)

**Comment by krivit** [comment]
I've added in a background and goals section and updated the tender document with approximate counts of the number of entitites that would need to have their documentation ported. Can I ask everyone to whom this may be of interest (@mbojan , @CarterButts , @martinamorris , @drh20drh20 , @skyebend , @handcock ?) please take a look at it, make edits, and suggest if there is any other information I need to put in before using it to advertise the project?
