### ISSUE TITLE
typo in the ergm.gof function

### ISSUE THREAD

**Issue by Pachka** [statnet/ergm#283]
I think there may be a typo in the ergm.gof function.
lines 278, 279: 'odeg' and 'ideg' are reversed.
`idegree=list('odeg', 0:(n-1), function(x) summ_form(x, 'odegree', 0:(n-1))),`
`odegree=list('ideg', 0:(n-1), function(x) summ_form(x, 'idegree', 0:(n-1)))`

**Comment by krivit** [comment]
Thanks!
