### ISSUE TITLE
Make MacOS dmg and Windows zip package files built by Travis CI and make them available to end-users.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#29]
This will enable end-users who do not have MacOS and Windows development tools installed to use unreleased versions of packages. TravisCI + Windows + R doesn't work yet, but probably will soon enough.

The steps seem to be straightforward: https://docs.travis-ci.com/user/deployment/ .

In our case, we want the following behaviour:
* Deploy after every push, not just the tags or the releases.
* Group or label deployments by branch.
* Don't clobber past deployments.
* Deploy the `-private` branches to a space that is only accessible by those with access to those repositories.

If this is not feasible, a compromise is to deploy on tagging. This is suboptimal, but is much better than nothing.

**Comment by martinamorris** [comment]
update?

**Comment by krivit** [comment]
I haven't had time to work on this.

**Comment by mbojan** [comment]
Perhaps Travis could push to a Drat (http://dirk.eddelbuettel.com/code/drat.html) repo? Some time ago I made an attempt to have this for one of my own packages but failed. I'll report back with some HowTos.

**Comment by mbojan** [comment]
@martinamorris @krivit I have crunched the code and have a solution that:

1. Uses Travis to run R CMD check on linux
2. Uses Travis to run R CMD check on Windows (yay! no AppVeyor)
3. After successful check (platform-specific) deploys the build package (including Windows binary) to a drat repository
5. Drat repository can be hosted on GitHub
4. Drat repository can be used by anybody to simply `install.packages("package", repos="url://to/drat")`.

The drat CRAN-like repository is public so it makes sense only for the public repositories of Statnet packages (not `-private` ones).

I still need to test it with a package containing C code.

**Comment by mbojan** [comment]
What would be the best Statnet package to try this on first? Preferably something that `check`s rather quickly. `network`?

**Comment by mbojan** [comment]
Confronting with @krivit 's ideas:

> In our case, we want the following behaviour:
> 
>     * Deploy after every push, not just the tags or the releases.

No problem.

> 
>     * Group or label deployments by branch.

I'm not yet sure how to do this. How would one deploy such branch-specific packages on CRAN (which is essentially how drat works)? 

> 
>     * Don't clobber past deployments.

No problem. Past deployments/versions can be removed or archived (just like on CRAN).

>     * Deploy the `-private` branches to a space that is only accessible by those with access to those repositories.

We would have to have a CRAN-like repo which is private: a web-accessible space that requires a some sort of authentication that can be handled by R.

**Comment by krivit** [comment]
Thanks for looking into this, @mbojan ! 

> Uses Travis to run R CMD check on Windows (yay! no AppVeyor)

How? I thought that Travis CI + R + Windows was still under development?

> We would have to have a CRAN-like repo which is private: a web-accessible space that requires a some sort of authentication that can be handled by R.

Ideally, we'd make them accessible by whomever has access to the corresponding GitHub repo. Any thoughts for how we might do that? I guess if we tagged every commit and uploaded the package as a "release"...

**Comment by mbojan** [comment]
> > Uses Travis to run R CMD check on Windows (yay! no AppVeyor)
> 
> How? I thought that Travis CI + R + Windows was still under development?

There is no "nice" wrapper, but it can be done. I still need to jump the last hurdle with compiled code and Rtools.


> > We would have to have a CRAN-like repo which is private: a web-accessible space that requires a some sort of authentication that can be handled by R.
> 
> Ideally, we'd make them accessible by whomever has access to the corresponding GitHub repo. Any thoughts for how we might do that? I guess if we tagged every commit and uploaded the package as a "release"...

It should be possible to set up Travis to basically create a GitHub release out of a build package (tarball or zip). The question is, do we really  want to have it for every commit that passes the check successfully?

Whether pushing the builds to drat or as a GH release Travis needs a GH access token that allows him to access and push to private repositories.

Another difficulty might be making sure that all works as intended for public and private repos **simultaneously** and that we do not mess-up branch-specific setup files across the branches with some accidental/careless merges. This is my speculation at this moment.

**Comment by mbojan** [comment]
@krivit @martinamorris I have a prototype here https://github.com/mbojan/travispkg Let's experiment there (issues etc.). Primarily we should iron-out the desired logic. At this moment Travis runs the checks on different platforms in parallel and the deployment of the builds to drat is done only if the checks succeed on **all** the platforms. This seems desirable because otherwise if the check, say, fails on linux but succeeds on Windows there will be inconsistent versions in drat.

I still need to add the MacOS pipeline (should be straightforward). I have tested this w an R package with compiled code, but it turned out I have different problems there... I will add some dummy C code just for testing purposes.

All in all, I propose to get it to work as we want with this dummy package before we transplant it to any statnet package.

**Comment by krivit** [comment]
Obviated by move to GitHub actions and nightly.link.
