### ISSUE TITLE
Term conversion: Nonzero vs edges

### ISSUE THREAD

**Issue by joycecheng** [statnet/ergm#290]
In the old term index, edges is documented as a binary term and also alised to the valued term nonzero. Are edges and nonzero equivalent? I can

1) Combine the entries and alias all the terms to the same entry

2) Keep the edges page describing the binary term and the nonzero page describing the valued term and include the valued edges usage on the nonzero page but leave it out of the binary edges page.

**Comment by joycecheng** [comment]
#

**Comment by krivit** [comment]
Please combine.
