### ISSUE TITLE
Levels documentation

### ISSUE THREAD

**Issue by joycecheng** [statnet/ergm#299]
I was not able to figure out the meaning of the `levels` argument to many of the terms from the existing documentation. Left them as a TODO for now. Alternatively, levels explain is templated. If its function is already well understood, I can replace the TODOs with the template.

**Comment by krivit** [comment]
We might want to make a levels template that takes a template variable, which lets the writer specify what the argument does, then inserts the standard attribute UI links.

**Comment by joycecheng** [comment]
Converted them into templates but left the explanation as TODO
