### ISSUE TITLE
Robbins Monro algorithm to fit ERGM

### ISSUE THREAD

**Issue by yinfanuci** [statnet/ergm#30]
`wants <- c("stringr", "parallel", "data.table", "dplyr", "stringi", 
           "ggplot2", "tibble", "mixtools", "openxlsx", "magic", "invgamma", "stringr","statnet",
           "ergm", "brainGraph", "intergraph", "CINNA") 
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
lapply(wants, library, character.only=TRUE)

data("faux.mesa.high")
mesa_new_mod <- ergm(faux.mesa.high ~ edges + nodematch('Race',diff=F) 
                   + gwesp(0.25, fixed=TRUE), eval.loglik = TRUE,
                      control= control.ergm(main.method = "Robbins-Monro", MCMC.burnin = 1e6,
                                            MCMC.interval = 5e5))
`
![image](https://user-images.githubusercontent.com/36427582/47879408-bfca0980-dddd-11e8-91f1-a19adb1c35a9.png)

**Comment by krivit** [comment]
This appears to be fixed in `master`. Please try installing `master` versions of `network`, `statnet.common`, and `ergm`, and reopen if the problem persists.

**Comment by yinfanuci** [comment]
"master versions of network, statnet.common, and ergm" seems to be a jargon to me, could you please provide us the R code to accomplish such task? Thank you!

**Comment by yinfanuci** [comment]
Thanks! After I installed those new versions and loaded them into R, I encountered the following issue --

![image](https://user-images.githubusercontent.com/36427582/49323676-dabe9500-f4d3-11e8-9027-8d0ee6bdd713.png)

**Comment by yinfanuci** [comment]
Btw, Robbins-Monro algorithm is indeed working now! The only remaining issue at this stage is the error caused by "summary.formula" as above.

**Comment by krivit** [comment]
Please open a new issue and provide some code to reproduce it.
