### ISSUE TITLE
Operator terms that propagate offset()s themselves get their parameter names offset()ed.

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#301]
`offset` is in there twice

```
require(tergm)
nw <- network.initialize(10, directed = FALSE)
m <- ergm_model(nw ~ Form(~offset(edges)))
m$terms[[1]]$coef.names
## > m$terms[[1]]$coef.names
## [1] "offset(Form(offset(edges)))"
```

**Comment by krivit** [comment]
This is a general problem that applies to all operator terms.

The easiest solution is to "teach" `ergm_model` to wrap in `"offset()"` offsets produced by the `offset()` decorator (e.g., `nw~offset(edges)`) but not those produced by an `InitErgmTerm.*()` function returning `oulist$offset`.

This would cause the above to return `"Form(offset(edges))"`. But, is that what we want? Arguably, `"offset(Form(edges))"` makes it more clear that the parameter is fixed.

I am not 100% sure how to implement that. Maybe an optional argument to `ergm_model`, e.g., `submodel=FALSE`, which, if true, will suppress `offset()` wrapping.

Any thoughts?
@martinamorris , @sgoodreau , which is better from the end-user perspective?

**Comment by krivit** [comment]
@martinamorris , @sgoodreau , could we please get your thoughts on this? This would be good to fix before the 4.0 release.

**Comment by sgoodreau** [comment]
I'm not fully sure I understand the question, sorry.  Are you asking if `Form(offset(edges))` or `offset(Form(edges))` is better from a user perspective?  I think probably the latter, but if it's much harder to implement then I'm not sure it's that important.

But again, I feel way behind on all of the conversations re syntax here, so take my response with a grain of salt.

**Comment by martinamorris** [comment]
what SMG said.  as long as `offset` only there once, i think the main issue has been addressed.

**Comment by krivit** [comment]
OK, I think that's all of them.
