### ISSUE TITLE
Term names differing only by case

### ISSUE THREAD

**Issue by joycecheng** [statnet/ergm#302]
The operator `Sum` and the term `sum` have the generated man pages called Sum-ergmTerm.Rd and sum-ergmTerm.Rd which causes an error in the R check. One of them should be renamed if possible.

**Comment by krivit** [comment]
That could be a problem on Windows. If we change the `@name` for one of them (e.g., `Sum-operator-ergmTerm.Rd`), does that break anything?

Generally, we need to make sure that if two different packages export a help file with the same name, everything still works.
