### ISSUE TITLE
Change the ergm_dyad_hashmap.h's DyadSet/DyadMap*/THKey "API" to not require the hash to be passed?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#304]
Because of the way `khash` is designed, the hash function and the hash equality macros can access the environment of the accessor/modifier, which includes the hash struct itself, as `h`. This means that the somewhat clunky `THKey(khash, tail, head)` calls can be replaced with, e.g., `TH(tail, head)` and the directedness can be processed within the hash function. Is this worth doing?

@chad-klumb , what do you think?

**Comment by chad-klumb** [comment]
Sounds like a reasonable simplification.

**Comment by krivit** [comment]
Implemented.
