### ISSUE TITLE
Reformat NEWS by adding a "breaking changes" section in front of New Features?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#305]
Following some discussions around, https://github.com/statnet/statnet.common/discussions/19, right now, `ergm` prints "this may break your code" type of news on start up. Do we want to remove those in favour of a special section in the `NEWS` file?

@martinamorris, I think you were advocating for this. Does it sound like what you were suggesting?

**Comment by martinamorris** [comment]
Yes, add the section to the NEWS

I'd be in favor of a very short announcement on startup, given the scale of changes in this release.  But if the lack of breaking changes we saw in the revdep check is an accurate indicator of the backwards compatibility, I think we can deprecate it quickly.

Something like:

Please note this release of the statnet packages  is a major version update.  Breaking changes are listed in the NEWS file.

**Comment by krivit** [comment]
@martinamorris , what do you think of how it looks now? I am a bit reluctant to create a new section, but I've flagged some issues as particularly important.

**Comment by martinamorris** [comment]
I don't see a section for breaking changes -- wasn't that meant to be up top?

**Comment by krivit** [comment]
I wasn't sure I wanted one after all. I thought I would highlight the breaking changes in the other sections instead. As it is, there have been interface-changing changes before, so I am not sure whether it's worth having a separate section just this time.
