### ISSUE TITLE
ergm generates strange tergm-related warning

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#308]
```
> ergm.fit1 <- ergm(flobusiness ~ edges + gwesp(0, fixed = T))
For dynamic simulation in �tergm� you must pass �dynamic=TRUE�.  Attempting �ergm� simulation instead...
```

This is also the warning mentioned in the `tergm` repo [here](https://github.com/statnet/tergm/issues/25)

**Comment by krivit** [comment]
This is a `tergm` issue, because it overwrites the `simulate_formula()` method for `network`, and there is nothing `ergm` can do about it. The warning shows up even if the end-user makes the call.

**Comment by martinamorris** [comment]
I hear that, but *we can not have this behavior*.  It has to be fixed.  For users to get this warning everytime they simulate a simple `ergm` is just not acceptable.

**Comment by krivit** [comment]
It can't be fixed in `ergm`, so it has to be fixed in `tergm`, so I am closing this. We need to figure out whether or not the behaviour that I describe in https://github.com/statnet/tergm/issues/25#issuecomment-855231658 is what we want, and then implement it.
