### ISSUE TITLE
Release ergm 4.0 to CRAN

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#309]
# Checklist before submitting to CRAN

## Directions for use

1. Create an appropriately named issue (e.g., "Release package version *version*.").
1. Copy-paste this file into the issue text to provide the checklist functionality.
1. **After a commit directly pursuant to a checkbox item**, uncheck all checkboxes below it.
1. **After any other commit to `master` branch**, uncheck all boxes from the "`master` branch" section down.
1. **After any other commit to `*release*` branch**, uncheck boxes from the "Release branch" section down.
1. Close the issue after all boxes are checked.

## `master` branch

* [x] `DESCRIPTION`: Package's CRAN dependencies require a recent CRAN version.
* [x] `DESCRIPTION`: Package's dependencies that are a part of R core (`base`, `datasets`, `grDevices`, `methods`, `splines`, `stats4`, `tools`, `utils`, `compiler`, `graphics`, `grid`, `parallel`, `stats`, `  tcltk`, `translations`) do *not* specify a version.
* [x] `DESCRIPTION`: Package's dependencies that are usually shipped with R (`KernSmooth`, `Matrix`, `MASS`, `class`, `nnet`, `spatial`, `boot`, `cluster`, `codetools`, `foreign`, `lattice`, `mgcv`, `nlme`, `rpart`, `survival`) do *not* specify a version unless necessary.
* [x] All tickets associated with the release's milestone have been resolved.
* [x] The stubs file in `inst/include/` is up to date if needed.
* [x] Roxygen has been run on the package since last commit to code, documentation, or `DESCRIPTION`.
* [x] Relevant tutorials run satisfactorily.
* [x] `inst/NEWS.Rd`: file is up to date: none of the commits since the last commit to explicitly mention updating the `NEWS` file are newsworthy.
* [x] `LICENSE`: license refers to the correct package.
* [x] `LICENSE`: affiliations are up to date.
* [x] `LICENSE`: copyright year range is correct.
* [x] All files that should have them have copyright headers. Generally, it never hurts to rerun `addcopyheaders` to ensure this.
* [x] `R CMD check` passes with `ENABLE_statnet_TESTS=yes` environment variable *and* `--run-donttest`.
* [x] `rchk` static code analysis passes.
* [x] `R CMD check` outputs do not produce unwanted warnings, particularly deprecation warnings.
* [x] Reverse dependency checks pass unless breakage known.

## Release branch

* [x] Release branch has had the latest `master` merged into it. (`git checkout *release*; git merge master`)
* [x] `DESCRIPTION`: There are no `Remotes:` directives (unless releasing simultaneously).
* [x] `R-CMD-check.yaml`: `rcmdcheck()` is called with `error_on = "warning"`.
* [x] `DESCRIPTION`: Release branch's version number does not have commit number attached to it.
* [x] `DESCRIPTION`: Date is today.
* [x] `CITATION`: `update_CITATION` has been run after installing all the mentioned packages from the release branch.
* [x] All files in the release branch have been committed and pushed to GitHub.
* [x] `*pkg*.tar.gz`: the candidate submission file is from the latest version of the release branch.
* [x] `*pkg*.tar.gz`: `R CMD check` passes with `ENABLE_statnet_TESTS=yes` environment variable *and* `--run-donttest`.
* [x] `*pkg*.tar.gz`: `R CMD check` passes with `--as-cran` option without `WARNING`s.
* [x] `*pkg*.tar.gz`: `R CMD check` passes Win-Builder (https://win-builder.r-project.org).
* [x] `*pkg*.tar.gz`: `R CMD check` passes on the previous stable release (unless there is a good reason to require the latest R).

## After release

* [x] Release branch corresponding to the package on CRAN has been tagged with the exact CRAN version and pushed to GitHub.

**Comment by krivit** [comment]
a38fe82e44d45b4108af031a24a97e6eb861fafd sent to CRAN.

**Comment by krivit** [comment]
On CRAN.

**Comment by handcock** [comment]
Congratulations, Pavel and all those who contributed!

It was a massive undertaking and an impressive achievement.

Mark

**Comment by martinamorris** [comment]
Yay!!!!

On Mon, 14 Jun 2021, Pavel N. Krivitsky wrote:

> 
> On CRAN.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AB6QTYXY2TN6FRYU4FBN5RLTSYJDBA5CNFSM46EMTW3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5
> WW2ZLOORPWSZGOGNG633I.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

***@***.***
http://faculty.washington.edu/morrism/

**Comment by CarterButts** [comment]
Congrats!  This is a massive milestone, and a big accomplishment!

**Comment by krivit** [comment]
Thanks, everyone! (Two done, four to go.)
