### ISSUE TITLE
Go through the ergm.Rmd vignette and make sure it's accurate.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#312]
It runs all the way through, but we need to make sure that there is nothing in there that is now deprecated, inaccurate, or useless.

**Comment by krivit** [comment]
@martinamorris , I suspect that is is pretty close to the workshop, so can I ask you to please take a quick look?

**Comment by martinamorris** [comment]
yep :)

**Comment by martinamorris** [comment]
I've pushed an update in ba3a950.  Can't get it to knit to pdf, but it's probably a simple latex command that is screwed up.

**Comment by krivit** [comment]
@martinamorris , I've fixed the issues; you might want to backport them to the workshop. A few things:

* `eqnarray` should be changed to `align`, and you can't have those inside other maths (`$$`).
* `fit$coef` shouldn't be used and produces a warning. It should be `coef(fit)`. In general, we want to discourage people poking around `ergm` object's internals.
* Our classic example for gwesp isn't ideal, since it's still trial-and-error rather than letting curved MPLE+MLE do its thing. On the other hand, I can't get Faux Magnolia High to fit otherwise.

**Comment by krivit** [comment]
@martinamorris , shall we call it finished and push the package?

**Comment by krivit** [comment]
Given the time-frame, I am going to assume yes, and submit in about 8 hours barring anything very urgent.

**Comment by martinamorris** [comment]
thx for the help.  i made one small tweak 03f6a07.  ready to go.
