### ISSUE TITLE
Error in the curved target+offset test with certain seeds.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#32]
As of dd1c70a2a5480e32c4227be8545fe8847db125ab, 

```
library(ergm)
data(florentine)
set.seed(5)
ergm(flomarriage~offset(edges)+edges+gwdegree(fix=FALSE)+degree(0)+offset(degree(1)),target.stats=summary(flomarriage~edges+gwdegree(fix=FALSE)+degree(0)), offset.coef=c(0,-0.25))
```
or `set.seed(15)` produces
```
Starting contrastive divergence estimation via CD-MCMLE:
Iteration 1 of at most 60:
Convergence test P-value:2.1e-274
Optimizing with step length 1.
Error in check.objfun.output(out, minimize, d) : 
  objfun returned value that is NA or NaN
Error: $ operator is invalid for atomic vectors
```
However, it works for most seeds.

**Edit:** Updated to a more recent version and problematic seeds.

**Comment by chad-klumb** [comment]
so, back when we made `check.ErgmTerm` check for required arguments, I got an unexpected test failure that was addressed in 897fea33856e69d25ea288e8b4852ddf9c4344e9 by adding a required argument to `gwdegree`; I think it's the same test you're referring to above; the "default" value for the argument was zero, so that's what I set it to in the aforementioned commit

it looks like in your example, `gwdegree` isn't being passed its `decay` argument, which is required; when I try running that now I get the error

```
> ergm(flomarriage~offset(edges)+edges+gwdegree(fix=FALSE)+degree(0)+offset(degree(1)),target.stats=summary(flomarriage~edges+gwdegree(fix=FALSE)+degree(0)), offset.coef=c(0,-0.25))
Error: In term ‘gwdegree’ in package ‘ergm’: argument ‘decay’ is missing, with no default.
Call `rlang::last_error()` to see a backtrace
```

Explicitly passing in zero (the "default" value, even though the argument is required) for the `decay` argument reproduces the error you got:

```
> ergm(flomarriage~offset(edges)+edges+gwdegree(0, fix=FALSE)+degree(0)+offset(degree(1)),target.stats=summary(flomarriage~edges+gwdegree(0, fix=FALSE)+degree(0)), offset.coef=c(0,-0.25))
Starting contrastive divergence estimation via CD-MCMLE:
Iteration 1 of at most 60:
Convergence test P-value:6.1e-256
Optimizing with step length 1.
Error in check.objfun.output(out, minimize, d) : 
  objfun returned value that is NA or NaN
Error: $ operator is invalid for atomic vectors
```

but is zero a valid `decay` value, or does it have to be strictly positive?  (the documentation says "non-negative")

**Comment by chad-klumb** [comment]
On closer inspection the error also occurs for positive `decay` parameters (and `decay = 0` is probably fine anyway).

The error appears to originate in the `trust::trust` function.

**Comment by martinamorris** [comment]
decay=0 is an acceptable value

**Comment by chad-klumb** [comment]
I would interpret non-negative to mean greater than or equal to zero, so I think the doc is okay.

This doesn't appear to depend on the use of offsets or target stats, just CD as the estimation method:

```
library(ergm)
data(florentine)
set.seed(4)
ergm(flomarriage~edges+gwdegree(0,fix=FALSE)+degree(0),estimate="CD")

Starting contrastive divergence estimation via CD-MCMLE:
Iteration 1 of at most 60:
Convergence test P-value:1.4e-260
Optimizing with step length 1.
Error in check.objfun.output(out, minimize, d) : 
  objfun returned value that is NA or NaN
Error: $ operator is invalid for atomic vectors
```

Debugging the above model showed that the initial Hessian in `trust` was singular:

```
Browse[2]> out
$value
[1] 0

$gradient
[1] -2.6396484 -0.2841797  0.0000000  0.2841797

$hessian
                    edges   gwdegree gwdegree.decay    degree0
edges          -3.1367483 -0.4442015              0  0.4442015
gwdegree       -0.4442015 -0.3635778              0  0.3635778
gwdegree.decay  0.0000000  0.0000000              0  0.0000000
degree0         0.4442015  0.3635778              0 -0.3635778

Browse[2]> eout
eigen() decomposition
$values
[1] 3.290688e+00 5.732158e-01 5.551115e-17 0.000000e+00

$vectors
           [,1]       [,2]      [,3] [,4]
[1,]  0.9712630  0.2380088 0.0000000    0
[2,]  0.1682976 -0.6867867 0.7071068    0
[3,]  0.0000000  0.0000000 0.0000000    1
[4,] -0.1682976  0.6867867 0.7071068    0
```

Is this normal?

The `trust` function is rather opaquely written but eventually one ends up dividing by zero and that results in the NaN error when it calls `check.objfun.output` to check the results.  For other seeds one divides by something very close to zero (like 1e-34) but not exactly zero, and that apparently allows one to escape.  So this might be a sort of computational singularity problem.

**Comment by chad-klumb** [comment]
Not restricted to degree/gwdegree combination either:

```
> library(ergm)
> data(florentine)
> set.seed(8)
> ergm(flomarriage~edges+gwesp(0,fix=FALSE)+esp(0),estimate="CD")
Starting contrastive divergence estimation via CD-MCMLE:
Iteration 1 of at most 60:
Convergence test P-value:9.9e-270
Optimizing with step length 1.
Error in check.objfun.output(out, minimize, d) : 
  objfun returned value that is NA or NaN
Error: $ operator is invalid for atomic vectors
```

**Comment by chad-klumb** [comment]
I had initially thought that this might be due to the initial parameter value (all zeros) being a point of additional symmetry of the likelihood, resulting in degeneracy.  However, shifting the initial value away from zero was not totally successful in stopping the error (although it's possible it reduced the rate of failure; I'll have to tabulate things tomorrow).

```
library(ergm)
data(florentine)
set.seed(34)
ergm(flomarriage~edges+gwdegree(0,fix=FALSE)+degree(0),estimate="CD", control=control.ergm(init=runif(4)))

Starting contrastive divergence estimation via CD-MCMLE:
Iteration 1 of at most 60:
Convergence test P-value:0e+00
Optimizing with step length 0.789489878060986.
The log-likelihood improved by 1.445.
Iteration 2 of at most 60:
Convergence test P-value:2.7e-243
Optimizing with step length 1.
The log-likelihood improved by 0.9554.
Iteration 3 of at most 60:
Convergence test P-value:2.3e-98
Optimizing with step length 1.
Error in check.objfun.output(out, minimize, d) : 
  objfun returned value that is NA or NaN
Error: $ operator is invalid for atomic vectors
```

In this case, the initial Hessian is *not* singular
```
Browse[2]> out
$value
[1] 0

$gradient
[1] -2.3892863 -1.6624279 -1.7944857  0.3022266

$hessian
                    edges   gwdegree gwdegree.decay     degree0
edges          -2.2698126 -1.4107428    -1.72044604  0.19889069
gwdegree       -1.4107428 -1.1755239    -1.04534777  0.29750819
gwdegree.decay -1.7204460 -1.0453478    -1.37948905  0.05617081
degree0         0.1988907  0.2975082     0.05617081 -0.24993896

Browse[2]> eout
eigen() decomposition
$values
[1] 4.54469761 0.43085770 0.08661768 0.01259148

$vectors
            [,1]       [,2]       [,3]       [,4]
[1,]  0.70045725 -0.1768237 -0.5263580  0.4483752
[2,]  0.46589329  0.6024884  0.6081868  0.2237409
[3,]  0.53587243 -0.3833326  0.2324437 -0.7154487
[4,] -0.07172042 -0.6773457  0.5468327  0.4868603
```

but still apparently falls back into degeneracy after several iterations (or some other problem happens, resulting in the same error message).

**Comment by krivit** [comment]
I can no longer reproduce the error in any of these cases, even with other seeds, so I guess it got fixed along the way.
