### ISSUE TITLE
Shorten BDStratTNT test

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#322]
@chad-klumb , if you are up, can you please take a few minutes to do that? It takes about a minute, and I am worried the CRAN will complain.

**Comment by chad-klumb** [comment]
I wasn't up, and it sounds like `ergm` is already on CRAN, but I will do something about this in the not too distant future.

**Comment by krivit** [comment]
Thanks! I ended up just chopping the last 2/3 of the tests; I am not sure that's the optimal thing to do.

**Comment by chad-klumb** [comment]
This was addressed awhile ago by reducing the size and/or length of tests.
