### ISSUE TITLE
breakage in `broom` tidiers for `ergm` objects

### ISSUE THREAD

**Issue by simonpcouch** [statnet/ergm#327]
Hey there,

We're seeing a breakage in `broom` related to the newest version of `ergm`. I just wanted to confirm that our fix correctly adjusts to the new model object structure! Here's the old code for extracting MCMC related info:

https://github.com/tidymodels/broom/blob/9260363a4a771e0949e8d5af7d36c1cecf4ffc56/R/ergm-tidiers.R#L155-L157

Where are these parameters now stored in the outputted model object?

Much appreciated!

**Comment by martinamorris** [comment]
Thanks for the report!  

I'm still able to pull these elements from the fit object:

```
library(ergm)
data(faux.mesa.high)
fit <- ergm(faux.mesa.high ~ edges + degree(1:3))

...
> fit$control$MCMC.interval
[1] 256
> fit$control$MCMC.burnin
[1] 8192
> fit$control$MCMC.samplesize
[1] 1506
```

Can you send a reprex that fails?

**Comment by martinamorris** [comment]
@krivit, is it worth creating an accessor for the `control` component?

**Comment by simonpcouch** [comment]
Thank you for the quick reply! A quick reprex:

``` r
library(broom)
library(ergm)
#> Loading required package: network
#> 
#> 'network' 1.17.0 (2021-06-06), part of the Statnet Project
#> * 'news(package="network")' for changes since last version
#> * 'citation("network")' for citation information
#> * 'https://statnet.org' for help, support, and other information
#> 
#> 'ergm' 4.0.0 (2021-06-14), part of the Statnet Project
#> * 'news(package="ergm")' for changes since last version
#> * 'citation("ergm")' for citation information
#> * 'https://statnet.org' for help, support, and other information
#> 'ergm' 4 is a major release that introduces a fair number of
#> backwards-incompatible changes. Please type 'news(package="ergm")' for
#> a list of major changes.

data(florentine)

x <- ergm(flomarriage ~ edges + absdiff("wealth"))
#> Starting maximum pseudolikelihood estimation (MPLE):
#> Evaluating the predictor and response matrix.
#> Maximizing the pseudolikelihood.
#> Finished MPLE.
#> Stopping at the initial estimate.
#> Evaluating log-likelihood at the estimate.

x$control$MCMC.interval
#> NULL
x$control$MCMC.burnin
#> NULL
x$control$MCMC.samplesize
#> NULL

packageVersion("ergm")
#> [1] '4.0.0'
```

<sup>Created on 2021-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by martinamorris** [comment]
Lol.  That's because that model doesn't use MCMC.  And it doesn't because it has only `dyad.independent` terms (in this case, just a function of nodal attributes).

You'll need to condition on that, tho I'm surprised if this worked before.  Here's what to condition on (assuming the reprex above is still in your session:

```
x$MPLE_is_MLE
```
 
if `TRUE` then there's no MCMC info, b/c the fit used the MPLE algorithm instead.

**Comment by simonpcouch** [comment]
Ah, thank you so much for the helpful details! Will adjust the tidiers' logic accordingly.

**Comment by martinamorris** [comment]
And thanks for building a tidier for `ergm` :)
