### ISSUE TITLE
Fix an UBSAN issue in BDStratTNT().

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#332]
Quoth CRAN:
```
Note that clang-UBSAN still has

ergm.Rcheck/tests/testthat.Rout:MHproposals.c:208:67: runtime error: 
applying non-zero offset 4 to null pointer
ergm.Rcheck/tests/testthat.Rout:MHproposals.c:208:86: runtime error: 
applying non-zero offset 4 to null pointer
```

@chad-klumb , this looks like your code. Can you please take a look? (My UBSAN attempts aren't picking it up for some reason.)

**Comment by chad-klumb** [comment]
Looks like the same issue in 708a0bc679cd453e8baa7f44889e0ef2ceb7313d.

I assume it's fixed in 763dddacf2919ad8a4743780a9dbc884bee6952d, but suffice it to say I am not reproducing the CRAN checks either.

**Comment by krivit** [comment]
Thanks! I think LLVM is using different criteria than GCC.

**Comment by krivit** [comment]
CRAN is no longer showing the error.
