### ISSUE TITLE
Error in Robbins-Monro Main Method

### ISSUE THREAD

**Issue by CarterButts** [statnet/ergm#335]
It looks like the current `ergm` version has an issue with Robbins-Monro:

```
> fit<-ergm(faux.mesa.high ~ edges + degree(0) ,control=control.ergm(main.method="Robbins-Monro"))
Starting maximum pseudolikelihood estimation (MPLE):
Evaluating the predictor and response matrix.
Maximizing the pseudolikelihood.
Finished MPLE.
Robbins-Monro algorithm with theta_0 equal to:
     edges    degree0 
-4.2748881  0.9170791 
Phase 1:  13 iterations (interval=1024)
Error in seq_len(nc - 1L) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In ergm.getCluster(control, verbose) :
  Unrecognized value passed to parallel= control parameter. 
```

Looks like recent control changes might have bitten it.  FWIW, the stochastic approximation method seems to run fine, though its defaults seem to be a bit out of whack (probably needs more aggressive settings).

**Comment by krivit** [comment]
IIRC, R-M is basically S-A but in R, so we might just want to deprecate it at this point.

**Comment by CarterButts** [comment]
Yes, it's a bit odd in that R-M is a special case of S-A.  But I'm not sure that the implementations are the same; IIRC, the two have behaved rather differently in the past.  FWIW, I have found R-M to be useful in the past, either for (1) recalcitrant models, or (2) where more numerical stability is needed than G-T.  It's also useful to have multiple estimation methods for comparison purposes.  Whether we need both whatever is in S-A and whatever is in R-A is a different question, though.
