### ISSUE TITLE
ergm computating time

### ISSUE THREAD

**Issue by DamienGeorges** [statnet/ergm#336]
Hi all,

Since I have updated ergm to its latest version, the ergm computing using MCMLE has increased a lot. I have the feeling that it is due to a change in control.ergm() default parameters. 
I was happy with the previous default settings that was a good trade-off between model precision and computational burden. Is there a way to configure control.ergm() to reproduce formal package settings?
Alternatively, could you indicate which parameters I can tune to make my models converge faster?

Thanks,
Damien

**Comment by chad-klumb** [comment]
You could try including the following control arguments

```
MCMLE.termination="Hummel",
MCMLE.samplesize=1024,
MCMLE.interval=1024,
MCMLE.effectiveSize=NULL
```

to get MCMLE behavior more like `ergm` 3.x versions.

**Comment by DamienGeorges** [comment]
Perfect! Thanks!!
