### ISSUE TITLE
Provide a mechanism for providing concept abbreviations and descriptions dynamically.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#343]
The first solution that comes to mind is:
```r
ergm_concept_abbrev(directed = "dir")

ergm_concept_abbrev("directed")

# > [1] "dir"
```
A package implementing new concepts can then call them in its `.onLoad()`.

However, there is no way for a package that exists but is not loaded to export its abbreviation. This may be irrelevant if we decide not to list terms in packages that are not loaded.

**Comment by krivit** [comment]
Since we now also want descriptions, we probably want some other interface. One possibility:

```r
ergm_concept(name="directed", short="dir",
             description="This term may be used with directed networks.",
             package="ergm")

ergm_concept()

## Output: a data frame with columns 'name', 'short', 'description', and 'package'
## that gets updated and, ideally, automatically purges keywords from unloaded packages.
```
@joycecheng , what do you think? I think we can repurpose code from elsewhere to do this.

**Comment by joycecheng** [comment]
That sounds pretty straightfoward

**Comment by krivit** [comment]
Sure, but I think we can hold off on that: filtering data frames is easy enough on the user end with, e.g., `subset()` or `dplyr`. Implementing the basic capability and incorporating it into the existing docs takes priority.

On further thought, we want to have an additional column in the table: frequently used. I'll update the ticket.
