### ISSUE TITLE
Local links on ?ergmConstraint

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#345]
(moved from joycecheng/ergm#3) copied from https://github.com/statnet/ergm/discussions/274#discussioncomment-963701.

I noticed that on `?ergmConstraint` the local links in the "Jump to category" list do not work. While the links look OK, e.g. the first one is:

```html
<a href="#cat_bipartite" onclick="window.parent.helpNavigate(this.href); return false">bipartite</a>
```

The category headers (to which these should lead, right?) don't have the proper `id`:

```html
<a id="bipartite" onclick="window.parent.helpNavigate(this.href); return false">bipartite</a>
```

The `id` should be `cat_bipartite` isn't it?

I did not yet check what's the situation on other dynamic pages.

**Comment by joycecheng** [comment]
Fixed for `?ergmTerm`
