### ISSUE TITLE
gof output for minimum geodesic distance shows no variation in simulated values

### ISSUE THREAD

**Issue by JeffreyAlanSmith** [statnet/ergm#347]
I am using the updated ergm package and noticed some odd output when using the gof function. The outputted values for distance appear to have no variation, which doesn't seem right. Here's a basic example from the gof help file: 

library(ergm)
data(florentine)
gest <- ergm(flomarriage ~ edges + kstar(2))

gofflo <- gof(gest, GOF=~distance)
gofflo

Goodness-of-fit for minimum geodesic distance 

    obs min mean max MC p-value
1    20  20   20  20          1
2    35  35   35  35          1
3    32  32   32  32          1
4    15  15   15  15          1
5     3   3    3   3          1
Inf  15  15   15  15          1

The simulated values all look the same and are set at the observed value. Am I missing something obvious or is this a bug?

**Comment by martinamorris** [comment]
thx for reporting @JeffreyAlanSmith :)

**Comment by martinamorris** [comment]
@krivit so this probably explains the graph below:

![image](https://user-images.githubusercontent.com/8194530/126414297-e3db8a10-fc0c-41fb-b33a-a7e27132aae0.png)

We'll need to update the CRAN version before the NME workshop 8/2
