### ISSUE TITLE
check.ErgmTerm does not check type of NULL arguments

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#349]
`NULL` is allowed for some arguments (e.g., levels) but not others (e.g., nodal attributes)

currently `check.ErgmTerm` does not check the type of arguments passed as `NULL`, meaning you can pass a `NULL` attribute and (incorrectly) get through `check.ErgmTerm`

e.g.

```
require(ergm)
nw <- network.initialize(10, dir = F)
summary(nw ~ nodemix(NULL))
```

produces

```
> summary(nw ~ nodemix(NULL))
Error in UseMethod("ergm_get_vattr") : 
  no applicable method for 'ergm_get_vattr' applied to an object of class "NULL"
```

It errors, but only after getting through `check.ErgmTerm`.

I would expect `check.ErgmTerm` to catch the incorrect type and give an error message like it does with incorrect non-`NULL` arguments

```
Error: In term ‘nodemix’ in package ‘ergm’: ‘attr’ argument is not of any of the expected (function,formula,character,AsIs) types.
```

**Comment by krivit** [comment]
Looks like we can make the check more strict, but it would break some existing terms that accept `NULL` but don't make it explicit. Someone would need to go through them and fix them up.

**Comment by krivit** [comment]
Another approach is to make a change early in `check.ErgmTerm()`: for all optional arguments, add whatever the class of the default argument is to the permitted classes. This approach has the advantage of fixing this problem without requiring terms to be updated, but the disadvantage is that an object can have multiple classes, and we need to guess which one(s) count. Maybe we can do it for `NULL` defaults only.

@chad-klumb , what do you think?

**Comment by chad-klumb** [comment]
In principle adding `NULL` to the allowed classes in `check.ErgmTerm` for optional arguments whose default is `NULL` sounds reasonable, but it appears some term modification would still be needed, e.g. `base` in `nodefactor` defaults to `1` and has allowed class `numeric` (only), but `base = NULL` is a valid argument.

We could just not worry about this for now.  It's not really important IMO, just something I happened across randomly, and I don't think it's worth anyone's time to go through all the terms searching for places they may need to insert `NULL` into allowed class lists (even if it really "should" be there).

**Comment by krivit** [comment]
For level specification, the `NULL` is included in `ERGM_LEVELS_SPEC`, so that's fine. It's the attribute specification that's concerning.
