### ISSUE TITLE
Help wanted -- nodemix term

### ISSUE THREAD

**Issue by yinfanuci** [statnet/ergm#35]
Let's say we want to build up a model for faux.mesa.high network, with nodemix term accounting for the cross-Grade pairing effects. Specifically, for example, we only want to consider such effects between two grades with the largest number of members (grade 7 and grade 9), then what might be the appropriate way to specify the model?

I tried the following code --

`nodemix_try` <- ergm(faux.mesa.high ~ edges + nodemix("Grade", base = c(7,9)), estimate = "MPLE")
summary(nodemix_try)
`
![nodemix_try](https://user-images.githubusercontent.com/36427582/48298417-d4f40780-e471-11e8-8168-8ac0aafbd1a7.jpg)

It seems that the effects of all possible pairs of grades are considered in the model, despite that I specified base = c(7,9) as the argument for nodemix.

May I know what I should do to achieve the aforementioned goal?

Thanks!

**Comment by krivit** [comment]
In general, the issue tracker is meant for bug reports and feature requests for the package; I would recommend asking the mailing list (https://mailman13.u.washington.edu/mailman/listinfo/statnet_help) in the future.

To answer your question, I would recommend using the new mixing matrix `mm()` term, which has a more flexible interface for specifying which cells you want.
