### ISSUE TITLE
warnings and errors with predict.ergm function

### ISSUE THREAD

**Issue by Pachka** [statnet/ergm#353]
Good afternoon,

I am having an issue with the predict.ergm function and I am not sure if it is an error in the function or in my model.
If it comes from my model I apologize in advance.

For one of my fitted ERGMs, the use of the 'predict' function produced the following error:

```
Error in ergm.pl(nw, fd, model, verbose = verbose, control = control,  :
  The maximum number of unique dyad types times the number of statistics exceeds 32 bit limits, so the MPLE cannot proceed; try reducing either MPLE.max.dyad.types or the number of terms in the model.
```

I had to comment the 119th line of the function (control = control.ergm(MPLE.max.dyad.types = Inf)) to generate ties probabilities.
Nevertheless, while it doesn't occur when adjusting the ergm, I still have the following warning when I use the predict function:
```
Warning message:
In ergm.pl(nw, fd, model, verbose = verbose, control = control,  :
  Too many unique dyads. MPLE is approximate, and MPLE standard errors are suspect.
```

Also, not so important but just a user feedback, only the 'matrix' output gives me the vertex names, the 'data.frame' output is made of numerical ids. 

Thanks by advance,

**Comment by krivit** [comment]
@Pachka , thanks for the report! Can you give us some idea bout the size of the network and about the model?

**Comment by Pachka** [comment]
Dear @Krivit,

The network is huge: 6121 nodes and 12,270 edges. It is directed and not bipartite.

The model contains 96 parameters, including edges as the only structural variable (all other variables are dyad independant - based on nodal attributes), so no MCMC estimation is performed.

glm outputs are:
Degrees of Freedom: 419625 Total (i.e. Null);  419529 Residual
Null Deviance:	    51930000 
Residual Deviance: 84410 	AIC: 84600

MLE likelihood is:
'log Lik.' -42205.95 (df=96)

Would you need any other information?

**Comment by krivit** [comment]
6k isn't huge these days, but the first problem is just as the error message describes: `predict.ergm()` has to compute the change statistics for every dyad in the network and for every parameter and store them, and they are currently indexed by a C integer. Therefore, if you delete that line what you will probably get is prediction only for some subset of the dyads.

Right now, this is inevitable, because prediction piggybacks on MPLE, but perhaps a more optimised version in the future could do better.

**Comment by Pachka** [comment]
Indeed, the matrix of ties probabilities is filled with a lot of NA, I guess it is related.
We will try to find another way to estimate the contact probabilities between the nodes while waiting for future versions.
Thank you

**Comment by krivit** [comment]
Good luck! One immediate workaround is to use a model with fewer parameters.
