### ISSUE TITLE
Release ergm 4.1 to CRAN.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#356]
# Checklist before submitting to CRAN

## Directions for use

1. Create an appropriately named issue (e.g., "Release package version *version*.").
1. Copy-paste this file into the issue text to provide the checklist functionality.
1. **After a commit directly pursuant to a checkbox item**, uncheck all checkboxes below it.
1. **After any other commit to `master` branch**, uncheck all boxes from the "`master` branch" section down.
1. **After any other commit to `*release*` branch**, uncheck boxes from the "Release branch" section down.
1. Close the issue after all boxes are checked.

## `master` branch

* [x] `DESCRIPTION`: Package's CRAN dependencies require a recent CRAN version.
* [x] `DESCRIPTION`: Package's dependencies that are a part of R core (`base`, `datasets`, `grDevices`, `methods`, `splines`, `stats4`, `tools`, `utils`, `compiler`, `graphics`, `grid`, `parallel`, `stats`, `  tcltk`, `translations`) do *not* specify a version.
* [x] `DESCRIPTION`: Package's dependencies that are usually shipped with R (`KernSmooth`, `Matrix`, `MASS`, `class`, `nnet`, `spatial`, `boot`, `cluster`, `codetools`, `foreign`, `lattice`, `mgcv`, `nlme`, `rpart`, `survival`) do *not* specify a version unless necessary.
* [x] All tickets associated with the release's milestone have been resolved.
* [x] The stubs file in `inst/include/` is up to date if needed.
* [x] Roxygen has been run on the package since last commit to code, documentation, or `DESCRIPTION`.
* [x] Relevant tutorials run satisfactorily.
* [x] `inst/NEWS.Rd`: file is up to date: none of the commits since the last commit to explicitly mention updating the `NEWS` file are newsworthy.
* [x] `LICENSE`: license refers to the correct package.
* [x] `LICENSE`: affiliations are up to date.
* [x] `LICENSE`: copyright year range is correct.
* [x] All files that should have them have copyright headers. Generally, it never hurts to rerun `addcopyheaders` to ensure this.
* [x] `R CMD check` passes with `ENABLE_statnet_TESTS=yes` environment variable *and* `--run-donttest`.
* [x] `rchk` static code analysis passes.
* [x] Tests pass with UBSAN.
* [x] If applicable, `R CMD check` passes with `ENABLE_statnet_TESTS=yes`, `DEBUG` compiler flag set, and `NDEBUG` unset.
* [x] `*pkg*.tar.gz`: `R CMD check` passes on the previous stable release (unless there is a good reason to require the latest R).
* [x] Reverse dependency checks pass unless breakage known.

## Release branch

* [x] Release branch has had the latest `master` merged into it. (`git checkout *release*; git merge master`)
* [x] `DESCRIPTION`: There are no `Remotes:` directives (unless releasing simultaneously).
* [x] `R-CMD-check.yaml`: `rcmdcheck()` is called with `error_on = "warning"`.
* [x] `DESCRIPTION`: Release branch's version number does not have commit number attached to it.
* [x] `DESCRIPTION`: Date is today.
* [x] `CITATION`: `update_CITATION` has been run after installing all the mentioned packages from the release branch.
* [x] All files in the release branch have been committed and pushed to GitHub.
* [x] `*pkg*.tar.gz`: the candidate submission file is from the latest version of the release branch.
* [x] `*pkg*.tar.gz`: `R CMD check` passes with `ENABLE_statnet_TESTS=yes` environment variable *and* `--run-donttest`.
* [x] `*pkg*.tar.gz`: `R CMD check` passes with `--as-cran` option without `WARNING`s.
* [x] `*pkg*.tar.gz`: `R CMD check` passes Win-Builder (https://win-builder.r-project.org).

## After release

* [x] Release branch corresponding to the package on CRAN has been tagged with the exact CRAN version and pushed to GitHub.

**Comment by krivit** [comment]
@chad-klumb , @martinamorris has asked me to push this update ASAP. Are you happy with your most recent BDStrat changes going to CRAN, or would you rather hold off?

If the latter, I will make a minimal release instead.

**Comment by chad-klumb** [comment]
Holding off on the recent changes is fine with me; I don't think anything of mine after 763dddacf2919ad8a4743780a9dbc884bee6952d needs to go to CRAN right now.

**Comment by krivit** [comment]
@chad-klumb , I would prefer to release the changes, and the question is whether you are happy with the changes you've made to `master` going out tonight.

**Comment by chad-klumb** [comment]
I'm not aware of a reason why they shouldn't go out.

**Comment by martinamorris** [comment]
ah the old double negative...

**Comment by krivit** [comment]
1b825569c8966d4a2bc133c47a72b848d7a199ce submitted to CRAN.

**Comment by krivit** [comment]
4d2aa5c59fb20ba95136c475132df60b6da8ecb6 resubmitted to CRAN after fixing automated check complaint.

**Comment by krivit** [comment]
8ec119c64e09e835f92bcd23cbbde11dd8df2465 resubmitted to CRAN after fixing revdep for `tergm`.

**Comment by krivit** [comment]
8ec119c64e09e835f92bcd23cbbde11dd8df2465 on CRAN as 4.1.2.
