### ISSUE TITLE
Implement inclusion and exclusion by category in .buildTermsDataframe().

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#374]
For flexibility, I am thinking of just passing a `purrr`-style formula with the predicate. E.g.,

List only operator terms:
```r
.buildTermsDataframe("ergmTerm", categories = ~"operator" %in% .)
```
Exclude all operator terms:
```r
.buildTermsDataframe("ergmTerm", categories = ~! "operator" %in% .)
```
List binary terms that are not operators:
```r
.buildTermsDataframe("ergmTerm", categories = ~! "operator" %in% . && "binary" %in% . ) # Watch the operator precedence: %in% > ! > &&.
```
List terms that are either operator or binary or both:
```r
.buildTermsDataframe("ergmTerm", categories = ~any(c("operator","binary") %in% .))
```
List terms that are both operator and binary:
```r
.buildTermsDataframe("ergmTerm", categories = ~all(c("operator","binary") %in% .))
```
Exclude any term that is either operator or binary (or both):
```r
.buildTermsDataframe("ergmTerm", categories = ~!any(c("operator","binary") %in% .))
```
Exclude any term that is both operator and binary:
```r
.buildTermsDataframe("ergmTerm", categories = ~!any(c("operator","binary") %in% .))
```

@martinamorris , would this interface work?

@joycecheng , I already have a prototype implementation for this, so don't worry about this for the moment. I may ask you to "generalise" this to filtering on other things and apply it to term matrix as well later.

**Comment by martinamorris** [comment]
I like the general idea.  Would the user syntax be `?search.ergmTerm("Operator")`?

**Comment by krivit** [comment]
This isn't for the term search; this is for the internal function used to filter the term table that displays in the help files, such as having a separate table for operators and not. It may be exposed to the end-user in some way, but not for the moment.

**Comment by martinamorris** [comment]
Then I'm not sure what you're asking me to comment on.  The internal interface is not something I'm an expert on :)

**Comment by krivit** [comment]
You might be invoking this one when editing docs.

**Comment by martinamorris** [comment]
Ok, I'm still not sure what the alternatives would be in this context.

**Comment by krivit** [comment]
Maybe two separate arguments, e.g., `only=` and `exclude=` that take lists of concepts, or maybe just one with special syntax such as `categories = "operator"` to list only operators and `categories = "!operator"` to exclude them. The downside of all those is that it's difficult to represent all possible combinations of things you want, such as "basic" terms that are binary and not operators.

Anyway, I'll push it, and we'll see how it goes.
