### ISSUE TITLE
Standardise terminology for term and termalike keywords/concepts/categories.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#376]
As a background, each `ergm` term and termalike has words (e.g., `commonly used`, `directed`, `valued`, `operator`) that identify its properties for the purposes of documentation and searching.

These are implemented as `\concept{}` entries in the help file (`#' @concept` in Roxygen). This is because R's documentation asks that we refrain from adding new `\keyword{}`s.

However, we do not use consistent naming for them in the documentation or in our code: they are called "keywords" in some places, "categories" in others, and "concepts" in others, and we should probably standardise on one.

Fundamentally, we can use any of these three, or something else. Any thoughts?

@martinamorris , @sgoodreau , @drh20drh20 , @CarterButts , @mbojan , @handcock , @chad-klumb

**Comment by handcock** [comment]
As you say, they are properties. So, "properties" is fine as is "keywords" if it is allowed.

**Comment by krivit** [comment]
@martinamorris , given your other comments, I take it your vote is also for "keywords"?

**Comment by martinamorris** [comment]
agreed.  i have a preference for "keywords" as i think it is more 
established for users.

On Fri, 3 Sep 2021, Mark S. Handcock wrote:

> 
> As you say, they are properties. So, "properties" is fine as is "keywords" if it is allowed.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.[AB6QTYWHMDT3WO5AWB453D3UAF56RA5CNFSM5DMX3BE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZ
> GOGZUZXTY.gif]
> 
> 
>

****************************************************************
  Professor Emerita of Sociology and Statistics
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

**Comment by krivit** [comment]
OK, sound like "keywords" it is. We'll probably need to change `search.ergmTerms()` so that its `keywords=` argument searches concepts and not title and description, but we are already reshuffling its arguments.

**Comment by krivit** [comment]
Done.
