### ISSUE TITLE
Do we still need man/eut-upgrade.Rd?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#384]
We transitioned to the `LinkingTo` mechanism back in 2013, so I don't think anyone still needs to know how to convert from the old way of invoking user terms. Any objections to deleting?

**Comment by krivit** [comment]
@drh20drh20 , @handcock , @sgoodreau ?

**Comment by drh20drh20** [comment]
Is  the old way broken/deprecated now?   If not, what's the benefit of removing this doc?

**Comment by krivit** [comment]
IIRC, the old way was to copy the header files into the userterms package and keep them up to date with `ergm`'s, and it was deprecated back in 2013. The new (and current) way is to use `LinkingTo:` and copy one file that only includes the stub file from `ergm` and never ever changes. The purpose of the document was to tell people to start using the new mechanism.

The reason to remove it is, as always, to reduce the size of the code and the maintenance burden.

**Comment by handcock** [comment]
Certainly no need to keep it from my view. Only the natural balance that any change may introduce errors.

**Comment by krivit** [comment]
As far as I can tell, the only scenario in which it might still be useful would be if someone has some user terms from before 2013 (which was before the userterms paper was published) that they hadn't used since, and now comes back and tries to use them.

**Comment by CarterButts** [comment]
Perhaps this is something that could be relegated to the userterms 
vignette?  Does seem like a good thing to have written down somewhere, 
but at this point it probably should be relegated to some kind of 
"historical notes/changes" spot....

**Comment by krivit** [comment]
It might be worth leaving in the `ergm.userterms` package.

**Comment by martinamorris** [comment]
Maybe better to put it in a self-contained file, in the repository (say the "inst" folder), and refer people there as needed.

Alternatively, people can always use the CRAN archive, or our GH repo, to find it.  Part of me thinks the onus should be on others to update to current status, not on us to keep 10 year old code working transparently.  There are more important priorities...

**Comment by sgoodreau** [comment]
I agree with the theme that, if there's any easy way to do it, it should be documented somewhere with a pointer to where people can find it, without keeping it in the actively maintained codebase. Ultimately I don't think it's going to be a big deal one way or another.

**Comment by krivit** [comment]
OK. I'll go ahead and remove it; it might be worth keeping in the userterms package (which needs a 4.0 update anyway).
