### ISSUE TITLE
Sort out what network.list(), as.network.list(), etc. are supposed to do.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#4]
```
library(ergm)
data(samplk)
network.list(samplk1, samplk2, samplk3) # Error
network.list(list(samplk1, samplk2, samplk3)) # Also error
```

**Comment by chad-klumb** [comment]
It appears `network.list()` was fixed, and I don't see `as.network.list()` anywhere.

It looks like second and later arguments to `network.list()` need to be named because they get attached to the `network.list` object as attributes.

Is there anything left to do for this issue?
