### ISSUE TITLE
Help page for the ddsp term is incorrect

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#41]
There are 5 possible options for the type argument (noted in the ddsp help text correctly).  But only 4 are then listed.

The 5 should be:

#  UTP - Undirected two-path (undirected graphs only)
#  OTP - Outgoing two-path (i->k->j)
#  ITP - Incoming two-path (i<-k<-j)
#  RTP - Reciprocated two-path (i<->k<->j)
#  OSP - Outgoing shared partner (i->k<-j)
#  ISP - Incoming shared partner (i<-k->j)

The RTP is missing now from the help.

It would also be good to have this info duplicated in the help for all of the dgw*sp terms -- right now the help for those terms just points users to the help for ddsp.

**Comment by chad-klumb** [comment]
@martinamorris I have added RTP to the d*sp docs, so for example ddsp now reads:

![ddspdoc](https://user-images.githubusercontent.com/10733914/61817921-8a020080-ae04-11e9-8eb2-c695f49936ed.png)

and similarly for other d*sp terms

Does this satisfy the requirements of this issue?

**Comment by martinamorris** [comment]
Not sure how to interpret the diff file -- is this explanation now added to all of the directed shared partner terms: ddsp, dnsp, desp?

We also want something similar to this to be added to the dgw*sp terms.  In the gw context, you're not adding one statistic per value of the d*sp, so that wording needs to be changed, but the 5 configuration descriptions should be included in the dgw*sp term help.

**Comment by chad-klumb** [comment]
The change was to the SPTypes macro, so in the six places where that's used (all the d*sp terms, including the gw ones) the RTP type is now described (in addition to the other four types).  Any other description is unchanged.  For example, dgwdsp reads:

![dgwdsp](https://user-images.githubusercontent.com/10733914/61829061-f7ba2680-ae1c-11e9-841e-77d441815812.png)

**Comment by martinamorris** [comment]
Perfect!  Thx.
