### ISSUE TITLE
sginv fails to deal with terms that are very close to zero  

### ISSUE THREAD

**Issue by marcishak** [statnet/ergm#419]
repex:

```
x <- matrix(c(-9.371797e-28, 0, 0, 1), byrow = T, nrow = 2, ncol = 2)
ergm:::sginv(x)
```

```
Error in svd(X) : infinite or missing values in 'x'
In addition: Warning message:
In sqrt(d) :
 Error in svd(X) : infinite or missing values in 'x' 
```

**Comment by krivit** [comment]
Thanks for the report! The problem here isn't the magnitude; it's the sign. How did it come to pass that `sginv()` was passed a non-SPD matrix?

**Comment by marcishak** [comment]
Not 100% sure.

I  was testing a couple of models with curved parameters (more on that soon). I assumed that there was probably some sort of rounding error given the magnitude.  All the other values along the diagonal in the matrix were positive, bar the value used in the test case. 

My understanding is that with curved models, it uses ```ergm:::logitreg()``` instead of  ```stats::glm()```, so it could be downstream of that. I have the matrix that went into ```sginv``` (which I've uploaded within a .zip as github doesn't allow .rda ) and the model still if need be.

[ginv_dump_inter.zip](https://github.com/statnet/ergm/files/7569850/ginv_dump_inter.zip)
