### ISSUE TITLE
Processing time on simulate.ergm has substantially slowed due to constraint processing in ergm_proposal

### ISSUE THREAD

**Issue by smjenness** [statnet/ergm#42]
## The Problem
Over the summer, there was a revision in how attributes for constraints were stored. I'm not exactly sure why, but they are now stored in an `.attributes` sublist. It looks like the processing of these attributes by `ergm_proposal` within `simulate.ergm` is now substantially slower than before this change. In dynamic simulations that call `simulate.ergm` repeatedly, this results in many of our "built-in" models in EpiModel that use the full functionality of ergm/tergm now being effectively un-runnable on laptops during timed events like workshops. One way around this is to use `tergmLite` 100% of the time, but that would be unfortunate.

## Profile Example
Here is a R profile of the clock time it takes to run `simulate.ergm` on a network of 10k vertices and ~2000 edges:

<img width="1038" alt="screen shot 2018-12-14 at 1 29 55 pm" src="https://user-images.githubusercontent.com/2521570/50020754-f8483000-ffa4-11e8-8d63-d44af3ec6e47.png">

Clock time was about 3.6 seconds, with 3.4 seconds taken up by `ergm:::InitErgmConstraint..attributes`. I don't have an equivalent profile of this would have taken before the changes over the summer, but my eyeball estimate was 500 ms in the older versions of ergm.

Interestingly, this model (fit with a target stats approach) has no "true" constraints (i.e., arguments passed to the `constraints` parameter in `ergm`. We have "effective" constraints on the model by passing in 0's for target stats to our formation terms. Here's the model, and we use 0's for the last three target stats:

```r
model_casl <- ~edges +
               nodematch("age.grp", diff = TRUE) +
               nodefactor("age.grp", base = 3) +
               nodematch("race") +
               nodefactor("race", base = 1) +
               nodefactor("deg.main", base = 3) +
               concurrent +
               degrange(from = 4) +
               nodematch("role.class", diff = TRUE, keep = 1:2)
```

Why did the run time substantially increase? What are the different strategies to reduce the computational time in this use case? Are the new `.attributes` for constraints relevant in this example? Could we reduce the writing and reading time through `ergm:::InitErgmConstraint..attributes` for models with no true constraints? Even in models with true constraints (really, only `~bd(maxout = X)` ever) , do we need `ergm:::InitErgmConstraint..attributes`?

## Reproducible Example for profiling

1. [Download Fitted ERGM](https://www.dropbox.com/s/j9qduzxkdt65dv3/artnet.NetEst.Atlanta.rda?dl=1)
2. Run this script

```r
#install.packages("profvis")
library(profvis)
est <- readRDS("path/to/dir/artnet.NetEst.Atlanta.rda")
fit <- est[[2]]$fit
profvis(simulate(fit, basis = fit$newnetwork))
```

---------------
cc: @martinamorris @sgoodreau

**Comment by smjenness** [comment]
Just as a follow-up, I was curious if I myself could test whether `ergm:::InitErgmConstraint..attributes` was necessary for simulations of the type described above. I think it's not necessary, and furthermore, reduces the runtime for simulate.ergm by over ten-fold to ~200 ms. Wow!

The method was to comment out all the computationally expensive stuff that the function does, then replace the new function in the ergm namespace.

```r
InitErgmConstraint..attributes2 <- function(lhs.nw, ...){
  list(
    # free_dyads = {
    # n <- network.size(lhs.nw)
    ## NB: Free dyad RLE matrix is stored in a column-major order for
    ## consistency with R.
    # d <-
    # if(has.loops(lhs.nw)) rep(rep(rle(TRUE),n,scale="run"),n,scale="run")
    # else do.call(c, lapply(seq_len(n), function(i) rep(rle(c(TRUE,FALSE,TRUE)), c(i-1, 1, n-i),scale="run")))
    
    # if(is.bipartite(lhs.nw)){
    #   n1 <- lhs.nw%n%"bipartite"
    #   n2 <- n - n1
    #   
    #   d <- d &
    #     c(rep(rep(rle(c(FALSE)),n,scale="run"),n1,scale="run"),
    #       rep(rep(rle(c(TRUE,FALSE)),c(n1,n2),scale="run"),n2,scale="run"))
    # }
    
    # if(!is.directed(lhs.nw)){
    #   d <- d &
    #     do.call(c, lapply(seq_len(n), function(i) rep(rle(c(TRUE,FALSE)), c(i-1, n-i+1),scale="run")))
    # }
    # 
    # rlebdm(compact.rle(d), n)
    # },
    constrain = character(0),
    dependence = FALSE)
}

assignInNamespace("InitErgmConstraint..attributes", InitErgmConstraint..attributes2, 
                  ns = "ergm", envir = as.environment("package:ergm"))

profvis(simulate(fit, basis = fit$newnetwork))
```

<img width="1032" alt="screen shot 2018-12-14 at 2 34 15 pm" src="https://user-images.githubusercontent.com/2521570/50023662-df904800-ffad-11e8-975b-d341e3abd317.png">

**Comment by krivit** [comment]
Thanks for the profiling. This functionality is a part of an API that now lets `ergm` handle arbitrary combinations of dyad-independent constraints in a reasonably efficient manner, by representing constraints as large boolean matrices of dyads. Run-Length Encoding (RLE) is used because it efficiently represents matrices with long contiguous runs of 0s or 1s, which these matrices usually are.

I'll try to see which part of this code is slowing things down and optimise it.

**Comment by smjenness** [comment]
Thanks Pavel. Might it be possible to turn off this code altogether if there are no constraints in the model?

**Comment by martinamorris** [comment]
On Fri, 14 Dec 2018, Pavel N. Krivitsky wrote:

> 
> Thanks for the profiling. This functionality is a part of an API that now lets ergm handle arbitrary combinations of
> dyad-independent constraints in a reasonably efficient manner, by representing constraints as large boolean matrices of
> dyads. Run-Length Encoding (RLE) is used because it efficiently represents matrices with long contiguous runs of 0s or
> 1s, which these matrices usually are.
> 
> I'll try to see which part of this code is slowing things down and optimise it.

sounds like the classic case of generalizing code leading to sub-optimal 
operation for primary uses :(

if this can't be optimized, can it be bypassed with an implicit flag based 
on use case?

**Comment by krivit** [comment]
@smjenness , how about now?

With respect to skipping it altogether, the `dev` branch splits the `simulate.formula()` method into a `simulate.formula()` and a `simulate.ergm_model()` method, with the former calling the latter, and the latter taking an initialised model and (potentially) an initialised proposal.

**Comment by krivit** [comment]
@smjenness , anyway, the optimisations are in `master`. Let me know if that's good enough.

**Comment by smjenness** [comment]
That is a massive improvement, thank you Pavel! I want to ask whether you still might consider having ergm_proposal avoid running the function altogether during simulation if there are no constraints specified in the model, if those calculations are not necessary. It might save another ~200 ms per simulation, which adds up over thousands of simulations.

**Comment by krivit** [comment]
I can backport the splitting of `simulate.ergm_model` from `simulate.formula` to `master`; that might help.

**Comment by krivit** [comment]
I have now done this. You should be able to pre-build an `ergm_model` and `ergm_proposal` object (perhaps by calling `simulate.formula()` with `do.sim=FALSE`, and then call `simulate(your_ergm_model, constraints=your_ergm_proposal)` repeatedly as needed.

This is probably the best we can do for now, so I will close this, but please reopen if you have other ideas or suggestions.
