### ISSUE TITLE
Error with dependencies lpSolveAPI?

### ISSUE THREAD

**Issue by smy310** [statnet/ergm#441]
Error:
Finished MCMLE.
Evaluating log-likelihood at the estimate. Fitting the dyad-independent submodel...

 *** caught segfault ***
address 0x2af626baa000, cause 'memory not mapped'

Traceback:
 1: (function (lprec) {    .Call(RlpSolve_delete_lp, lprec)    invisible(lprec)})(<pointer: 0x35452580>)
An irrecoverable exception occurred. R is aborting now ...

A short review all steps I did as below:
https://github.com/leifeld/btergm/issues/30#issue-1181011438

I am trying to do ergm examples as Leifeld suggested, it will take for a while.
Perhaps you have other suggestions that I can test more?

Thanks a lot!

**Comment by krivit** [comment]
Thanks for the report! The C code in question doesn't actually belong to `ergm` but to `lpSolveAPI`, but it could, in theory, be the case that `ergm` calls it incorrectly.

I can't investigate further without a self-contained reproducible example, however.

**Comment by smy310** [comment]
I have updated reply to maintainer of btergm.

https://github.com/leifeld/btergm/issues/30#issuecomment-1085870637

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: Pavel N. ***@***.***>
Gesendet: 2022年4月1日 6:43
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [statnet/ergm] Error with dependencies lpSolveAPI? (Issue #441)


Thanks for the report! The C code in question doesn't actually belong to ergm but to lpSolveAPI, but it could, in theory, be the case that ergm calls it incorrectly.

I can't investigate further without a self-contained reproducible example, however.

―

**Comment by smy310** [comment]
@leifeld I have sent Pavel my data and codes directly. Thanks for your advice!

**Comment by krivit** [comment]
@smy310, I don't think I got any R code from you; just data and output.

**Comment by smy310** [comment]
I have sent you the rda files as required. Would you please have a look? Thanks! @krivit

**Comment by leifeld** [comment]
@smy310 You need to include the R code. See http://sscce.org.

**Comment by smy310** [comment]
> @smy310 You need to include the R code. See http://sscce.org.

The R codes were also sent to him per email.
