### ISSUE TITLE
when i add same nodes  distance and language Exogenous contextual network, I meet some problem

### ISSUE THREAD

**Issue by ru-zheng** [statnet/ergm#446]
when i add  distance and language Exogenous contextual network(from CEPII dataset) which with the same nodes with origin trade network, I meet some problem:
Error in if (any(low.drop.theta)) message(paste("Observed statistic(s)",  : missing value where TRUE/FALSE needed

I did not know how to do,maybe I can construct  distance network and language network with all given nodes?

**Comment by krivit** [comment]
Thank you for the report! Could you please provide a reproducible example?

**Comment by krivit** [comment]
No reply since April. I'm closing this until there is a reproducible example.
