### ISSUE TITLE
Error when trying to run an ANOVA table for valued ergm

### ISSUE THREAD

**Issue by santiagcarcal** [statnet/ergm#471]
I am fitting a valued ERGM model of a bipartite network. I am using `sum` as the valued term and the weights of the bipartite matrix as the response variable. I'm using packages `ergm` and `ergm.count` to fit the model and `network` to construct the objects.
I've fitted the model and obtained the estimates, but I want to call an ANOVA table for the model using `anova(ergm.1, test="Chi")` . But I get this error: `Error: $ operator is invalid for atomic vectors`.
Alternatively when I use `anova(ergm.1)`  I only get an 'empty' anova table, as if I had not specified the variables.

**Comment by mbojan** [comment]
Unlike the GLM method, the method `anova.ergm()` does not have the `test` argument. It's primary job is model comparison. What exactly do you want to achieve?

**Comment by santiagcarcal** [comment]
THanks for your answer. I want to know how much variation in link formation is explained by each attribute.
