### ISSUE TITLE
add control argument to skip hashing in ergm_state

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#474]
as introduced in https://github.com/statnet/ergm/commit/0424bd80c3224e37b5e5a8e0cef61ae60e923607

Generating the hash can take a lot of time for some EpiModel applications.

cf. https://github.com/EpiModel/EpiModelHIV-p/issues/120

**Comment by krivit** [comment]
I see. It speeds up most parallel applications by quite a lot, since it only needs to serialise model and proposal objects once per `ergm()` call, but if you are running everything in a single thread, indeed there is no point in computing the hash.

**Comment by smjenness** [comment]
@krivit : any chance you could work on this for EpiModel/MIDAS time in the next week? It is an important fix to address for EpiModel work. Thanks!

**Comment by krivit** [comment]
It turns out to be nontrivial to put a control parameter into that code path. It may make sense to use an `options()` style option instead.

Perhaps if it's set to disable hashing, we can use a random string instead, which will save time on some use cases.

**Comment by krivit** [comment]
A possible fix is in the `i474-state-hash-random` branch. Please test.

**Comment by AdrienLeGuillou** [comment]
Thanks @krivit,

with this branch I get similar results with [this code](https://github.com/EpiModel/EpiModelHIV-p/issues/120#issuecomment-1177568998) as I did with [this commit](https://github.com/statnet/ergm/commit/afbcbb0960c01b71956f91108faeb0d9d239f1c9). 
So it seems to fix it for me. 

I will run full simulations on the HPC with it to make sure .

**Comment by AdrienLeGuillou** [comment]
Everything seems as fast as before with this branch
