### ISSUE TITLE
option to bypass random GUID generation

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#482]
The stochasticity in GUID generation here

https://github.com/statnet/ergm/blob/a312661b3fcbd8b415821971456851894d5d85d1/R/parallel.utils.R#L494

changes the RNG state when calling the non-random functions `ergm_model`, `summary_formula`, `(t)ergm.godfather`, etc.  This breaks various tests in `tergm` and `EpiModel`.

Can we have a global option to skip this, as suggested in 

https://github.com/statnet/ergm/issues/474#issuecomment-1192418622

?

**Comment by krivit** [comment]
I'd rather switch to something deterministic, e.g., time with fractions of a second, PID, and a globally incrementing counter.

**Comment by chad-klumb** [comment]
That should be fine.
