### ISSUE TITLE
Do we need to Suggest: Rmpi?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#487]
It's a hassle to install on some systems, and we don't actually have any particular accommodations or tests for it, since we access it through the standard `parallel` package API.

**Comment by handcock** [comment]
I suggest getting rid of it. I find the "PSOCK" is adequate for most UNIX-like systems in addition to working on Windows. MPI has become more fragile on UNIX-like systems over time and, at this point, is very much a specialist choice for ergm users.

**Comment by krivit** [comment]
On deeper look, we do have an MPI test, though its disabled unless a special setting is enabled. However, since package code doesn't actually handle MPI any differently from other parallel APIs, there isn't really a point to keeping that test either.
