### ISSUE TITLE
Improve san() help page

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#488]
What do you think about improving the man page of `san()` by extending the Details part with the, possibly adopted, copypaste of section 4 of [Krivitsky, P. N., Hunter, D. R., Morris, M., & Klumb, C. (2022). ergm 4: Computational Improvements. arXiv preprint arXiv:2203.08198.](https://arxiv.org/abs/2203.08198)? Perhaps then it will be more helpful in detailing what the function does.

**Comment by krivit** [comment]
I think it would be great!

**Comment by mbojan** [comment]
I think it should be good to go. CI fails with R-devel but for an unrelated reason.

**Comment by krivit** [comment]
@mbojan , looks like this has created a problem for manual building: https://github.com/statnet/ergm/actions/runs/3168552867/jobs/5159829523 . Can you please fix?

**Comment by mbojan** [comment]
Yep.
