### ISSUE TITLE
rlebdm() construction does not handle network sizes over 46340 (Was: Problem specifying ppopsize=50000)

### ISSUE THREAD

**Issue by netterie** [statnet/ergm#50]
@krivit @mbojan 

I am running into trouble using the ppopsize control, for larger sizes. Our desired size is 50K. I can run 45K but not 50K.

So, this works:
```r
data(faux.mesa.high)
fmh.ego <- as.egodata(faux.mesa.high)
fit <- ergm.ego(fmh.ego ~ edges, 
                         control=control.ergm.ego(ppopsize=45000))
```

But this throws the error below (I included some traceback, not sure if that helps):
```r
data(faux.mesa.high)
fmh.ego <- as.egodata(faux.mesa.high)
fit <- ergm.ego(fmh.ego ~ edges, 
                         control=control.ergm.ego(ppopsize=50000))
```
![image](https://user-images.githubusercontent.com/4825649/53272703-da82ff80-36a6-11e9-9b0f-29a5901dd58f.png)

@martinamorris @dth FYI

**Comment by krivit** [comment]
The problem is that 32-bit signed integers top out at 2147483647, and its square root is 46340.95, so, say
```
> 46340L*46340L
[1] 2147395600
> 46341L*46341L
[1] NA
Warning message:
In 46341L * 46341L : NAs produced by integer overflow
```

**Comment by mbojan** [comment]
Is this for `master` or `dev`?

**Comment by krivit** [comment]
@mbojan , confirmed for `master`, haven't checked for `dev`, but probably. Generally, `master` bugs go to the `statnet/ergm` repo, and `dev`-only bugs to `statnet/ergm-private` repo.

**Comment by mbojan** [comment]
@krivit `ergm@dev` + `ergm.ego` worked for me with `ppopsize=50000`: https://github.com/krivit/ergm.ego-papers/blob/master/sn-work/estimation/main-50k-cd.out  The model did not converge, but for other reasons.
