### ISSUE TITLE
Error with dependencies, MCMLE

### ISSUE THREAD

**Issue by dgzara** [statnet/ergm#510]
Hi all,

I tried to run an ergm with structural and edgecov terms. I didn't have trouble with prior versions of R (<4.2.2) and ergm (< 4.4). Now, I'm getting the following error.

I'm not sure why I'm getting `caught segfault` errors now. I'd appreciate any help. Thanks!

```
Starting maximum pseudolikelihood estimation (MPLE):
Evaluating the predictor and response matrix.
Maximizing the pseudolikelihood.
Finished MPLE.
Starting Monte Carlo maximum likelihood estimation (MCMLE):
Iteration 1 of at most 50:

 *** caught segfault ***
address 0x7fd04e835370, cause 'memory not mapped'

Traceback:
 1: ergm_MCMC_slave(state[[1]], burnin = burnin, samplesize = samplesize,     interval = interval, eta = eta, control = control.parallel,     verbose = verbose, ...)
 2: doruns(burnin = interval, samplesize = samplesize, interval = interval)
 3: ergm_MCMC_sample(s, control, theta = mcmc.init, verbose = max(verbose -     1, 0))
 4: ergm.MCMLE(init, nw, model, initialfit = (initialfit <- NULL),     control = control, proposal = proposal, proposal.obs = proposal.obs,     verbose = verbose, ...)
 5: ergm(as.formula(paste0("g ~ ", ergm.formula)), constraints = ~blockdiag("project_id"),     control = control.ergms, eval.loglik = F)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

Here is my session info
```
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rglpk_0.6-4    slam_0.1-50    ergm_4.4.0     network_1.18.1

loaded via a namespace (and not attached):
 [1] lpSolveAPI_5.5.2.0-17.9 magrittr_2.0.3          MASS_7.3-58.1           lattice_0.20-45         rlang_1.0.6             fastmap_1.1.0           fansi_1.0.4             tools_4.2.2             rbibutils_2.2.13        parallel_4.2.2         
[11] grid_4.2.2              rle_0.9.2               utf8_1.2.3              cli_3.6.0               coda_0.19-4             tibble_3.1.8            lifecycle_1.0.3         Matrix_1.5-1            purrr_1.0.1             vctrs_0.5.2            
[21] Rdpack_2.4              trust_0.1-8             robustbase_0.95-0       memoise_2.0.1           glue_1.6.2              cachem_1.0.6            statnet.common_4.8.0    DEoptimR_1.0-11         compiler_4.2.2          pillar_1.8.1           
[31] pkgconfig_2.0.3  
```

**Comment by mbojan** [comment]
Thanks @dgzara for reporting. Please provide a **reproducible example** that includes the offending call to `ergm()` together with (perhaps artificial) data that we can use to trace the problem. Otherwise it is difficult to investigate.

**Comment by dgzara** [comment]
Thanks, @mbojan. Here is the code I'm running. I can send you the dataset if needed.

I believe the error comes from the solver. I ran the same R script in a cluster from my university and the MCMC works. It runs and I get this message instead:

`Warning: ‘glpk’ selected as the solver, but package ‘Rglpk’ is not available; falling back to ‘lpSolveAPI’. This should be fine unless the sample size and/or the number of parameters is very big.
`

`##################################################
## Project: MDT Analysis
## Script purpose: Survey Analysis
## Date: 2019-01-25
## Author: Diego Zara dgomezara@u.northwestern.edu
##################################################

#folder <- getwd()
folder <- "/Users/dgomezara/Dropbox (SONIC)/SONIC-Gomez-Zara/MDT_Diego/Scripts/mdt_2023_misq/"
setwd(folder)
set.seed(42)
rm(list = ls()) 

# Library -----------------------------------------------------------------
library(ergm)

# Load datasets -----------------------------------------------------------
invitations <- read.csv("data/invitations.csv", sep = ",", stringsAsFactors = F)
relationships <- read.csv("data/relationships.csv", sep = ",", stringsAsFactors = F)
user.profiles <- read.csv("data/user.profiles.csv", sep = ",", stringsAsFactors = F)
ranking <- read.csv("data/ranking_top10.csv", sep = ",", stringsAsFactors = F)

# Variables ---------------------------------------------------------------

# Remove duplicates
invitations <- invitations[!duplicated(invitations[,c("project_id","sender","recipient")]), ]
relationships <- relationships[!duplicated(relationships),]
user.profiles <- user.profiles[!duplicated(user.profiles$user_id), ]
ranking <- ranking[!duplicated(ranking),]

invitations <- invitations[order(invitations$project_id),]
user.profiles <- user.profiles[order(user.profiles$project_id),]
relationships <- relationships[order(relationships$type, relationships$project_id),]

rownames(invitations) <- NULL
rownames(user.profiles) <- NULL
rownames(relationships) <- NULL
rownames(ranking) <- NULL

# Remove users without info
invitations <- invitations[(invitations$sender %in% user.profiles$user_id),]
invitations <- invitations[(invitations$recipient %in% user.profiles$user_id),]
relationships <- relationships[(relationships$source %in% user.profiles$user_id),]
relationships <- relationships[(relationships$target %in% user.profiles$user_id),]
ranking <- ranking[(ranking$sender %in% user.profiles$user_id),]
ranking <- ranking[(ranking$recommended %in% user.profiles$user_id),]

# Keep certain projects  
projects <- c(11, 91, 92, 101, 120, 131, 133, 136, 221, 6, 10, 15, 18, 19, 25)
invitations <- invitations[invitations$project_id %in% projects, ]
relationships <- relationships[relationships$project_id %in% projects, ]
user.profiles <- user.profiles[user.profiles$project_id %in% projects, ]
ranking <- ranking[ranking$project_id %in% projects, ]

# Fix rankings
ranking$top10 <- apply(ranking, 1, function(x) {ifelse(as.numeric(x["rank"]) <= 10, 1, 0)})
ranking$top5 <- apply(ranking, 1, function(x) {ifelse(as.numeric(x["rank"]) <= 5, 1, 0)})
ranking$top3 <- apply(ranking, 1, function(x) {ifelse(as.numeric(x["rank"]) <= 3, 1, 0)})

# Fix the age
user.profiles$age <- as.numeric(user.profiles$age)
user.profiles$age[(is.na(user.profiles$age) | user.profiles$age < 18)] <- 18

# Declare international NA as 0
user.profiles$international[(is.na(user.profiles$international))] <- 0

# Replace project.skill.score with averages
user.profiles$project.skill.score[(is.na(user.profiles$project.skill.score))] <- mean(user.profiles$project.skill.score[!is.na(user.profiles$project.skill.score)])

# Remove invitations without rank
#invitations <- invitations[!is.na(invitations$rank), ]

# Invitations: create loop interactions
for(p in projects){
  users.project <- user.profiles$user_id[(user.profiles$project_id == p)]
  invitations <- rbind(invitations, data.frame(project_id = p, 
                                               sent_at = NA, 
                                               replied_at = NA,
                                               sender = users.project, 
                                               recipient = users.project,
                                               status="FK", 
                                               recommendation_id = NA,
                                               rank = NA))
  rm(users.project)
}
invitations <- invitations[order(invitations$project_id),]

# Prior relationships: create loop interactions
for(p in unique(relationships$project_id)){
  for(t in unique(relationships$type)){
    unused_ids <- setdiff(user.profiles$user_id[user.profiles$project_id == p], 
                          union(relationships$source[relationships$project_id == p & relationships$type == t], 
                                relationships$target[relationships$project_id == p & relationships$type == t]))
    if(length(unused_ids) > 0){
      relationships <- rbind(relationships, data.frame(project_id = p, type = t, source = unused_ids, target = unused_ids))
    }
  }
}
relationships <- relationships[order(relationships$project_id),]

# Data scale
traits.columns <- c("age", "project.skill.score", "leadership.score", "social.skills.score", "creativity.score", "personality.agreeableness.score",
             "personality.conscientiousness.score", "personality.extraversion.score", "personality.neuroticism.score", "personality.openness.score")

social.columns <- c("know.degree", "know.constraint", "know.betweenness", "know.closeness", "know.degree.squared",
                    "work.degree", "work.constraint", "work.betweenness", "work.closeness", "work.degree.squared",
                    "enjoy.degree", "enjoy.constraint", "enjoy.betweenness", "enjoy.closeness", "enjoy.degree.squared", 
                    "enjoy.work.degree", "enjoy.work.constraint", "enjoy.work.betweenness", "enjoy.work.closeness", "enjoy.work.degree.squared",
                    "weak.degree", "weak.constraint", "weak.betweenness", "weak.closeness", "weak.degree.squared", 
                    "strong.degree", "strong.constraint", "strong.betweenness", "strong.closeness", "strong.degree.squared",
                    "know.no.work.degree", "know.no.work.constraint", "know.no.work.betweenness","know.no.work.closeness", "know.no.work.degree.squared")
  
# Check correlations
correlations.users <- cor(user.profiles[,c(traits.columns,social.columns)])

# Scale metrics
user.profiles[,c(traits.columns, social.columns)] <- scale(user.profiles[,c(traits.columns, social.columns)], center = F)

# Network creation --------------------------------------------------------

# Remove duplicates
el <- invitations[,c("project_id","sender","recipient")]
test_el <- t(apply(el, 1L, sort))
el <- el[which(!duplicated(test_el)),]

# Create network (accepted (AC), rejected (RJ), invited (IN), rejected & invited (NEG), or all)
g <- network(el[,c("sender","recipient")], directed=T, matrix.type = "edgelist", loops = T)

# Remove the loops
g1 <- as.matrix(g)
diag(g1) <- 0
g <- network(g1)
rm(g1)

# Print the network
print(g)
#plot(g)

# Get the vertex list
users.invitations <- data.frame(id=get.vertex.attribute(g, "vertex.names"), stringsAsFactors = F)
users.invitations <- merge(users.invitations, user.profiles, by.x = c("id"), by.y=c("user_id"), all.x = T, all.y = F, sort = F)

# Factor attributes
users.invitations$gender <- as.numeric(as.factor(users.invitations$gender))     # 1: female, 2: male
users.invitations$international <- as.numeric(users.invitations$international)  # 0: US, 1: international 

# Set attributes
for (i in 2:ncol(users.invitations)) {
  set.vertex.attribute(g, colnames(users.invitations)[i], users.invitations[, i])
}

# Set relationship networks
for(i in unique(relationships$type)){
  el <- relationships[(relationships$type == i), c("source", "target")]
  test_el <- t(apply(el, 1L, sort))
  el <- el[which(!duplicated(test_el)),]
  el <- el[el$source != el$target,]
  assign(paste0("network.",i), network(el, loops = F, directed=F, matrix.type = "edgelist"))
}

# Create the ranking network
network.ranking <- network(ranking[ranking$top5==1,c("sender","recommended")], directed=T, matrix.type = "edgelist", loops = F)

# Creation of filtered networks
g.AC <- g
g.RJ <- g
g.IG <- g

list.status <- get.edge.value(g, "status")
delete.edges(g.AC, which(list.status %in% c("RJ","IN","RV","FK")))
delete.edges(g.RJ, which(list.status %in% c("AC","IN","RV","FK")))
delete.edges(g.IG, which(list.status %in% c("AC","RJ","FK")))

# Plot --------------------------------------------------------------------
png(file = paste0("plots/graph.png"), width = 1820, height = 1820, units = "px", bg = "transparent", res=150)
plot(g, vertex.col = as.numeric(as.factor(get.vertex.attribute(g, "project_id")))+1)
dev.off()

# ERGM --------------------------------------------------------------------
decay <- 0.1

# ERGM Controls
control.ergms <- control.ergm(MCMC.burnin=10000,
                              MCMC.samplesize = 2500,
                              MCMC.interval = 10000,
                              MCMLE.maxit = 50,
                              seed=10)

# Formula
ergm.formula <- 'edges + 
               gwidegree(decay, fixed=T) + 
               gwodegree(decay, fixed=T) + 
               dgwnsp(decay, fixed=T) + 
               dgwesp(decay, fixed=T) + 
               edgecov(network.weak) + 
               edgecov(network.work.no.enjoy) + 
               edgecov(network.enjoy.work) + 
               nodeifactor("international") + 
               nodeifactor("gender") +
               nodeicov("age") +
               nodeicov("project.skill.score") +
               nodeicov("weak.degree") + 
               nodeicov("work.no.enjoy.degree") + 
               nodeicov("enjoy.work.degree") + 
               nodeofactor("international") + 
               nodeofactor("gender") +
               nodeocov("age") +
               nodeocov("project.skill.score") +
               nodeocov("weak.degree") + 
               nodeocov("work.no.enjoy.degree") +
               nodeocov("enjoy.work.degree") +
               nodematch("international") + 
               nodematch("gender")'

# Print model
print(ergm.formula)

# Model
ergm <- ergm(as.formula(paste0("g ~ ",ergm.formula)),
             constraints=~blockdiag("project_id"),
             control = control.ergms,
             eval.loglik = F)
`

**Comment by dgzara** [comment]
I created the ERGM, saved the Rdata, and used those objects to continue the script in my computer.
Still, I'm getting the error coming from `summary.ergm_state(state)`

` *** caught segfault ***
address 0x7f8cac2a6ae8, cause 'memory not mapped'

Traceback:
 1: summary.ergm_state(state)
 2: summary(state)
 3: summary.ergm_model(m, nw, term.options = control$term.options)
 4: summary(m, nw, term.options = control$term.options)
 5: simulate.ergm_model(m, nsim = nsim, seed = seed, coef = coef,     constraints = proposal, monitor = mon.m, basis = nw, esteq = esteq,     output = output, simplify = simplify, sequential = sequential,     control = control, verbose = verbose, return.args = return.args,     ...)
 6: simulate(m, nsim = nsim, seed = seed, coef = coef, constraints = proposal,     monitor = mon.m, basis = nw, esteq = esteq, output = output,     simplify = simplify, sequential = sequential, control = control,     verbose = verbose, return.args = return.args, ...)
 7: simulate_formula.network(object, nsim = nsim, seed = seed, ...,     basis = attr(object, ".Basis"))
 8: simulate_formula(object, nsim = nsim, seed = seed, ..., basis = attr(object,     ".Basis"))
 9: simulate.formula_lhs_network(object = g ~ edges + gwidegree(decay,     fixed = T) + gwodegree(decay, fixed = T) + edgecov(network.work.no.enjoy) +     edgecov(network.enjoy.work) + edgecov(network.ranking, "ranking"),     nsim = nsim, seed = seed, coef = coef, response = response,     reference = reference, esteq = esteq, sequential = sequential,     constraints = constraints, observational = observational,     monitor = monitor, output = output, simplify = simplify,     control = control, verbose = verbose)
10: stats::simulate(object = g ~ edges + gwidegree(decay, fixed = T) +     gwodegree(decay, fixed = T) + edgecov(network.work.no.enjoy) +     edgecov(network.enjoy.work) + edgecov(network.ranking, "ranking"),     nsim = nsim, seed = seed, coef = coef, response = response,     reference = reference, esteq = esteq, sequential = sequential,     constraints = constraints, observational = observational,     monitor = monitor, output = output, simplify = simplify,     control = control, verbose = verbose)
11: eval(cl, parent.frame())
12: eval(cl, parent.frame())
13: simulate.formula(object$formula, nsim = nsim, coef = coef, response = response,     reference = reference, esteq = esteq, sequential = sequential,     constraints = constraints, observational = observational,     monitor = monitor, basis = basis, output = output, simplify = simplify,     control = control, verbose = verbose, seed = seed, ...)
14: simulate(object$formula, nsim = nsim, coef = coef, response = response,     reference = reference, esteq = esteq, sequential = sequential,     constraints = constraints, observational = observational,     monitor = monitor, basis = basis, output = output, simplify = simplify,     control = control, verbose = verbose, seed = seed, ...)
15: simulate.ergm(mod.1, nsim = 100, verbose = T)
16: simulate(mod.1, nsim = 100, verbose = T)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace`

**Comment by mbojan** [comment]
Thanks @dgzara . 

The message about **Rglpk** is benign, but you may want to install it because it is preferred in general to the fallback **lpSolveAPI**. 

So to summarize: your estimation code failed with segafult on your personal computer but completed  succesfully on a different compuer (cluster)? Then you wanted to simulate from the estimated model on your personal computer and this, again, resulted with a segfault. Is that correct?

**Comment by mbojan** [comment]
My hypotheses so far:

- Something is wrong with R and/or package compilation/installation on @dgzara personal computer
- `network_stats_wrapper()` mismanages memory on some OSes or architectures

CC @krivit

**Comment by krivit** [comment]
Without a working example, I can't really speculate.

**Comment by martinamorris** [comment]
Maybe a clean install of R and packages would be a good idea?

**Comment by krivit** [comment]
Since there hasn't been any word from the reporter, I assume this was resolved. If not, please reopen.
