### ISSUE TITLE
In control.ergm(SA.*) parameters, set defaults, including functional ones

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#511]
Currently, many of the `control.ergm()`'s `SA.*` arguments are set to `NULL` and substituted in `ergm.stocapprox()` .

Instead, they should be set to the defaults there. Where they are specific to the model or similar, they should be functions along the lines of `init.MPLE.samplesize=`.

**Comment by krivit** [comment]
Also, in the controls set by `ergm.stocapprox()`, use more descriptive names. For example, there is no reason to replace `SA.nsubphases` with `nsub` as it currently does.

**Comment by AryaKarami** [comment]
In the stoch.approx(), Is the argument "s.obs" related to the missing data? Why does it use !is.null(s.obs) ?

**Comment by krivit** [comment]
`s.obs` is an `ergm_state` object that is only non-`NULL` if there is a missing data process. It's passed because missing data support for SA is on the roadmap.
