### ISSUE TITLE
error with `init.method = "zeros"`

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#516]
When running

```
require(ergm)
nw <- network.initialize(10, directed = FALSE)
e <- ergm(nw ~ edges, target.stats = 10, control = list(init.method = "zeros"))
```

with `ergm@master` I get the error

```
Error in structure(mple.lik, vcov = 0) : object 'mple.lik' not found
```

apparently coming from this line:

https://github.com/statnet/ergm/blob/8eeb514f81b9a72113a5492341bf303169df3f50/R/logLik.ergm.R#L110

**Comment by krivit** [comment]
Looks like a regression from the refactor of `ergm()`. Will fix.
