### ISSUE TITLE
documentation for nodefactor doesn't explain the "levels" argument

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#53]
also true for nodeifactor and nodeofactor

**Comment by krivit** [comment]
It's in the "Nodal attribute levels" section. Also, we'll probably update this as we port more terms to the new "API".

**Comment by krivit** [comment]
It sounds from our conversation that we need to rewrite this documentation to make it more clear.

**Comment by martinamorris** [comment]
I'll see if I can do that, working with Chad.

**Comment by krivit** [comment]
Is this satisfactory now?

**Comment by martinamorris** [comment]
The ergm-terms.rd file has this:

https://github.com/statnet/ergm/blob/7fc9393d1bf659ee68175c46d7d35d0cb07b48f9/man/ergm-terms.Rd#L219-L225

note, the first line is from the discussion of Covariate transforms.

1. Can you still use the old version of "levels" if you invoke version 3.9?
2. Did we decide that you can use either levels, or {keep, base} in 3.10, but not both?

either way, i think the doc needs to be more explicit.  happy to write it, if i know what to write.

**Comment by krivit** [comment]
Is this one good now?

**Comment by martinamorris** [comment]
Yes, it looks great.  Nice work Chad.

**Comment by sgoodreau** [comment]
Nice!
