### ISSUE TITLE
Enabling the constraint combination: blockdiag("gid")+edges

### ISSUE THREAD

**Issue by benrosche** [statnet/ergm#538]
~ Feature request ~

Dear Pavel / ergm developers,

As discussed at Sunbelt 2023, I would like to request the following constraint combination:

`ergm(..., constraints=~blockdiag("gid")+edges)`  or
`ergm(..., constraints=~blockdiag("gid")+(o)degrees )`

to model multiple networks while keeping the overall number of edges constant.

When using ergms to simulate networks, keeping the number of edges constant is often necessary to draw valid comparisons between network states. When modeling multiple networks, this is currently only possible with the following hack:

`ergm(g~... + offset(F(~edges, ~!nodematch("gid"))), offset.coef=-Inf, constraints=~edges)`

ergm.multi does not solve this problem because

`ergm(Networks(gs) ~... , constraints=~edges)`

is not possible either.

Thank you very much and best wishes,

Ben Rosche

**Comment by krivit** [comment]
Thanks for the request. I am currently testing a proposal that will do that, but I want to check something: do you want to constrain the number of edges overall or *within each block*? The former should be in `master` tonight, but the latter is a taller order.

**Comment by benrosche** [comment]
Hi Pavel,
I'd be happy with either. Within blocks would be great to have at some
point but it's not urgent.
Thank you so much! I'll update the package tomorrow then!
Ben

Benjamin Rosche
PhD candidate in Sociology at Cornell University
benrosche.com

**Comment by krivit** [comment]
Merged in in add1887606fb3f2dd78465f59b0a8de554804e58 (for full-network edge constraint).

**Comment by benrosche** [comment]
Dear Pavel / ergm developers,
I tried implementing the new constraint combination `ergm(...,constraints=~blockdiag("gid")+edges)` now with actual (larger) data. Unfortunately, the RStudio crashes when model parameters need to be fitted as soon as I add `+edges` (both with CD and MLE algorithms). Simulating networks with `ergm(...,constraints=~blockdiag("gid")+edges)` works, however. Fitting a model with the constraint combination produces the following [error message](https://we.tl/t-XHnzaf6Bfy). Alas, I cannot provide a reproducible example because the data I'm using (Add Health) is on a secured server. I wonder whether you have come across this error message before and whether this could be due to the ergm package or more likely due to the server I'm working on.

**Comment by benrosche** [comment]
Dear Pavel,

I wanted to follow up one more time regarding the new constraint combination `ergm(...,constraints=~blockdiag("gid")+edges)`.

Unfortunately, R crashes when both `blockdiag()` and `edges` are specified. This happens regardless of whether an ergm model is fitted using the ergm function or networks are simulated using the simulate function.

This code reproduces the error:

```
library(dplyr)
library(igraph)
library(intergraph)
library(ergm)

nd <- read.csv(file="nd.txt") %>% relocate(id)
ed <- read.csv(file="ed.txt") %>% relocate(id_from, id_to)

g <- 
  graph_from_data_frame(
    d=ed, 
    vertices=nd, 
    directed = T
  ) %>% 
  asNetwork(., multiple=F) 

g.ergm <- 
  ergm(
    g ~
      edges+mutual,
    estimate="MLE", 
    constraints=~blockdiag("gid")+edges,
    control=control.ergm(
      seed=1,
      MCMLE.maxit = 20
    ))
```

The data files can be downloaded [here](http://benrosche.com/wp-content/uploads/2023/ed.txt).

**Comment by benrosche** [comment]
I appreciate it.

Any chance you could enable this feature for ergm.multi? When using the
edges (or (o)degrees) constraint with ergm.multi, it responds that
blockdiag + edges is not supported.

Thank you,

Benjamin Rosche
PhD candidate in Sociology at Cornell University
benrosche.com

**Comment by krivit** [comment]
> I appreciate it. Any chance you could enable this feature for ergm.multi? When using the edges (or (o)degrees) constraint with ergm.multi, it responds that blockdiag + edges is not supported.

Odd. Can I trouble you to please open a new ticket with test code?

**Comment by benrosche** [comment]
I tried to replicate the error just now and ergm.multi with constraint=~edges works. My bad!
