### ISSUE TITLE
Shouldn't argument to getOption be quoted

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#54]
here: https://github.com/statnet/ergm-private/blob/790afe02397055239451dd4e6d85f44b94f13235/R/logLik.ergm.R#L194

After updating the package to 4.0-4834 I see in the logs (trial run with 1 iteration):

```
(yaddayadda)
Optimizing with step length 0.418084281310255.
Using lognormal metric (see control.ergm function).
Using log-normal approx (no optim)
Starting MCMC s.e. computation.
The log-likelihood improved by 4.107.
Estimating equations are not within tolerance region.
MCMLE estimation did not converge after 1 iterations. The estimated coefficients may not be accurate. Estimation may be resumed by passing the coefficients as initial v
alues; see 'init' under ?control.ergm for details.
Finished MCMLE.
Stopping the running cluster.
Error in getOption(ergm.loglik.warn_dyads) : 
  object 'ergm.loglik.warn_dyads' not found
```

**Comment by mbojan** [comment]
@krivit I fixed your fix of this issue and committed to `master`. I'll merge it with `dev` too. I see you are also merging with `3.10`. Everything from `master` should be merged into that too?

**Comment by mbojan** [comment]
Ha, I can't (no write access). I'll make a PR.

**Comment by krivit** [comment]
The problem was that I was using inconsistent case for the option name (`logLik` in one place, `loglik` in another).

**Comment by mbojan** [comment]
I think the problem was that if the option was not set at all then the if
expression was NULL && (TRUE or FALSE) which is invalid. PR is submitted.

**Comment by krivit** [comment]
The default options are set on loading in `.onLoad()` in `zzz.R`. I had used `logLik` and `loglik` inconsistently, so the the option was not being set.

I have now also rewritten that code to avoid clobbering options if the had been set prior to `ergm` being loaded.

**Comment by mbojan** [comment]
ah, ok. I was not aware of that.
