### ISSUE TITLE
How should SMALLEST(), LARGEST(), and COLLAPSE_SMALLEST() handle ties?

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#545]
This is stemming from an issue reported by #544 reported by @benrosche.

Suppose that in the attribute of interest, there is an exact tie in the frequency of the values. Sometimes, it won't have any effect, and sometimes, it will. For example, if the frequencies are, in descending order, 100, 90, 90, 80, etc., then `LARGEST` and `LARGEST(1)` won't be affected but `LARGEST(2)` will be.

Currently, the tie-breaking is arbitrary. It would probably be better to detect ties when they affect the result. What should the code do?

1. Warn and break ties arbitrarily.
2. Stop with an error, insisting the user remove ambiguity.

I am leaning towards the second. Any thoughts? @martinamorris , @mbojan , @drh20drh20 , @handcock , @CarterButts , @sgoodreau ?

**Comment by martinamorris** [comment]
How would a user remove ambiguity?   If it's straightforward, then an
informative message with example or link to syntax would be ideal.

**Comment by krivit** [comment]
> How would a user remove ambiguity?  

Either specify the categories manually or increase or decrease the argument to either include all of the tied categories or none.

> If it's straightforward, then an informative message with example or link to syntax would be ideal.

Should the message be in the form of a warning or an error, though?

**Comment by martinamorris** [comment]
I like @Michał Bojanowski ***@***.***> 's idea.  If
there's a standard R default to ordering in the presence of ties, use that,
with a warning (not an error) and a pointer to the syntax for manual
collapsing.

**Comment by krivit** [comment]
For this type of tiebreaker, there's lexicographic order (i.e., "a" comes before "b"), and there is order in the nodal attribute list. There is an argument for either. (We default to lexicographic for factor levels, for example.)

**Comment by drh20drh20** [comment]
I'm with @mbojan and @martinamorris .  In particular, I do not like the idea of an error, as this does not technically seem like an error.  Indeed, a warning message is a kindness here.

**Comment by krivit** [comment]
OK, I'll see about implementing a lexicographic tie breaker.
