### ISSUE TITLE
Using an offset together with the Godambe information for the MPLE does not work

### ISSUE THREAD

**Issue by corneliusfritz** [statnet/ergm#561]
Using an offset in an ergm specification while wanting to use the Godambe information for the MPLE does currently not work. Here is a small sample script to showcase it: 

```r
data(molecule)
gest <- ergm(molecule ~ offset(edges)+ triangle ,
             offset.coef = -1, estimate = "MPLE", 
             control = control.ergm(MPLE.covariance.method = "Godambe"))
```

The reason must lie in the `ergm_mplecov` function, where the offset term is included in the `net.stat` matrix (which are the statistics of the simulated network), but not in the matrix of change statistics (`pl$xmat`). The code wants to equate the column names, which then leads to the aforementioned error. The easiest fix might be to exclude the offset term from the statistics, as the uncertainty quantification does not relate to it. I, however, do not know if this leads to downstream problems ...

**Comment by krivit** [comment]
Thanks, @mbojan!
