### ISSUE TITLE
Dropped terms appear to result in the estimated log-likelihood being NaN.

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#573]
``` r
library(ergm)
data(faux.mesa.high)
fit <- ergm(faux.mesa.high~edges+nodefactor("Grade")+nodefactor("Race")+nodematch("Grade", diff=T)+nodematch("Race", diff=T)+gwesp(0.25, fixed=T), control=snctrl(MCMLE.maxit=2))
logLik(fit)
#> 'log Lik.' NaN (df=20)
```

<sup>Created on 2024-07-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by krivit** [comment]
The problem appears to be in the dyad-independent submodel estimation: it's run with `drop=FALSE`, so it produces large but finite estimators---but if they then get bridged to infinite ones, that can create a problem.

**Comment by krivit** [comment]
@martinamorris , this problem has more moving parts than I thought. I might not be able to fix it tonight.

**Comment by martinamorris** [comment]
As always @krivit you rock!

**Comment by martinamorris** [comment]
@krivit how can I verify I have the most recent version built/loaded locally?  it doesn't look like the DESCRIPTION file updates the version for every commit

**Comment by martinamorris** [comment]
@mbojan THANKS.  

is there a way to verify the Runiverse version also, without installing/loading it?

**Comment by martinamorris** [comment]
@mbojan NM -- the sha is published at the bottom of the Runiverse package description.

and the great news is, the current binaries incorporate Pavel's most recent updates! 

@smjenness [check it out](https://statnet.r-universe.dev/ergm).  It is just an awesome hosting site.
