### ISSUE TITLE
should check.ErgmTerm do more checking?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#59]
Currently, check.ErgmTerm does not check that all required arguments were passed (instead, it checks that the number of arguments passed was at least as big as the number of required arguments), and does not check that no argument was passed more than once.  I think the former should generate an (informative) error message, and the latter at least a warning.  Both of these could be checked for with the information currently passed to check.ErgmTerm (i.e. we wouldn't need to rewrite all the check.ErgmTerm calls, we'd just need to add a few lines to check.ErgmTerm itself).

**Comment by krivit** [comment]
Ideally, the error messages should be formatted in the same way as they would be in a function call, even though terms are not, of course, function calls. What are the corresponding error messages for those?

**Comment by chad-klumb** [comment]
the improvements suggested above were implemented in 415c4ae

additional functionality to check for deprecated term arguments was added in 16913fab470ecfc5bdce0fa0540cf227d57375cc, expanded in 100c16b87f994fd79af937188a8f4f0cf30aa1b3, and tweaked for greater consistency in f1e87a3ef5ca9dff092bed361a5ac3ec91d5f115
