### ISSUE TITLE
Towards predict.ergm()

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm#6]
I wrote a function that calculates conditional tie probabilities for a given model `fit` and a network object `net` by:

1. Extracting model formula from `fit`
2. Calculating observed sufficient statistics for `net`
3. For all dyads in `net` 
    a. toggle the dyad
    b. calculate sufficient stats after toggle
    c. calculate change stats (2)-(3b) or (3b)-(2) depending if the toggle created the tie or removed it
    d. compute expit based on changestats (c)

I used `fix.curved()` on (1) if `is.curved(fit)` to be able to compute sufficient statistics for curved ERGMs in (2) and (3b).

Would that be correct? Seems to be working fine for some simple ERGMs I tried.

**Comment by krivit** [comment]
Do you have a branch of this anywhere?

Anyway, I would recommend against the `fix.curved()` approach. Rather, change stats should be multiplied by `ergm.eta(coef, model$etamap)` to obtain predicted probabilities.

**Comment by mbojan** [comment]
> Do you have a branch of this anywhere?

Standby

> Anyway, I would recommend against the fix.curved() approach. Rather, change stats should be multiplied by ergm.eta(coef, model$etamap) to obtain predicted probabilities.

OK, I'll fix that.

**Comment by mbojan** [comment]
I pushed a branch on my fork.

It has just a function (no man or NAMESPACE export) because for some reason C compilation stopped working on my Windows machine....

**Comment by krivit** [comment]
Thanks. Can you make a pull request?

**Comment by mbojan** [comment]
Onto `master`? Actually maybe I'll simply push a new branch to public `ergm`?

**Comment by krivit** [comment]
Yes. From what you're describing, it sounds like it should go into `master`. I think there's a way to make it possible for us to work on the pull request cooperatively.

**Comment by krivit** [comment]
Thanks for the pull request.

**Comment by leifeld** [comment]
Hello,

Is this something like the `interpret` and `edgeprob` functions in the `btergm` package? See Section 6 of https://www.jstatsoft.org/article/view/v083i06.

**Comment by krivit** [comment]
I think so.

**Comment by krivit** [comment]
Closed with thanks to @mbojan .
