### ISSUE TITLE
Decide on the structure of a contributed user terms repository

### ISSUE THREAD

**Issue by sgoodreau** [statnet/ergm#62]
(Posting here since the repository(ies) being discussed don't exist yet).

After many years of discussing this, the time has come to set up a GitHub repository for user-contributed terms.

Dave and I had a call today to start brushing the dust off the ergm-userterms workshop, and in the process started this conversation as well.  In doing so, I realized that I have long conflated the current ergm-userterms package with this new repository.  They serve related, but distinct purposes.  The ergm-userterms package is currently a "lean and mean" package whose primary aim is to serve as a template to help people learn to write their own terms; it is currently on CRAN.  The purpose of this contributed user terms repository would be to include all of the different terms that users wish to share through the years.  As such, it could in theory get large with time. It also needs to be on Github since it will rely heavily on pull request functionality (but could of course also be pushed to CRAN at regular or irregular intervals).

So we saw at least three ways of organizing things:

1 All in one.  The ergm-userterms package is also the place that users push their terms to.  The benefit here is that the current name of the package suggests this use.  The downsides are that the "lean and mean" nature could get lost.  Then again, anyone who wants to build their own terms automatically gets everyone else's contributed terms in the process, so has lots of examples to work from.  Development would occur on Github, and releases to CRAN would happen periodically.

2. Two separate entities.  Perhaps named "ergm_userterms" and "ergm_contributed_terms"or something like that. This keeps them distinct, since they serve two purposes.  And those who want the template don't have to deal with getting all these different terms they don't necessarily want.  Then again, those may be useful for them to practice from.  Downside is that "ergm_userterms" sounds like it contains the terms users have contributed, so users may get confused.  Plus is that we would more freedom to decide whether to keep all the terms people contribute on Github, or also post them to CRAN, with all its added complications.

3. Many entities. That is, "ergm-userterms" remains as is.  And then instead of one big repository, we allow users to create their own repositories with terms that all depend on "ergm-userterms".  This means that users can choose to only get the terms they want, and contributors have more visible contributions. It might also make the set of terms available more visible. I'm not sure how the whole pull request thing works in a case like this though. This approach might be especially useful if the contributions start getting voluminous, and if there are a set of users who each contribute many terms.

I had all along implicitly had approach 1 in my head.  Only when we started talking about it did I think of 2.  Dave suggested option 3.   

@martinamorris, @krivit, @smjenness, @chad-klumb: Discuss.

**Comment by smjenness** [comment]
I would vote for option 1. Just put the template code in separate R/C files, and clearly describe how to get started in the repository README. For options 2, I don't see how a separate package gives you more free to decide what to keep -- for both 1 and 2, you can decide to merge pull requests (or not). For option 3 (which is essentially what we have now), how does that make contributors more visible? You would not have pull requests if there is no merging of code back into a central repository.

**Comment by krivit** [comment]
To be clear, user terms packages do not need to depend on `ergm.userterms`, only on `ergm`.

**Comment by sgoodreau** [comment]
Re: @smjenness's question about option 2; I just meant that we could choose to keep ergmuserterms (the template package) on CRAN (where it already is), but then also have the contributed terms only on github if we wanted.  Since I keep hearing about how awful it is to post things on CRAN, I thought that might have some value, especially since the contributed terms will be coming from different authors outside the group.  But I'm probably overthinking it.

Anyone else have a preference?  So far we have 1.5 votes for option 1 (Sam and half of me) and 0.5 for option 2 (half of me).

**Comment by drh20drh20** [comment]
I see some merit in 2 only due to the potential CRAN woes, but in the end the confusion about the name ("ergm-userterms" does sound like the contributed terms) makes me vote for 1.  And I suppose even if CRAN does prove problematic, the github version of the package will always be totally up to date for people to use.

**Comment by martinamorris** [comment]
weird.  i voted for option 1 yesterday in a comment, but don't see it here now.

i see some value to enforcing CRAN dictates.  while it may feel like overkill to us sometimes, i think the goal is to keep the software engineering up to date and functional in this crowd-sourced ecosystem.

**Comment by handcock** [comment]
I vote for 1 with only very occasional updates to CRAN and the github 
version promoted via devtools installs.

**Comment by drh20drh20** [comment]
Me too.  I’m going to copy my comment here because now I’m curious whether this will show up in the comments on github.  Sorry for any spam that results.

I see some merit in 2 only due to the potential CRAN woes, but in the end the confusion about the name ("ergm-userterms" does sound like the contributed terms) makes me vote for 1. And I suppose even if CRAN does prove problematic, the github version of the package will always be totally up to date for people to use.

Dave

**Comment by sgoodreau** [comment]
Thanks very much all.  Sounds like 1 it is. I'll close this ticket, and we'll start on making it happen.

**Comment by krivit** [comment]
Just waking up in Australia, I have a strong preference for 2:
* Terms packages don't actually depend on `ergm.userterms` but on `ergm`, since `ergm` is the one with the header files and helper functions.
* Users should be able to load the terms in `ergm.contrib.terms` without loading the toy terms in `ergm.userterms`.
* Flooding `ergm.userterms` with extra terms and documentation will complicate the workflow of creating a package with custom terms, which was the original purpose of the package. Rather than copying the package contents, renaming, and modifying the term files, the user would now have to clean out all of the contributed terms as well (or risk them being loaded twice).

**Comment by martinamorris** [comment]
All good arguments, but then I really think we need to rename the ergm.userterms package, as the name will create confusion once we have a new package full of user contributed terms.

suggestion:

ergmterm.builder (for ergm.userterms) + ergmterm.contrib (for the new contributed terms)

**Comment by krivit** [comment]
Renaming a package---especially one with a JoSS paper attached to it---might not be practical.

`ergm.userterms` and `ergm.contribterms` or some similar distinction makes sense to me.

**Comment by drh20drh20** [comment]
I disagree but maybe I don’t understand.

> On Apr 17, 2019, at 6:28 PM, Pavel N. Krivitsky <notifications@github.com> wrote:
> 
> Just waking up in Australia, I have a strong preference for 2:
> 
> Terms packages don't actually depend on ergm.userterms but on ergm, since ergm is the one with the header files and helper functions.
So?

> Users should be able to load the terms in ergm.contrib.terms without loading the toy terms in ergm.userterms.
What difference does it make if they have to load these few extra terms?  By the same token, users have to load a bunch of terms they don’t need in ergm itself but we don’t raise an objection to that.

> Flooding ergm.userterms with extra terms and documentation will complicate the workflow of creating a package with custom terms, which was the original purpose of the package. Rather than copying the package contents, renaming, and modifying the term files, the user would now have to clean out all of the contributed terms as well (or risk them being loaded twice).
But if we use plan #2, won’t they have to copy the second package contents (ergm.contribterms or whatever) and do all the same stuff?

Sorry if I’m being obtuse.
Dave

**Comment by krivit** [comment]
@handcock , I think that one of the benefits of having a separate contributed terms package is that we can have frequent updates.

@drh20drh20 ,

> So?

It means that keeping the two separate won't lead to code duplication or additional dependencies.

> What difference does it make if they have to load these few extra terms?

It's a minor issue, granted.

> But if we use plan #2, won’t they have to copy the second package contents (ergm.contribterms or whatever) and do all the same stuff? 

Here's how I understand the workflow under Plan 2 to produce a minimal user terms package:

1. Download the source code for `ergm.userterms` from CRAN; don't actually install it.
2. Implement the terms.
3. Compile and install the package.

Here's how I understand it under Plan 1:

1. Download the source for `ergm.userterms` package source to a new directory. (Note that you probably have it installed as well.)
2. Rename the directory (to keep from getting confused); edit the `DESCRIPTION` file to change package name; and edit the `NAMESPACE` file to load the correct C library. (This is necessary to be able to both get updates of user-contributed terms from CRAN and keep them from installing over your user terms.)
3. Delete unwanted term files, C, and documentation files (but avoid deleting the files you need).
4. Implement the terms.
5. Compile and install the package.

**Comment by sgoodreau** [comment]
OK, we seem to be at a bit of an impasse.  Lots of folks expressed preferences for 1, but then Pavel made some novel points in making a strong case for option 2.  Do Pavel's latest points sway people?

On my end, I'm starting to see now how option 1 will lead to complicated requirements if one wants to both develop new terms and keep updating the package to get terms others contribute.  Although I have to admit I don't fully understand Step 3 in Pavel's previous comment (why do you need to delete anything?  Is it a big deal to have terms around you don't use?  After all that happens in regular ergm all the time.  Or am I missing some point?)

**Comment by krivit** [comment]
> why do you need to delete anything? Is it a big deal to have terms around you don't use?

If you have a term with the same name (and valuedness) implemented in multiple packages, it is not possible to predict which version will be used. This means that if your custom package retains contributed terms, and an update from CRAN comes through with modifications to those terms, `ergm` might grab your old version, the new version, or, worse yet, R code from one but C code from the other.

**Comment by sgoodreau** [comment]
So, it turns out that @mbojan actually set up a separate package called ergm.terms.contrib for us on github a few years ago.  (Thanks Michal!) How embarrasing that we all didn't know this :-)  Not only that, but it's had a pull request sitting on it for two years, from someone named matthewlhamilton.  Oops.

I'm not sure of the full decision-making process that led up to that at the time, but between that and @krivit's points in the thread above, it seems like sticking with this is definitely the way to go.  The name for ergm.userterms might be a bit confusing, but surely this isn't the first case of a name that turned out to be problematic later as functionality expanded.

I will close this, knowing you all can reopen if you have objections.

**Comment by drh20drh20** [comment]
In light of all this, I agree!  Thanks to Michal, Pavel, and Steve.
Dave

**Comment by martinamorris** [comment]
Just a bit of the history -- 

@skyebend was also instrumental in getting this set up, and iirc the contribution from Matt Hamilton (who I just met at OSU last week) triggered some kind of error.  Skye may have more of the details.  

this, of course, is the achilles heel of this whole approach.

i think it would be helpful to use Matt's contribution to work out the kinks in testing and publishing terms from this package.  if we want to get Matt back into the loop, i can do that (Pavel and I will be talking with him tomorrow).

**Comment by mbojan** [comment]
Apologies for joining the discussion late. Indeed, ergm.terms.contrib was setup by @skyebend containing terms contributed by Matt Hamilton, with me helping with some details only. 

With respect to @sgoodreau 's options my opinion is 3>2>1:

- have a template package for contributing terms that a user can take, rename, fill it with own code, submit to CRAN (or not), fix bugs, keep up to date with improving `ergm` API and so on
- optionally have `ergm.terms.contrib` as a statnet-maintained repo for terms contributed by users not able/willing to pursue item above all the way. The question is, if it is going to be statnet-maintained, why do we need it in the first place as we can just add these user-contributed terms to `ergm`...

**Comment by sgoodreau** [comment]
Thanks all.  I think picking back up on Matt's contribution is a great next step.  @martinamorris, did you end up talking with him about it last week?

And @mbojan, I hear your point about why we even need the `ergm.terms.contrib` package at all if it's going to be maintained by us -- why not just allow pull requests right into `ergm` itself?  I do agree with you that they provide equivalent functionality.  I think the value added is that more from a marketing perspective - it makes the option more readily visible. Perhaps we're over-estimating how much difference that will make, but I'm hoping it will.  we can of course always decide to roll it into `ergm` proper if it feels right to do so. So i'm inclined towards reinvigorating the status quo now. thanks to Pavel's and your arguments.
