### ISSUE TITLE
sociality() term with attributes

### ISSUE THREAD

**Issue by krivit** [statnet/ergm#64]
ERGM term `sociality()`---which calculates the degree sequence of the graph---seems to have arguments (`attr` and `levels`) that its directed analogues `sender()` and `receiver()` do not have (as of the 3.9.4 release). When given, it only counts relations that match on `attr`.

We should do one of two things:

1. Remove those arguments from `sociality()` to make it consistent with `sender()` and `receiver()` terms.
2. Add those arguments to `sender()` and `receiver()`.

Personally, I am in favour of Option 1, since this seems like obscure functionality that is likely to surprise the user, and that will be obviated by operator terms when 4.0 comes out.

@martinamorris , @sgoodreau , @handcock , @CarterButts , @drh20drh20 , are you aware of any prominent use cases?

**Comment by drh20drh20** [comment]
Why not choice 3, which is not worry about it? 
Not trying to be flippant, just not clear whether it’s worth effort if this functionality will be obviated when 4.0 comes out.  

Dave

**Comment by krivit** [comment]
* Code simplicity and maintainability.
* User interface consistency.
* Requiring nonstandard naming for some of the arguments.

**Comment by sgoodreau** [comment]
My guess is that that functionality was added when we were working on the Birds of a Feather paper, and that it probably hasn't been used by anyone since.  But of course I don't know for sure.

I still don't have much sense of the operator terms will work - you're sure that the entirety of the functionality of these optional arguments will be covered?

**Comment by martinamorris** [comment]
I'm happy with (1) as long as the operator terms replace the functionality.

**Comment by krivit** [comment]
An operator term will basically let you say "evaluate this statistic on a network constructed by taking the LHS network and deleting all ties not within a group".

**Comment by krivit** [comment]
I'll go ahead and deprecate them for now.
