### ISSUE TITLE
does term balance behave correctly when passed arguments?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#67]
Appears balance does not correctly handle arguments.  Despite some R code in InitErgmTerm.balance for dealing with them, the results of summary and ergm do not appear correct, so I'm guessing the C code is not handling the arguments correctly.  The arguments are not in the ergm-terms documentation, but they are in the code itself.

Assuming the premise is correct, should we remove the arguments or fix the C code (or do something else)?

Example (same behavior with CRAN or github master ergm):

> require(ergm)
> set.seed(234)
> nwu = network(200, directed = F, density = 0.1)
> nwd = network(200, directed = T, density = 0.1)
> cat1 = sample(letters[1:3], 200, replace = T)
> nwu %v% "cat1" <- cat1
> nwd %v% "cat1" <- cat1
> 
> summary(nwu ~ balance)
balance 
 328092 
> summary(nwu ~ balance("cat1"))
balance.cat1 
      328092 
> summary(nwu ~ balance("cat1", diff = T))
balance.cat1.a balance.cat1.b balance.cat1.c 
        328092              0              0 
> summary(nwu ~ balance("cat1", diff = T, levels = c("a", "c")))
balance.cat1.a balance.cat1.c 
        328092              0 
> 
> summary(nwd ~ balance)
balance 
  24927 
> summary(nwd ~ balance("cat1"))
balance.cat1 
       24927 
> summary(nwd ~ balance("cat1", diff = T))
balance.cat1.a balance.cat1.b balance.cat1.c 
         24927              0              0 
> summary(nwd ~ balance("cat1", diff = T, levels = c("a", "c")))
balance.cat1.a balance.cat1.c 
         24927              0

**Comment by krivit** [comment]
@handcock @CarterButts @drh20drh20 , what *is* that term supposed to do in the first place?

**Comment by drh20drh20** [comment]
I’m afraid I don't know.

**Comment by chad-klumb** [comment]
From the ergm-terms documentation:

    \item{\code{balance}  (binary)  (triad-related)  (directed)  (undirected)}{\emph{Balanced triads:} 
    This term adds one network statistic to the model equal to the number of
    triads in the network that are balanced. The balanced triads are those of
    type \code{102} or \code{300} in the categorization of Davis and Leinhardt (1972). For details on the 16 possible triad types, see
    \code{?triad.classify} in the \code{{sna}} package. For an undirected
    network, the balanced triads are those with an even number of ties (i.e., 0
    and 2).}

Based on the behavior of other terms, my expectation would be that passing (just) an attribute would result in one statistic equal to the number of balanced triads where all three nodes have the same value of the attribute, that passing an attribute with diff = TRUE would give one statistic for each value of the attribute (equal to the number of balanced triads where all three nodes have that value of the attribute), and that additionally specifying levels would give one such statistic for each level thus specified.
