### ISSUE TITLE
are InitErgmTerm.b1starmix and InitErgmTerm.b2starmix implemented correctly? (and what is the intended function of the levels argument?)

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#70]
Appears to me that InitErgmTerm.b1starmix and InitErgmTerm.b2starmix are not correctly implemented, at least as far as the levels argument goes.  It is also not clear to me what exactly this argument is supposed to specify, since it is not explained at all in the documentation; the terms appear in the ergm-terms documentation, and the argument levels is shown there, but its functionality is not explained.  Does it refer to levels of the b1 partition, the b2 partition, both, or is its interpretation supposed to depend on other arguments (such as diff)?

Currently this argument is applied equally to both the b1 part of nodecov and the b2 part of nodecov which makes me think it is somehow supposed to be a total specification of what levels to include from either bipartition.

However, restricting the levels with this argument, whether diff is T or F, results in strange behavior (such as quashing excluded categories together into a single NA category, and including that NA category in the model), and the R code itself performs a numerical recoding and subsequent processing that doesn't seem sensible to me (at least as far as how it treats categories not included in the levels argument).

(Updated example to use different categories for b1 and b2.)

As the examples below show, when dealing with b1starmix, omitting levels from b2 causes an increase in the number of homophilous stars for each of the b1 categories, as the omitted b2 categories are pooled together into a single (NA) category.  (There is no change in the counts when omitting the first category in b2, because as far as the counts are concerned, there's no difference between the original category and the new NA category it's placed into; the homophilous subsets of b2 are unchanged if we relabel a single category, but not if we pool multiple categories together, as subsequent omissions of b2 levels do.)

When omitting levels from b1, they are again pooled into a single NA category, which has total count equal to the sum of the counts of the pooled b1 categories.

```CODE```

> require(ergm)
> 
> set.seed(234)
> 
> nwb = network(125, directed = F, bipartite = 75, density = 0.1)
> 
> cat2 = c(sample(letters[1:3], 75, replace = T), sample(letters[4:6], 125, replace = T))
> 
> nwb %v% "cat2" <- cat2
> 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("a", "b", "c", "d", "e", "f")))
b1starmix.3.cat2.a b1starmix.3.cat2.b b1starmix.3.cat2.c 
               685                799                989 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("a", "b", "c", "d", "e")))
b1starmix.3.cat2.a b1starmix.3.cat2.b b1starmix.3.cat2.c 
               685                799                989 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("a", "b", "c", "d")))
b1starmix.3.cat2.a b1starmix.3.cat2.b b1starmix.3.cat2.c 
              2252               2029               2829 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("a", "b", "c")))
b1starmix.3.cat2.a b1starmix.3.cat2.b b1starmix.3.cat2.c 
              7188               6941               9659 
> 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("a", "b", "c", "d", "e", "f")))
b1starmix.3.cat2.a b1starmix.3.cat2.b b1starmix.3.cat2.c 
               685                799                989 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("b", "c", "d", "e", "f")))
 b1starmix.3.cat2.b  b1starmix.3.cat2.c b1starmix.3.cat2.NA 
                799                 989                 685 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("c", "d", "e", "f")))
 b1starmix.3.cat2.c b1starmix.3.cat2.NA 
                989                1484 
> summary(nwb ~ b1starmix(3, "cat2", 0, F, c("d", "e", "f")))
b1starmix.3.cat2.NA 
               2473

**Comment by chad-klumb** [comment]
It might make sense to use b1attr, b2attr, b1levels, and b2levels arguments here (as well as a levels2 argument).

Here's a proposed specification for how the term "should" work:

Specifying b1levels in b1starmix would only include statistics corresponding to stars with b1 node level in b1levels, and (I think this is reasonable) specifying b2levels would

(i) if diff is F, only count stars where the b2 nodes are homophilous on one of the levels in b2levels, and

(ii) if diff is T, only include statistics where the b2 nodes are homophilous on one of the levels in b2levels

levels2 could additionally be used to exclude specific statistics (this would be redundant with b1levels if diff is F but not if diff is T).

**Comment by sgoodreau** [comment]
First off, Chad thank you so much for looking so deeply into the behavior of the terms; this is great.

Before diving into the plan you lay out, I want to spend a moment thinking about the bigger picture.  Namely, is this a term anyone ever actually uses or is likely to use?  Do we know who first created it, and why?  The reason I ask is that star terms tend to be problematic (degeneracy and other issues), and can be mapped onto degree terms, which are generally much more stable.  So before investing more time getting this all to make sense, I wonder if it might be time to just jettison it.

As for what exactly to do if we do keep it - I started writing out three different sets of thoughts on your proposal, and then kept tying myself in mental knots, and ultimately realized that I have no idea what this term is supposed to do, or might reasonably be expected to do (as someone who himself generally avoids star terms).  Every time I thought I had it figured out I found more places that didn't make much sense. So I really don't have an answer!  Bringing us back to the same question as above.

**Comment by martinamorris** [comment]
I'll just note 2 things -- 

- this is a bipartite network, so @sgoodreau we're unlikely to be using these terms ourselves, but others might.  i don't have much intuition for how well- or poorly-behaved stars are in bipartitie nets.

- it's possible @handcock wrote these up originally; if so, there may be an application published with them.

**Comment by krivit** [comment]
Based on the commit history, they were added by @drh20drh20 . Dave?
