### ISSUE TITLE
levels = ALL argument?

### ISSUE THREAD

**Issue by martinamorris** [statnet/ergm#77]
> for levels=TRUE (or NULL, old base=0, are the words "TRUE" or "NULL"
> set by R, or is that something we can set?
>
> i ask b/c the most natural word to use from my perspective would be
> levels=ALL

TRUE isn't just a magic word. It does what it does because for any
vector or list x, x[TRUE] is identical to x, because TRUE gets recycled
to the length of x.

The "ALL" UI idea isn't bad, even if it pollutes the namespace
somewhat. There are two ways we can do that:
 * We could have ergm export a variable ALL that is set equal to TRUE.
   Then, we better hope that the end-user doesn't assign some other
   value to ALL.
 * We could do some nonstandard evaluation alchemy to have the term
   interpret ALL in a special way. This will deviate from the standard
   term structure and may be error-prone in other ways, but it will be
   safe if the user assigns some other value to ALL---unless, that is,
   they pass it to the levels= argument.

Might be worth raising an issue about this.

                        Best,
                        Pavel

**Comment by krivit** [comment]
From our phone conversation, a third option was to export a longer semantically meaningful variable, such as `ALL_LEVELS`.

**Comment by martinamorris** [comment]
Not a fan of `ALL_LEVELS`.

I'm more in favor of the alchemy

**Comment by krivit** [comment]
Frankly, I think that using `ALL` is overdoing it with user friendliness and is more trouble than it's worth.

If we want to, we can add to our tutorials a recommendation to just assign `ALL <- TRUE` first thing and go with that.

**Comment by martinamorris** [comment]
Ok, then I think we need explicit statements that levels=NULL is the one to use if you don't want to select, or de-select, any levels.

Worth a bit of user-friendliness...

**Comment by krivit** [comment]
How about now?

**Comment by martinamorris** [comment]
The one last issue is that we should use "NULL" consistently in the docs (except to note that TRUE is a synonym for NULL).

For example, here:
https://github.com/statnet/ergm/blob/0d6d597b176b9f81ae510915240feec1a7e74893/man/ergm-terms.Rd#L1416-L1440

**Comment by krivit** [comment]
@martinamorris, can you work with @chad-klumb to get it to a point where you are happy with it?

**Comment by krivit** [comment]
Two things:
1. I think that documentation should mention both `TRUE` and `NULL`. `TRUE` is, as far as I am concerned, the canonical form, while `NULL` is an alias for it vaguely translating to "no filtering".
2. Since `NULL` is now semantically meaningful *and* broadly advertised as such, whereas most of the rest of the time it's a placeholder, it's important to change the defaults for `levels` in both `InitErgmTerm`s and in the documentation to do whatever `base`/`keep` would do (i.e., typically the same value as `keep` and the negation of `base`). This would have been a problem when they were applied sequentially, but they no longer are.

**Comment by krivit** [comment]
Further to the above, and given the time constraints, I'm going to do the following:
1. In the code, default for `levels` will remain `NULL` so things continue working.
2. I will "abstract" it where appropriate, so that we could always change it later very quickly.
3. In the documentation, the defaults will be set to `-1` where `base=1`. This will hopefully get the user used to specifying `levels`.

**Comment by krivit** [comment]
How about now?

**Comment by martinamorris** [comment]
> 1. I think that documentation should mention both TRUE and NULL. TRUE is, as far as I am concerned, the canonical form, while NULL is an alias for it vaguely translating to "no filtering".

agreed.  i don't like either from the perspective of the naive user, but as you noted, NULL is somewhat more "meaningful" -- we can explain NULL as "you're not selecting or dropping any levels".

> 2. Since NULL is now semantically meaningful and broadly advertised as such, whereas most of the rest of the time it's a placeholder, it's important to change the defaults for levels in both InitErgmTerms and in the documentation to do whatever base/keep would do (i.e., typically the same value as keep and the negation of base). This would have been a problem when they were applied sequentially, but they no longer are.

agree

**Comment by martinamorris** [comment]
> 1. In the code, default for levels will remain NULL so things continue working.
> 3. In the documentation, the defaults will be set to -1 where base=1. This will hopefully get the user used to specifying levels.

Just to make sure I understand -- NULL is the default for levels UNLESS the term previously had a default for base or keep.  In the latter case, you're setting the default for levels to the equivalent base or keep default, yes?

**Comment by martinamorris** [comment]
made a few changes to the ergm-terms.Rd with sha faf49041.  not closing b/c i'll leave that to @krivit.

**Comment by krivit** [comment]
> Just to make sure I understand -- NULL is the default for levels UNLESS the term previously had a default for base or keep. In the latter case, you're setting the default for levels to the equivalent base or keep default, yes?

In the documentation, yes.

**Comment by martinamorris** [comment]
Are you saying it's not set as the default in the package?  Only in the documentation?

**Comment by krivit** [comment]
We have, at least nominally, a semantic that if given, `levels` overrides `base`. This is the most concise way to implement it given the time constraints: if `levels` is omitted, the level-getter is run with no filtering, then filtered by `base`. If it's given, the level-getter uses filtering, and then `base` filtering is skipped.

**Comment by martinamorris** [comment]
Typing is clearly not helping here.

I understand the "if levels then we ignore base/keep"

What I'm asking is if the user types `nodefactor("Race")` with no levels/base/keep argument, what is the default behavior now?  IIRC, the prior default would have been base=1.

**Comment by krivit** [comment]
The default behaviour is still to remove the first level.

**Comment by martinamorris** [comment]
perfect
