### ISSUE TITLE
Estimation on large networks using target stats hits error in ergm.pl

### ISSUE THREAD

**Issue by sgoodreau** [statnet/ergm#83]
Reproducible example:

```
library(ergm)
#n <- 1e3
n <- 1e4
my.net  <- network.initialize(n, directed=FALSE)
my.net <- set.vertex.attribute(my.net, 'sqrtage', runif(n, 18, 65)^0.5)
my.target.stats  <- c(0.4*n, 0.001*n, 0.7*0.4*n)
my.fit  <- ergm(my.net~edges+degree(2)+absdiff('sqrtage'), 
                target.stats = my.target.stats)
```
It works fine for a network of size 1e3, but not 1e4.  What seems to happen is that inside `ergm.pl`, there is a check on line 80 that sees that it is a large, sparse network with many unique dyads, and decides to do case-control MPLE.  That method then tries to build an edgelist (line 87), but since there are no edges in the target.stats case, `Clist$tails` and `Clist$heads` are `NULL`, and the code as written stops with the error:

```
Error in UseMethod("as.edgelist") : 
  no applicable method for 'as.edgelist' applied to an object of class "NULL"
Error: $ operator is invalid for atomic vectors
```

I am using `ergm 3.9.4` (latest on CRAN), although I've checked the github master branch code for `ergm.pl` and it seems to be the same.  Between the two of us, @sestansfield and I have replicated the problem on our local machines, the CSDE windows TS, the RStudio unix server, and Hyak.

**Comment by sgoodreau** [comment]
Aha, it looks like the line for constructing the edgelist had a different syntax in `ergm 3.8`.

**Comment by krivit** [comment]
Appears to be fixed in current `master`.
