### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dth2** [statnet/ergm#92]
I just tried to install ergm for github and I returned an error:

Error in once(ergm_Init_inform) : could not find function "once"

is once supposed to be an ergm function?  if not what package is it from?

**Comment by martinamorris** [comment]
once is the new function Pavel wrote to limit the number of warnings.

tried a github install on my windows laptop just now and didn't get an 
error

**Comment by dth2** [comment]
I got the error from a cran install.  I am installing from git now.

**Comment by dth2** [comment]
Correction, it was a github install.  I just tried remotes::install_github(“statnet/ergm”, dependencies =TRUE) and got this:

** byte-compile and prepare package for lazy loading
Error in once(ergm_Init_inform) : could not find function "once"
Error: unable to load R code in package ‘ergm’
Execution halted
ERROR: lazy loading failed for package ‘ergm’
* removing ‘/homes/dth2/R/x86_64-pc-linux-gnu-library/3.6/ergm’
* restoring previous ‘/homes/dth2/R/x86_64-pc-linux-gnu-library/3.6/ergm’
Error in i.p(...) :
  (converted from warning) installation of package ‘ergm’ had non-zero exit status

**Comment by dth2** [comment]
I also tried from ergm-private and got the same error.

**Comment by dth2** [comment]
Installing network and statnet.common from github solved the problem.

**Comment by krivit** [comment]
@dth2 , also, `statnet.common` with those functions has been on CRAN for a while now.
