### ISSUE TITLE
malformed printing of `constraints` attribute for `simulate` results

### ISSUE THREAD

**Issue by chad-klumb** [statnet/ergm#93]
Currently the `constraints` attribute of `simulate` results is printed in an odd way, e.g. the code

```
require(ergm)
data(florentine)
mod <- ergm(flomarriage ~ edges + nodecov("wealth"))
sim <- simulate(mod, nsim = 100)
sim
```
gives the print summary of `sim` as

```
Number of Networks: 100 
Model: flomarriage ~ edges + nodecov("wealth") 
Reference: ~Bernoulli 
Constraints: TNT NULL 16   , 1    , 15   , 2    , 14   , 3    , 13   , 4    , 12   , 5    , 11   , 6    , 10   , 7    , 9    , 8    , 8    , 9    , 7    , 10   , 6    , 11   , 5    , 12   , 4    , 13   , 3    , 14   , 2    , 15   , 1    , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, TRUE , FALSE, FALSE, 1    , FALSE, FALSE Bernoulli, MPLE     , CD       , zeros     ergm 
Parameters:
         edges nodecov.wealth 
   -2.59492903     0.01054591 
```
I think this probably isn't what we want to print for `Constraints`.

AFAIK TNT isn't technically a constraint (rather it's a proposal); I'd rather see `NULL` or `None` than `TNT` if there are no constraints in effect.  Or perhaps we could just print the constraint formula, whether or not it contains any constraints?

(The funny printing continued to happen even if contraints were used, although `TNT` was replaced by something like `CondDegree` or `CondDegreeDist`, reflecting the constraint used, although again, these are technically proposals, not constraints.)

This is related to statnet/statnetWeb#66 (the `sum[4]` warning comes when trying to copy the `constraints` attribute of a `simulate` result).

It might be worth looking at the `'constraints'` attribute of the `simulate` results and seeing if it is what we want it to be.  Even if it is, at a minimum we should change how it's printed (IMO).

Got this behavior with both CRAN and github master ergm.

**Comment by chad-klumb** [comment]
This is also in the new version of the ergm workshop html:

![Untitled2](https://user-images.githubusercontent.com/10733914/59545730-8d39d080-8ed7-11e9-920f-fa51d7bde763.png)

I don't think it's a version issue (I'm pretty sure I have the most up-to-date version of everything).

**Comment by martinamorris** [comment]
that's ugly...

**Comment by krivit** [comment]
Indeed. I am surprised it's new. What happens in the ordinary course of things is that a `constraints=` argument is used to initialise the `ergm_proposal`, which then replaces it. (In fact, you can pass an `ergm_proposal` object to the `constraints=` argument.

It looks like that new value for `constraints=` now gets printed as well. I am guessing that this was introduced when `simlulate.formula()` was split into `simulate.formula()` and `simulate.ergm_model()`.

**Comment by krivit** [comment]
Medium-term, one thing we can do is take advantage of something that `R CMD check` can do that we don't use: if a `tests` directory contains `Rout` files, it'll trigger an error if the output produced by the corresponding test does not match that of that file. There are some disadvantages however:
1. We have to set the random seed in all tests, which may result in a "lucky" seed that works while others don't.
2. False positives will abound: it only takes one extra `runif()` call somewhere to shift the random number stream.
3. There is probably a way to do it with `testthat` as well, but I don't know what it is.

**Comment by krivit** [comment]
Fixed in the above-mentioned commits.
